nrfconnect/sdk-zephyr

dts/arm/nordic/nrf52832.dtsi, dts/arm/nordic/nrf52833.dtsi, dts/arm/nordic/nrf52840.dtsi, dts/arm/nordic/nrf5340_cpuapp_peripherals.dtsi
This is a fromtree commit that disables NFCT by default. 
This allow us use Kconfig option generated from device tree to configure the NFCT  as GPIOS in TF-M.
Ref: NCSDK-24437
=> [nrf fromtree] dts: arm: nordic: keep NFCT disabled by default

include/zephyr/bluetooth/audio/bap.h, subsys/bluetooth/audio/bap_stream.c
By exposing the underlying iso channel, the application can retrieve properties of the iso channel.
This can be useful in case the application wants to use the connection handle for vendor specific HCI commands or to retrieve the particular parameters used for the given channel.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
(cherry picked from commit 75973852bfb0328957b2bf86cfbe67e1139ee2c0)
=> [nrf fromtree] Bluetooth: Audio: Add iso_chan to bt_bap_ep_info

include/zephyr/net/wifi_mgmt.h, subsys/net/l2/wifi/wifi_shell.c
1. Use getopt API to process the arguments passed with connect command.
2. Add support for BSSID configuration in connect call.
=> Add support to configure BSSID in Wi-Fi connect command

modules/openthread/platform/crypto_psa.c
OpenThread requires `otPlatCryptoPbkdf2GenerateKey` to be implemented by platform if PSA Crypto API is used. For ncs v2.6.0 PSA Crypto API doesn't yet fully support PBKDF2 generation. Because of that, calling `otPlatCryptoPbkdf2GenerateKey` results with `OT_ERROR_NOT_CAPABLE` error.
This commit provides a patch that allows a fallback to legacy MbedTLS implementation that follows the one provided by OpenThread.
=> [backport-ncs2.6][nrf noup] net: openthread: fix `otPlatCryptoPbkdf2GenerateKey` implementation

modules/mbedtls/Kconfig.psa
fixup! [nrf noup] modules: mbedtls: add PSA configurations
Deprecate PSA_WANT_KEY_TYPE_ECC_KEY_PAIR since it was removed from the Oberon PSA core.
=> [nrf noup] modules: mbedtls: add PSA configurations

tests/drivers/i2s/i2s_api/src/main.c, tests/drivers/i2s/i2s_api/src/test_i2s_errors.c
Add more tests cases in the i2s driver error management area
Signed-off-by: Bartosz Miller <bartosz.miller@nordicsemi.no>
(cherry picked from commit 32dd4ec4e89b1ebf43ef108adf8090ccf461703c)
=> [nrf fromtree] drivers: Extend coverage for i2s driver

scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py
add --dev-id to flashing command also when nrfutil runner is used.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71532
=> [nrf fromlist] twister: pytest: hardware_adapter: adapt to nrfutil.

boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.yaml
add twister yaml to support PDK 0.3.0 in tests
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71375
=> [nrf fromlist] boards: nrf54l15pdk_nrf54l15_cpuapp: yaml for PDK 0.3.0

subsys/net/ip/tcp.c, tests/net/tcp/src/main.c
Pull fixes for FIN with data case from the upstream, along with some predependencies to reduce the number of conflicts. 
I've also pulled the new test case, to make sure the fix works well with the older code base.
Fixes SHEL-2687
=> [v3.4.99-ncs1-branch] net: tcp: FIN with data fixes

boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp-pinctrl.dtsi, boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp.dts, samples/subsys/mgmt/mcumgr/smp_svr/boards/nrf54l15pdk_nrf54l15_cpuapp_ext_flash.overlay, samples/subsys/mgmt/mcumgr/smp_svr/sample.yaml, soc/common/nordic_nrf/Kconfig.peripherals
Configuration for MCUboot and smp_svr which
allows to use nRF54L15pdk external flash as location for the secondary partition.
For testing, see usage in [the manifest PR](https://github.com/nrfconnect/sdk-nrf/pull/14838) description.
=> Nrf54l15 ext flash smp svr

tests/drivers/counter/counter_basic_api/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/counter/counter_basic_api/boards/nrf54h20dk_nrf54h20_cpurad.overlay, tests/drivers/counter/counter_basic_api/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
Add nRF54L15 overlay for counter_basic_api test.
Signed-off-by: Magdalena Pastula <magdalena.pastula@nordicsemi.no>
(cherry picked from commit 1e20632b3675e064fe8c53a3e398defa99592c9a)
=> [nrf fromtree] tests: drivers: counter: add nRF54L15 overlay

samples/tfm_integration/psa_crypto/sample.yaml
We have our own psa crypto samples to show how to used PSA crypto with NCS.
This sample still uses CONFIG_MBEDTLS_BUILTIN which is not supported anymore, therefore removing the support for it in NCS.
Ref: NCSDK-17944
=> [nrf noup] samples: psa_crypto: Remove support for Nordic boards

modules/openthread/platform/crypto_psa.c
This reverts commit 28ac23896bacca886d8cf0acc580b6c423e268fc.
Pbkdf2 support is now available in TFM.
Therefore commit 85bc24eb0731cef2275529633c6f4a915ae8f6ed "net: openthread: Add PSA implementation for PBDKF2 genkey" can be restored.
=> Revert "[nrf noup] Revert "net: openthread: Add PSA implementation for PBDKF2 genkey""

drivers/regulator/regulator_common.c, drivers/regulator/regulator_fake.c, dts/bindings/regulator/adi,adp5360-regulator.yaml, dts/bindings/regulator/nordic,npm1300-regulator.yaml, dts/bindings/regulator/nordic,npm6001-regulator.yaml, dts/bindings/regulator/regulator.yaml, dts/bindings/regulator/x-powers,axp192-regulator.yaml, dts/bindings/regulator/zephyr,fake-regulator.yaml, include/zephyr/drivers/regulator.h, tests/drivers/regulator/api/app.overlay, tests/drivers/regulator/api/src/main.c
Added regulator-boot-off option to common regulator driver.
=> drivers: regulator: common: Added regulator-boot-off

boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp.dts, drivers/adc/adc_nrfx_saadc.c, samples/drivers/adc/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, tests/drivers/adc/adc_api/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
Changes cherry picked from: https://github.com/zephyrproject-rtos/zephyr/pull/68692
=> Update adc driver to support nRF54L15

doc/releases/release-notes-3.7.rst, include/zephyr/net/wifi_mgmt.h, subsys/net/l2/wifi/wifi_mgmt.c, subsys/net/l2/wifi/wifi_shell.c
Support to set rts threshold.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71077
=> [nrf fromlist] net: wifi_mgmt: Setting RTS threshold

subsys/net/l2/wifi/wifi_nm.c
Use lock while accessing iface data.
One of the use case is while setting regulatory, it access iface info, while from some other place also it can be accessed. Protected the data processing.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71737
=> [nrf fromlist] net: mgmt: Protect processing of iface data

include/zephyr/net/net_stats.h, subsys/net/l2/wifi/wifi_shell.c
Unicast RX stats
It represents total number of unicast (any type data, action or any other unicast frames) frames received at firmware level. The actual frames passed to host will be different as firmware may drop packets or some packets may be dropped because of errors.
Unicast TX stats
Transmission side the unicast packets count states the packets handed over to firmware. The stats taken at firmware level. Actual packets transmission may vary depending upon various factors.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71917
=> [nrf fromlist] net: wifi: Unicast frames statistics

subsys/mgmt/mcumgr/grp/os_mgmt/src/os_mgmt.c
There are two fixes now.
Previously there has been one, but it required conflict resolution at cherry-pick as there has been previous change missing;
this time both changes are brought.
=> [nrf fromtre] mcumgr/img_mgmt: CONFIG_MCUBOOT_BOOTLOADER_NO_DOWNGRADE fixes

boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20-pinctrl.dtsi, boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20_cpuapp.dts, boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp-pinctrl.dtsi, boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp.dts, boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp_0_3_0.overlay
Adds support for first possible LED to be connected with HW PWM.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/72010
=> [nrf fromlist] boards: nordic: Add PWM support for LEDs on nRF54 DKs

kernel/banner.c
Makes the boot banner function weak, this resolves an issue when building with llext enabled which uses different build options than a normal zephyr build
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/72400
=> [nrf fromlist] kernel: banner: Make function weak

boards/nordic/nrf54l15pdk/nrf54l15pdk_nrf54l15_cpuapp.yaml
It will enable testing adc with twister which is relying on board yaml data in determining test scope.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/68692.
This change was missed in previous [nrf fromlist] for this upstream PR.
=> [nrf fromlist] boards: nordic: Add ADC to supported in nRF54L15 PDK

subsys/ipc/ipc_service/backends/ipc_icbmsg.c
This change works around the issue with the semaphore timeout during
the Bluetooth HCI driver initialization when the bt_enable function
is called in the context of the System Workqueue thread. This issue
only affects platform that use the IPC service and its ICBMsg backend
(e.g. the nRF54H20 DK target).
The bt_enable function, when called in the System Workqueue context,
results in a deadlock, as the waiting semaphore of the Bluetooth HCI
driver times out:
bt_hci_driver: Endpoint binding failed with -11
During the Bluetooth HCI driver open operation in the context of the
bt_enable function, the driver code waits using the semaphore for the
endpoint binding process of the IPC service module to finalize. The
issue occurs when the waiting occurs in the System Workqueue context.
The ICBMsg …
=> [nrf fromlist] ipc: ipc_service: icbmsg backend: workaround endpoint binding deadlock

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi
Move global RAM0x regions to align with the documentation.
(cherry picked from commit b8338f956d937d6dce3af43f3da93a2c1caa06ec)
=> [nrf fromtree] boards: nordic: nrf54h20dk: Update memory map

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-pinctrl.dtsi, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, drivers/spi/Kconfig.dw, drivers/spi/spi_dw.c, drivers/spi/spi_dw.h, dts/bindings/spi/nordic,nrf-exmif.yaml, dts/common/nordic/nrf54h20.dtsi, include/zephyr/dt-bindings/pinctrl/nrf-pinctrl.h, samples/drivers/jesd216/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, soc/nordic/nrf54h/Kconfig.defconfig
Note: Contains one [noup] commit.
=> EXMIF support in NCS

drivers/cache/Kconfig.nrf, drivers/cache/cache_nrf.c, soc/nordic/nrf54h/Kconfig, soc/nordic/nrf54h/soc.c, west.yml
DCACHE is by default enabled for nrf54h20.
=> soc: nordic: nrf54h: Remove redundant ICACHE Kconfig and add enabling DCACHE

MAINTAINERS.yml
Fix few more paths that are failing to parse on system running Python >= 3.11 due to a change in behavior of glob.
Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
(cherry picked from commit 0ef608a0ab3e90ba28b9f50862a207a0fc64af66)
=> [nrf fromtree] MAINTAINERS: fix more paths

include/zephyr/net/ethernet.h, subsys/net/l2/ethernet/Kconfig, subsys/net/l2/ethernet/arp.c, subsys/net/l2/ethernet/vlan.c, tests/net/vlan/src/main.c
Add support for gratuitous ARP transmission by Zephyr network stack. This allows to prematurely fill the peer ARP table, so there's no need to send an explicit request when peer needs to send an actual packet.
The gratuitous ARP is send when the network interface is brought up (joins the network) or a new IP address is added. The gratuitous ARP request is also sent periodically, with a configurable interval time. The gratuitous ARP should also be sent whenever MAC address of the interface is changed, but as Zephyr only allows to do this when interface is down, this is already covered by the first case (interface brought up).
=> [nrf fromtree] net: arp: Add support for gratuitous ARP transmission

subsys/net/ip/net_if.c
It may happen that the interface is up but not yet running when we issue the rejoin_ipv6_mcast_groups(). This can be fixed by calling this function again right after the iface is set to 'running' state in the notify_iface_up handler.
Signed-off-by: Marcin Kajor <marcin.kajor@nordicsemi.no>
(cherry picked from commit b571e45d80923a786979460f218618e2000da8f3)
=> [nrf fromtree] net: if: Extend the usage of rejoining the multicast groups

subsys/bluetooth/mesh/blob_io_flash.c
Adapts flash writing for BLOB IO to RRAM. The previously used write block alignment is not needed for RRAM.
(cherry picked from commit 0f416b3576d2b259f1bf4f381d8cae430bb41d2a)
=> [nrf fromtree] bluetooth: mesh: Adapt BLOB IO to RRAM write size

subsys/net/ip/ipv6_mld.c
In case of successful submission, the reference shouldn't be put down, this only should done on error cases.
As reference is put down on success, during the buffer unref, no action is taken due to an uint8 overflow (ref is now 255), so, the buf->frags isn't cleared properly and the next time the frags is used and when L2 inserts a second frag, the first head frag and next frag are same (due to buffer re-use) causing an infinite loop in either net_buf_frag_last or net_pkt_get_len.
Signed-off-by: Chaitanya Tata <Chaitanya.Tata@nordicsemi.no>
(cherry picked from commit 09048e0a16b368c6e4feea4b655c807ccad26357)
=> [nrf fromtree] net: ipv6: mld: Fix improper reference drop

samples/sensor/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/sensor/qdec/sample.yaml
Add overlay file that enables sample on nrf54h20 Application core.
(cherry picked from commit f84e082f73511789eab69577521a16040b8e1fce)
=> [nrf fromtree] samples: sensor: qdec: Run sample on nrf54h20

lib/posix/options/env.c
Fix 2 build warnings in posix/options/env:
The maximum length given to strncpy() matches the input string length, which makes the call equivalent to strcpy(). As the destination buffer size has been ensured sufficient (in the first case by chechking just before,
in the second case by allocating it big enough),
let's just use strcpy() instead.
lib/posix/options/env.c: In function 'getenv_r':
lib/posix/options/env.c:109:17: error: 'strncpy' specified bound depends on the length of the source argument
[-Werror=stringop-truncation]
109 |                 strncpy(buf, val, vsize);
|                 ^~~~~~~~~~~~~~~~~~~~~~~~
lib/posix/options/env.c:104:25: note: length computed here
104 |                 vsize = strlen(val) + 1;
|                         ^~~~~~~~~~~
lib/posix/options/env.c: In …
=> posix: env: Fix 2 build warnings

boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20-memory_map.dtsi
Move global RAM0x regions to align with the documentation.
_Note: required to support latest SDFW_
=> [v2.6.99-cs2] boards: nordic: nrf54h20dk: Update memory map

include/zephyr/dt-bindings/pinctrl/nrf-pinctrl.h
New nRF54H20 SoC series expose more ports, e.g. P9, so reserve more bits for the Port+Pin field.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73097
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>
(cherry picked from commit 8ffa1fa4a89734ec78017ff5e05c335480f1daa8)
=> [nrf fromlist] dt-bindings: pinctrl: nrf: allow for more ports

boards/nordic/thingy53/Kconfig.sysbuild, scripts/pylib/twister/twisterlib/handlers.py, scripts/pylib/twister/twisterlib/runner.py, scripts/pylib/twister/twisterlib/testinstance.py, scripts/tests/twister/test_handlers.py, scripts/tests/twister/test_runner.py, scripts/west_commands/build.py
Adds a sysbuild Kconfig file which enables external flash when partition manager is enabled
=> sysbuild changes

include/zephyr/storage/flash_map.h, tests/subsys/storage/flash_map/src/main.c
adds size, offset and divice access macros that are operating with nodes as an argumet.
=> [nrf fromlist] include: storage: flash_map: _NODE macros

samples/subsys/mgmt/mcumgr/smp_svr/sample.yaml
In sample.yaml:
`SB_CONFIG_PARTITION_MANAGER=n` moved to extar_args as extra_config can't handle property with `SB_` prefix.]
REf.: https://github.com/nrfconnect/sdk-zephyr/pull/1636#pullrequestreview-2068729246
=> [nrf noup] samples/**/smp_svr: fix SB_CONFIG_PARTITION_MANAGER injection

.github/test-spec.yml
nrf-squash! [nrf noup] test-spec: include nrf54 boards in low-level test trigger
nrf-squash! [nrf noup] test-spec: introduce specific ble-sample label
nrf-squash! [nrf noup] ci: add .github/test-spec.yml
/boards/arm -> /boards/nordic
=> [noup] test-spec: update boards paths for HWv2

dts/common/nordic/nrf54h20.dtsi
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/72810
Add a definition of SUIT storage, so there will be a common source of the SUIT storage location for both SDFW and scripts generating SUIT storage areas, assigned to local domains.
=> [nrf fromlist] boards: nrf54h20dk: Add SUIT storage definition

samples/bluetooth/direction_finding_connectionless_tx/src/main.c
BT_GAP_ADV_SLOW_INT_MIN and BT_GAP_ADV_SLOW_INT_MAX represent 1s and 1.2s, respectively, in the extended advertising context, where the bit interval is 0.625 ms. Using them for periodic advertising will result in a range of [2s, 2.4s], as the bit interval for periodic advertising is 1.25ms.
Instead, BT_GAP_PER_ADV_SLOW_INT_MIN and BT_GAP_PER_ADV_SLOW_INT_MAX should be used in this sample, and the range will become [1s, 1.2s].
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73418
=> [nrf fromlist] samples: Bluetooth: use correct periodic advertising intervals

subsys/net/lib/shell/iface.c
Add option for setting a random MAC address to
the net iface set_mac command. With random option
a random MAC address can be assigned to an interface. [SHEL-2352].
[SHEL-2352]: https://nordicsemi.atlassian.net/browse/SHEL-2352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [nrf fromtree] net: shell: Add random MAC address generation

subsys/net/l2/wifi/wifi_utils.c
When channel range is configured in scan params, get the channel count from `chan_idx` instead of taking a difference of start and end of the channel range. The `difference` method fails in case of 5GHz band since channels may not be consecutive numbers.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73312
=> [nrf fromlist] wifi: utils: Get correct channel count

subsys/bluetooth/mesh/Kconfig, subsys/bluetooth/mesh/adv_ext.c
Disable processing of extended ADV packets by mesh scanner. This is done to prevent loss of scan time due to reception of pointer packets while scanning for mesh packets.
=> [nrf noup] Bluetooth: Mesh: Disable processing of ext ADV packets

subsys/net/lib/lwm2m/lwm2m_message_handling.c
Fix the error where we reply with wrong NUM field on block-wise write.
=> net: lwm2m: Fix NUM field on CoAP Block-Wise write

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.yaml
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73408
Define the default DFU partition.
=> [nrf fromlist] boards: nrf54h20dk: Add default DFU partition

subsys/net/l2/wifi/wifi_shell.c
The control and data settings are set improperly for packet filter operation for sniffer operation. The change sets them properly.
=> [nrf fromlist] net: wifi_shell: Resolve filter settings mismatch

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.yaml, tests/boards/nrf/i2c/i2c_slave/testcase.yaml
Add i2c to supported peripheral to enable i2c testing.
Signed-off-by: Sebastian Głąb <sebastian.glab@nordicsemi.no>
(cherry picked from commit 955dbf47f8ca8c0151807df88eefa9b1c910852b)
=> [nrf fromtree] tests: nordic: Enable I2C tests

boards/nordic/thingy53/Kconfig.sysbuild
Changes the default MCUboot mode to update only for the thingy53, to align with previous bootloader builds
=> [nrf noup] board: nordic: thingy53: Default to update only MCUboot type

boards/nordic/nrf54h20dk/board.cmake, boards/nordic/nrf54h20dk/support/nrf54h20_cpuapp.JLinkScript
A custom reset scheme is required for the nRF54H20 SoC so that debug works out of the box. This magic will eventually be part of JLink.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73771
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>
(cherry picked from commit a18d9b6ac9471de9e25ede8abc7cfffa121853be)
=> [nrf fromlist] boards: nordic: nrf54h20dk: add custom JLink reset scheme

boards/nordic/thingy53/Kconfig.sysbuild
Removes selecting SECURE_BOOT as this is now an automatic selection
=> [nrf noup] boards: nordic: thingy53: Remove old SECURE_BOOT selection

west.yml
Update hal_nordic with fix in nrfx_gpiote.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73704
Signed-off-by: Magdalena Pastula <magdalena.pastula@nordicsemi.no>
(cherry picked from commit f5bb97abb6dd0e20b689b4058b341dbbc427be29)
=> [nrf fromlist] manifest: update hal_nordic with nrfx_gpiote fix

boards/nordic/nrf54h20dk/nrf54h20dk_bicr.dtsi
Adjustment LFXO CLOAD value. New value is a resualt of DK's characterization.
=> [nrf noup] dts: nordic: LFXO crystal settings adjustment

subsys/net/lib/sockets/sockets_service.c
In case of thread failure, fix the registrations by properly managing the synchronization i.e. use conditional wait only if thread is being initialized or will be initialized, else check for success or failure without waiting for conditional variables.
Fixes #73523.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73524
=> [nrf fromlist] net: sockets_service: Fix thread failure

cmake/modules/kconfig.cmake
kconfig_soc_root was mistakenly set to value of BOARD_ROOT. Fix this by correctly set kconfig_soc_root to the value of SOC_ROOT.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74057
(cherry picked from commit e7aef7ffb9b197efd914fe402621b63d28551f9e)
=> [nrf fromlist] cmake: use SOC_ROOT for SoCs instead of BOARD_ROOT

drivers/serial/Kconfig.nrfx, drivers/serial/Kconfig.nrfx_uart_instance, drivers/serial/uart_nrfx_uarte.c
Legacy shim takes less flash so it should be a first choice on cores with less code memory (like RISCV cores on nrf54h20). Adding new instances support to the legacy shim.
(cherry picked from commit d07b13dbc203be8066e9f840edf917dd8969ce00)
=> [nrf fromtree] drivers: serial: nrfx_uarte: Use of legacy shim on RISCV

boards/nordic/nrf21540dk/doc/index.rst, boards/nordic/nrf51dk/doc/index.rst, boards/nordic/nrf51dongle/doc/index.rst, boards/nordic/nrf52833dk/doc/index.rst, boards/nordic/nrf52840dk/doc/index.rst, boards/nordic/nrf52840dongle/doc/index.rst, boards/nordic/nrf52dk/doc/index.rst, boards/nordic/nrf5340_audio_dk/doc/index.rst, boards/nordic/nrf5340dk/doc/index.rst, boards/nordic/nrf9131ek/doc/index.rst, boards/nordic/nrf9151dk/doc/index.rst, boards/nordic/nrf9160dk/doc/index.rst, boards/nordic/nrf9161dk/doc/index.rst, boards/nordic/thingy52/doc/index.rst, boards/nordic/thingy53/doc/index.rst
As the Infocenter will soon be taken offline, updating links to point to TechDocs.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73693
Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>
(cherry picked from commit ce1ade30b61d889cbc595ae84e419c34d4ab419f)
=> [nrf fromlist] doc: update Infocenter links to TechDocs links

dts/arm/nordic/nrf54l15_cpuapp.dtsi
When TF-M is used, zephyr must use a different interrupt line for GRTC.
Signed-off-by: Vidar Lillebø <vidar.lillebo@nordicsemi.no>
(cherry picked from commit 1fcbddc02a462e6fe7d5c36a16ef2fe925d87ae4)
=> [nrf fromlist] nordic: dts: Fix grtc interrupt line for secure nRF54L

subsys/bluetooth/host/hci_core.c
If the new encryption state is the same as the old one, there's no point in doing additional processing or callbacks. Simply log a warning and ignore the HCI event in such a case.
(cherry picked from commit bf363d7c3e4614ebc9b7e7a051657ae6fde6283b)
=> [nrf fromtree] Bluetooth: Host: Avoid processing "no change" encryption changes

soc/CMakeLists.txt
While all in-tree SoCs have been ported to HWMv2, Zephyr still supports out-of-tree SoCs in HWMv1 format, including boards. Add a clear deprecation message so that users get notified that this is a deprecated feature to be removed in the future.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74143
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>
(cherry picked from commit 5301880b6f5b73337b02e7c9bd5498f70d11fd48)
=> [nrf fromlist] soc: add deprecation warning if using HWMv1 SoCs

samples/sysbuild/hello_world/sysbuild.cmake
PM support is still required for nRF53 in the context of NCS.
=> [nrf noup] samples: sysbuild: hello_world: support PM on nRF53

scripts/west_commands/build.py
`west build` can be invoked without specifying the source directory when being invoked from the source directory itself.
When using `west build` for incremental builds, then the build command will examine the CMake cache to determine the application dir by using the value of CMAKE_HOME_DIRECTORY.
With sysbuild, this leads to the wrong assumption that the sysbuild itself is the application to build.
Instead, have west build look for APP_DIR which points to the correct source dir when sysbuild is used. Use APPLICATION_SOURCE_DIR when APP_DIR is not set, as this indicates a no-sysbuild build.
Keep CMAKE_HOME_DIRECTORY behavior as last fallback mechanism.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74230
=> [nrf fromlist] west: update build extension command to use APP_DIR

doc/services/storage/nvs/nvs.rst, subsys/fs/nvs/Kconfig, subsys/fs/nvs/nvs.c, subsys/fs/nvs/nvs_priv.h, tests/subsys/fs/nvs/src/main.c, tests/subsys/fs/nvs/testcase.yaml
Cherry-picked upstream commits that add CRC-32 protection to NVS.
=> [nrf fromtree] fs: nvs: Add CRC to protect the data part of the NVS items

doc/develop/test/twister.rst, scripts/pylib/pytest-twister-harness/src/twister_harness/plugin.py, scripts/pylib/pytest-twister-harness/src/twister_harness/twister_harness_config.py, scripts/pylib/twister/twisterlib/handlers.py, scripts/pylib/twister/twisterlib/harness.py, scripts/pylib/twister/twisterlib/testinstance.py, scripts/tests/twister/pytest_integration/test_harness_pytest.py, scripts/tests/twister/test_harness.py, tests/drivers/can/host/README.rst, tests/drivers/can/host/pytest/conftest.py
Required to make tests/can/driver/host to work
=> [nrf fromtree] Extend twister fixture options

modules/hal_nordic/nrfx/Kconfig, modules/hal_nordic/nrfx/nrfx_glue.h
The list of reserved PPIs by MPSL should be kept if MPSL is enabled. The 802154 radio driver is not the only user of MPSL.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74139
Quoting original PR
> This is a blocker for Garmin's ANT stack that also uses MPSL.
Their application/stack doesn't start up at all without this fix.
=> [nrf fromlist] hal_nordic: Fix reserved PPI faulty logic

samples/drivers/adc/adc_dt/src/main.c, samples/drivers/adc/adc_sequence/src/main.c
Sample must end to dump coverage data.
Signed-off-by: Bartlomiej Buczek <bartlomiej.buczek@nordicsemi.no>
(cherry-picked from commit 79f4f2ac31cbba648ae4bc6066e7da77a1688fd7)
=> [nrf fromtree] samples: drivers: adc: Allow coverage calculation.

subsys/bluetooth/host/Kconfig.gatt, subsys/bluetooth/host/att.c, subsys/bluetooth/host/conn.c
By default, the BLE stack calls sent callback for ATT data when the data is passed to BLE controller for transmission. Enabling this Kconfig option delays calling the sent callback until data transmission is finished by BLE controller (the callback is delayed until receiving the num complete packets event).
PR also allows for an extra ref in bt_conn_send_cb (needed for the newly added feature).
Jira: NCSDK-27422
=> [nrf noup] bluetooth: att: Allow ATT sent callback after data TX is done

scripts/west_commands/runners/nrf_common.py
In order for the --recover option to work properly on the nRF54H20, it requires executing it for both cores, the radio and the application one. Extend the recover_target() function so that it does so for both 53 and 54H20.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74489
=> [nrf fromlist] scripts: runners: nrf_common: Fix recover on 54H20

subsys/bluetooth/mesh/Kconfig, subsys/bluetooth/mesh/large_comp_data_srv.c, subsys/bluetooth/mesh/od_priv_proxy_srv.c, subsys/bluetooth/mesh/priv_beacon_srv.c
PR adds extension of the configuration model server by private beacon server and large composition data server.
According to Mesh Protocol specification v 1.1
4.4.11.1
The Mesh Private Beacon Server model is a main model
that extends the Configuration Server model.
4.4.21.1
The Large Composition Data Server is a main model
that extends the Configuration Server model.
=> [nrf fromtree] Bluetooth: Mesh: Fix missing model extensions

boards/nordic/nrf54h20dk/CMakeLists.txt, boards/nordic/nrf54h20dk/board.c, modules/hal_nordic/nrfs/Kconfig
Turn off suspending MRAM for NRF54H20 DK
This change is required so sections of code
depending on critical timings will not have unacceptable latency.
=> [nrf noup] boards: nordic: Turn off MRAM suspend for NRF54H20 DK

modules/hal_nordic/nrfs/Kconfig
Turn on NRFS globaly so turning off
suspending MRAM for NRF54H20 DK will work.
=> [nrf noup] boards: nordic: Turn on NRFS globally

boards/nordic/nrf54h20dk/board.c, modules/hal_nordic/nrfs/Kconfig
nrf-squash! [nrf noup] boards: nordic: Turn on NRFS globally
Signed-off-by: Jan Zyczkowski <jan.zyczkowski@no
=> [nrf noup] boards: nordic: By default turn off NRFS for ztest

subsys/testsuite/coverage/coverage.c
Don't attempt to lock the scheduler is trying to dump coverage information from an ISR. The scheduler won't run while the ISR is in progress.
Signed-off-by: Jordan Yates <jordan@embeint.com>
(cherry picked from commit e881445065f468652da6c77c59909ee3e9afa53b)
=> [nrf fromtree] testsuite: coverage: don't lock scheduler in ISR

modules/trusted-firmware-m/CMakeLists.txt
Incremental builds for TF-M are not picked up by Zephyr linking stage. Code changes to tf-m repository results in a rebuild of TF-M and thus an updated tfm_s.hex (and other files).
tfm_s.hex is merged together with the zephyr hex to form a final merged hex file for flashing. This is done as a post-build command, however such as step cannot take extra dependencies. The Zephyr target can have extra dependencies, however that will only ensure the dependency is brought up-to-date when Zephyr re-link, not re-linking Zephyr when the dependency changes.
Therefore an object dependency is placed on the interface.c file for Zephyr TF-M interface implementation, which ensures the tfm_api library is brought up-to-date whenever TF-M rebuilds, and this update again ensures the Zephyr itself is …
=> [nrf fromlist]: cmake: tf-m: create tfm_api dependency on tfm_s.hex

scripts/west_commands/build.py
nrf-squash! [nrf noup] scripts: west: build: Use sysbuild by default if in NCS dir
Adds the ANT project to the list of repos that should be built using sysbuild by default
=> [nrf noup] scripts: west_commands: build: Add ant to sysbuild list

tests/bluetooth/tester/src/btp_bap_broadcast.c, tests/bluetooth/tester/src/btp_cap.c
The Broadcaster setup has been hardcoded to include the BT_LE_PER_ADV_OPT_USE_TX_POWER parameter. This may cause incompabilities should the controller not support it, and since the feature may not be required for most broadcast tests it should not be forced.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73361
=> [nrf fromlist] bluetooth: tester: Adjust Broadcaster ext adv pars

subsys/bluetooth/controller/Kconfig
Add Kconfigs to enable experimental subrating HCI commands.
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>
(cherry picked from commit 570c86d1efb9409993571f139e9aad0fc181964d)
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>
=> [nrf fromtree] Bluetooth: Controller: Add Kconfigs to enable Connection Subrating

tests/drivers/pwm/pwm_api/src/test_pwm.c
Extend pwm driver test coverage.
Upstream PR: [zephyrproject-rtos/zephyr#75583](https://github.com/zephyrproject-rtos/zephyr/pull/75583)
=> [nrf fromlist] tests: drivers: pwm: pwm_api

modules/hal_nordic/nrfs/backends/nrfs_backend_ipc_service.c
In function nrfs_backend_send_work tx_data buffer was used in function ipc_service_send instead of
data_to_send. This is fixed and also tx_data and rx_data are moved to coresponding functions preventing such issues in future.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/75803
https://github.com/nrfconnect/sdk-nrf/pull/16422 to check CI
=> [nrf fromlist] modules: hal_nordic: nrfs: fix buffer used in nrfs send

.github/workflows/manifest-PR.yml
This action will automatically manage a PR to sdk-nrf once a PR to sdk-zephyr is created.
This includes:
- Creating an initial PR
- Updating and (optionally) rebase it once the PR to sdk-nrf is merged.
The action can be disabled by adding the string
"manifest-pr-skip" to the title or body of the PR.
This will simplify cherry-picking changes from upstream zephyr.
=> [nrf noup] ci: Enable action-manifest-pr

soc/nordic/nrf54l/CMakeLists.txt, soc/nordic/nrf54l/kmu_push_area_section.ld
Add a custom section in the linker which should always be placed in the top of RAM. This will be used by the KMU to push keys into it. Since when you provision a key into the KMU you need to set specific a memory location for the PUSH operation we need to keep this memory location static across images/dfus.
This is a noup since the KMU is not supported upstream.
Ref: NCSDK-25121
=> [nrf noup] soc: nrf54l: Add custom section for KMU

drivers/flash/Kconfig.nrf_rram
adjusting region resolution to match erase-block-size
=> [nrf noup] drivers: flash: kconfig: nrf_rram region resolution

tests/drivers/pwm/pwm_api/boards/nrf54h20dk_nrf54h20_cpuapp_fast.overlay, tests/drivers/pwm/pwm_api/testcase.yaml
Add fast PWM instance for nRF54H20 device.
=> [nrf fromlist] test: drivers: pwm: add fast PWM

tests/kernel/timer/timer_api/Kconfig, tests/kernel/timer/timer_api/src/main.c, tests/kernel/timer/timer_behavior/testcase.yaml
This commit provides an additional threshold value for comparison when a custom k_busy_wait() implementation is chosen.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73068
=> [nrf fromlist] tests: kernel: timer: Fix failing tests

drivers/spi/spi_nrfx_spim.c, tests/drivers/spi/spi_controller_peripheral/boards/nrf52840dk_nrf52840.overlay, tests/drivers/spi/spi_controller_peripheral/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, tests/drivers/spi/spi_controller_peripheral/testcase.yaml, tests/drivers/spi/spi_loopback/testcase.yaml
Enable the device runtime power management on the SPIM shim.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/75715
=> [nrf fromlist] drivers: spi: nrfx_spim: Add support for device PM

tests/drivers/adc/adc_error_cases/CMakeLists.txt, tests/drivers/adc/adc_error_cases/boards/nrf52840dk_nrf52840.overlay, tests/drivers/adc/adc_error_cases/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/adc/adc_error_cases/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay, tests/drivers/adc/adc_error_cases/prj.conf, tests/drivers/adc/adc_error_cases/src/main.c, tests/drivers/adc/adc_error_cases/testcase.yaml
Tests are checking error codes returned from adc_read() and adc_setup_channel() used with invalid configurations.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76191
=> [nrf fromlist] tests: drivers: adc: add adc_error_cases tests.

modules/openthread/platform/radio.c
When multicast packet is forwarded to the OpenThread stack it has to have its "multicast loop" flag enabled to be processed by the stack itself instead of only propagating it further.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76086
=> [nrf fromlist] net: l2: openthread: set multicast loop by default

tests/drivers/timer/nrf_grtc_timer/testcase.yaml
Add nRF54H20 cpu PPR target to GRTC tests.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76215
=> [nrf fromlist] tests: drivers: nrf_grtc: Add nRF54H20 PPR target

samples/drivers/mbox/src/main.c
The sample must end to dump coverage data.
Stop receiving to prevent callback from interrupting coverage dump.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76415
=> [nrf fromlist] samples: drivers: mbox: Allow coverage calculation

dts/arm/nordic/nrf54h20_cpurad.dtsi, modules/hal_nordic/nrf_802154/sl_opensource/platform/nrf_802154_clock_zephyr.c
* Adds missing device tree configs for dppic and ipct connections between the Radio core and the Global domains.
* Changes the ramp-up time from 1000us to 550us on nRF54H20. The time must fit inside general preconditions ramp up.
The hfclk time can be adjusted this way because the current solution is not precise until the clock_control is available.
=> Updates for radio driver with nRF54H20

subsys/testsuite/coverage/coverage.c
k_sched* are not avaliable when there is CONFIG_MULTITHREADING=n
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76550
=> [nrf fromlist] testsuite: coverage: allow disabled multithreading

west.yml
Brings in bsim updates that will unblock some testing efforts:
Including the following:
* 53635212 nRF54L15 MDK: Redefine NRF_RADIO_*_BASE to point to model
* 4a92c424 NHW_IPC: Fix out of bounds read
* 2dae79b5 RADIO: Add nRF54 support
* 4447a22a CLOCK,POWER,RESET: Add stubs for the 54L
* 6c389b9 PPI (52): Connect CCM TASK_RATEOVERRIDE
* 2056253 CCM: Change TASK RATEOVERRIDE warning to info
* 3ede171 GRTC: Expose nhw_GRTC_counter_to_time()
* 2726f8b RTC: Define nhw_rtc_start_time_get()
* cc6fb0f hal: hack: Add nrf_hack function for triggering a task
* 03ca9b5 MWU: Add registers stub
=> Bsim: Update to latest revision

include/zephyr/net/socket_ncs.h
This commit removes deprecated RAI socket options.
Deprecated back in version 2.6.0.
=> [nrf noup] include: net: socket_ncs: remove deprecated RAI

subsys/bluetooth/host/conn.c
If ATT sent callback is delayed until data transmission is done by BLE controller, the transmitted buffer may have an additional reference. The reference is used to extend lifetime of the net buffer until the data transmission is confirmed by ACK of the remote.
send_buf function can be called multiple times, if buffer has to be fragmented over HCI. In that case, the callback is provided as an argument only for the last transmitted fragment. The `buf->ref == 1` check is skipped because it's impossible to properly validate number of references for the sent fragments if buffers may have the additional reference.
Jira: NCSDK-28624
=> [nrf noup] bluetooth: conn: Skip buffer ref count check in send_buf

soc/nordic/nrf54h/soc.c
A single trigger of the TASK_FREQ_CHANGE task might not be enough, so trigger twice to make sure the frequency gets updated.
Signed-off-by: Karsten Koenig <karsten.koenig@nordicsemi.no>
(cherry picked from commit 16e7e46478f792980853cdd69f8aea3ae0d393bd)
=> [nrf fromtree] soc: nordic: nrf54h: Retrigger TASK_FREQ_CHANGE

soc/nordic/Kconfig
Allow CONFIG_NRF_APPROTECT_LOCK and
CONFIG_NRF_SECURE_APPROTECT_LOCK with TF-M with all the SOC's that support TF-M.
Signed-off-by: Markus Lassila <markus.lassila@nordicsemi.no>
(cherry picked from commit c44968486d2419334748fddf76690117c83d41af)
=> [nrf fromtree] soc: nordic: Fix APPROTECT with TF-M

drivers/flash/Kconfig.nrf_rram
RRAMC peripheral is a secure-only peripheral, and the application cannot use it directly. While building an application with TF-M enabled and SOC_FLASH_NRF_RRAM the NRFX_RRAMC selection must be forbidden.
Signed-off-by: Arkadiusz Balys <arkadiusz.balys@nordicsemi.no>
(cherry picked from commit 2de6274119c9e908784ac7729da6b215924c9cb5)
=> [nrf fromtree] drivers: flash: Do not select NRFX_RRAMC while buildig with TF-M

scripts/west_commands/runners/nrf_common.py
It is safer to base the SUIT artifacts path on the path of the configuration file than the HEX file that is being flashed. The latter may be overriden by several scripts that merge/transform the final firmware image.
Ref: NCSDK-26282
Upstream PR: zephyrproject-rtos/zephyr#76560
=> [nrf fromlist] scripts: nrf_common: Use cfg for SUIT paths

modules/hal_nordic/CMakeLists.txt
Version 5.5.1 of nrf-regtool is required for the IPC communication to/from secdom to work after the mbox compatible rename.
This noup commit is to be removed when synchronizing sdk-zephyr with upstream zephyr and a newer version of nrf-regtool is required.
=> Need exactly nrf-regtool v5.5.1 for SSF IPC

subsys/bluetooth/mesh/blob_srv.c
Initialize the missing chunk field when canceling a BLOB Transfer. If you canceled a BLOB Transfer, the missing_chunk was not cleared in the next BLOB Transfer. This can make it look like there are still missing chunks, even though all chunks in the block have already been received, and it does cause bugs.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/77315
=> Bluetooth: Mesh: Fix uninitialized field when cancelling transfer blob

drivers/hwinfo/Kconfig, drivers/hwinfo/hwinfo_nrf.c, drivers/serial/uart_nrfx_uarte.c, drivers/serial/uart_nrfx_uarte2.c, modules/hal_nordic/nrfx/nrfx_config_common.h, modules/hal_nordic/nrfx/nrfx_config_nrf52805.h, modules/hal_nordic/nrfx/nrfx_config_nrf52810.h, modules/hal_nordic/nrfx/nrfx_config_nrf52811.h, modules/hal_nordic/nrfx/nrfx_config_nrf52820.h, modules/hal_nordic/nrfx/nrfx_config_nrf52832.h, modules/hal_nordic/nrfx/nrfx_config_nrf52833.h, modules/hal_nordic/nrfx/nrfx_config_nrf52840.h, modules/hal_nordic/nrfx/nrfx_config_nrf5340_application.h, modules/hal_nordic/nrfx/nrfx_config_nrf5340_network.h, modules/hal_nordic/nrfx/nrfx_config_nrf54h20_application.h, modules/hal_nordic/nrfx/nrfx_config_nrf54h20_ppr.h, modules/hal_nordic/nrfx/nrfx_config_nrf54h20_radiocore.h, modules/hal_nordic/nrfx/nrfx_config_nrf54l15_enga_application.h, modules/hal_nordic/nrfx/nrfx_config_nrf54l15_enga_flpr.h, modules/hal_nordic/nrfx/nrfx_config_nrf91.h, west.yml
HWinfo depends on the nrfx v3.6.0 integration:
Combines commits from the following PRs:
- https://github.com/zephyrproject-rtos/zephyr/pull/75530 (HW info changes for nRF54H20)
- https://github.com/zephyrproject-rtos/zephyr/pull/76330 (nrf v3.6.0 integration)
=> Bring the Zephyr HWinfo driver changes into NCS

tests/bluetooth/tester/src/btp/btp_csip.h, tests/bluetooth/tester/src/btp_csip.c
_Note: The corresponding changes from this are already in our auto-pts repo, so this should fix a discrepancy..._
Refactor CSIP btp commands by removing the 'count' parameter from set_coordinator_lock and set_coordinator_release functions. If we want to support lock/release procedure on subset of set members in the future, 'count' param doesn't indicate a specific set member. Instead, introduce 'address_count' and 'addr' array params, although their usage is not yet implemented.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71059
=> [nrf fromlist] tests: bluetooth: tester: refactor CSIP btp command

scripts/pylib/twister/twisterlib/environment.py, scripts/pylib/twister/twisterlib/handlers.py, scripts/pylib/twister/twisterlib/harness.py, scripts/pylib/twister/twisterlib/testplan.py
Readline method sometimes receives more lines in buffer. Split them to avoid misinterpreting data in harness module.
(cherry picked from commit 79ef0b6b10dd97d8e734fe6a4104fe3bc5589640)
=> [nrf fromtree] twister: scripts: Split lines before processing

west.yml
A set of cherry-picks to update BabbleSim, the HW models & EDTT to the version used upstream.
=> Update bsim, HW models & EDTT to version used upstream

scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py, scripts/pylib/pytest-twister-harness/src/twister_harness/plugin.py, scripts/pylib/pytest-twister-harness/src/twister_harness/twister_harness_config.py, scripts/pylib/twister/twisterlib/harness.py
Pass flashing timeout to pytest-harness and use them.
Takes changes from Upstream Zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/77788
=> [nrf fromtree] twister: Pass device flash timeout to pytest-harness.

scripts/west_commands/build.py
fixup! [nrf noup] scripts: west: build: Use sysbuild by default if in NCS dir
Enables sysbuild by default for all repositories, NCS or otherwise
=> [nrf noup] scripts: west: build: Enable sysbuild by default globally

boards/nordic/nrf54l15dk/nrf54l15_cpuapp_common.dtsi, boards/nordic/nrf54l15dk/nrf54l15dk_nrf54l15_cpuflpr.dts
For both UARTs connected to debugger chip.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/78033
=> [nrf fromlist] boards: nordic: nrf54l15dk: enable HWFC

tests/drivers/timer/nrf_grtc_timer/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/timer/nrf_grtc_timer/src/main.c
Add more test cases for nRF GRTC timer
Signed-off-by: Bartosz Miller <bartosz.miller@nordicsemi.no>
(cherry picked from commit a49c649b9015f9c46e801363f95d65a6ed1b2efa)
=> [nrf fromtree] tests: drivers: Extend coverage for NRF GRTC timer

include/zephyr/net/wifi.h, include/zephyr/net/wifi_mgmt.h, subsys/net/l2/wifi/wifi_mgmt.c, subsys/net/l2/wifi/wifi_shell.c
PS exit stategy support in 2.6 branch (Ported changes from 2.5 branch)
=> [nrf noup] wifi_mgmt: Add support for configuring PS exit strategy

subsys/mgmt/mcumgr/grp/img_mgmt/Kconfig, subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c
Adds handling code to allow selecting the correct image slot when using QSPI XIP in DirectXIP mode
=> [nrf noup] mgmt: mcumgr: grp: img_mgmt: Add handling for QSPI XIP

modules/hal_nordic/nrfx/nrfe_config.h, modules/hal_nordic/nrfx/nrfx_glue.h
Add the possibility to mark DPPI channels as allocated for software-defined I/O devices.
=> modules: hal_nordic: nrfx: add DPPI channel allocation for NRFE

tests/bsim/run_parallel.sh
Let's filter out escape sequences from the tests
output (for ex. color escapes) as those corrupt
the xml.
Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
(cherry picked from commit c11fccdaddf9a5a9d1578fa77ef2ce5f661cbad3)
=> [nrf fromtree] tests: bsim: run_parallel: Avoid escape sequences in xml

include/zephyr/net/wifi.h
nrf-squash! [nrf noup] wifi_mgmt: Add support for configuring PS exit strategy
The comments were not updated when enumerations were swapped.
=> [nrf noup] wifi_mgmt: Fix comments for PS exit strategy choices

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi
Align settings and DFU partition definition with the values, specified by the design documentation.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/78240
=> [nrf fromlist] boards: nrf54h20dk: Fix settings partition

tests/drivers/mbox/mbox_error_cases/sample.yaml, tests/drivers/mbox/mbox_error_cases/src/main.c
mbox_error_cases tests must be run with the nordic-flpr snippet to prevent bus fault error while accessing VPR registers.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/75114
=> [nrf fromlist] tests: drivers: mbox: Fix for BUS FAULT on nrf54l15

drivers/timer/nrf_grtc_timer.c
GRTC needs to use direct clock source path instead of system clock path to support ELV mode for nRF54L targets.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/78082
=> [nrf fromlist] drivers: timer: grtc: Switch GRTC clock source to LFXO

subsys/logging/frontends/Kconfig, subsys/logging/frontends/log_frontend_stmesp.c, subsys/logging/frontends/log_frontend_stmesp_demux.c
Fixes for:
- unaligned access in STM frontend (RISCV only)
- ETR processing hanging when there is an incomplete message in the buffer
=> [nrf fromlist] logging: STM fixes

tests/drivers/timer/nrf_grtc_timer/boards/nrf54h20dk_nrf54h20_cpuppr.overlay
Test did not support PPR core due to failing GRTC channel allocation. This change fixes the channel allocation and enables PPR core test.
Signed-off-by: Bartosz Miller <bartosz.miller@nordicsemi.no>
(cherry picked from commit e26b9750ae32cf8232bf510a815c7b1eb93b4bfe)
=> [nrf fromtree] tests: drivers: Add PPR support in NRF GRTC timer test

include/zephyr/net/socket_ncs.h
Add SO_IPV6_DELAYED_ADDR_REFRESH socket option.
=> include: net: add delayed addr refresh socket option

include/zephyr/arch/arm/cortex_m/scripts/linker.ld
fixup! [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
Allows overriding the variable used for specifying how much SRAM a device has in partition manager by using the Kconfig value rather than the PM-generated config value
=> [nrf noup] include: arch: arm: cortex_m: linker: Add PM SRAM override

tests/bluetooth/tester/src/audio/btp_bap_broadcast.c, tests/bluetooth/tester/src/audio/btp_bap_broadcast.h
Adds a semaphor to make sure the stream has properly been stopped by the controller before returning from btp_bap_broadcast_source_stop.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79329
=> [nrf fromlist] bluetooth: tester: audio: Add check for bis stopping

subsys/mgmt/mcumgr/grp/os_mgmt/Kconfig, subsys/mgmt/mcumgr/grp/os_mgmt/src/os_mgmt.c
Required for SUIT solution in the following PR:
https://github.com/nrfconnect/sdk-nrf/pull/17301
=> Bootloader info command for other bootloaders than MCUboot

drivers/clock_control/clock_control_nrf2_common.c, drivers/clock_control/clock_control_nrf2_common.h, drivers/clock_control/clock_control_nrf2_fll16m.c, drivers/clock_control/clock_control_nrf2_hfxo.c, dts/common/nordic/nrf54h20.dtsi, soc/nordic/common/CMakeLists.txt, soc/nordic/common/soc_lrcconf.c, soc/nordic/common/soc_lrcconf.h, soc/nordic/nrf54h/power.c, soc/nordic/nrf54h/soc.c, soc/nordic/nrf54h/soc.h
Add LRC domain power management around idle. The Fast Clock Domain needs to be forced-on during CPU idle. Also the force needs to be disabled on idle-exit.
=> [nrf fromlist] soc: nordic: nrf54h20: Add LRC around idle

include/zephyr/mgmt/mcumgr/transport/smp_bt.h, subsys/mgmt/mcumgr/transport/src/smp_bt.c
Added the SMP service and characteristic UUIDs to the smp_bt module header and used those definitions.
Signed-off-by: Mateusz Kapala <mateusz.kapala@nordicsemi.no>
(cherry picked from commit 77555898de6cb2b0a1933edd35e97c7d55ac26e2)
=> [nrf fromtree] mgmt: mcumgr: Add SMP SVC and CHR UUIDs to header

scripts/logging/dictionary/log_parser.py, scripts/logging/dictionary/log_parser_uart.py, scripts/logging/dictionary/parserlib.py
This commit adds support to dictionary logging to parse binary data directly from input serial and generate the ascii logs.
Signed-off-by: Kumar Siddaramayya <harish.kumar@nordicsemi.no>
(cherry picked from commit a899deda2b0f53802cd232e0cb0f537167571f28)
=>  [nrf fromtree] scripts: logging: dictionary: Add uart support

include/zephyr/logging/log_output.h, subsys/logging/Kconfig.template.log_format_config, subsys/logging/backends/CMakeLists.txt, subsys/logging/backends/Kconfig, subsys/logging/backends/Kconfig.adsp, subsys/logging/backends/Kconfig.adsp_mtrace, subsys/logging/backends/Kconfig.ble, subsys/logging/backends/Kconfig.efi_console, subsys/logging/backends/Kconfig.fs, subsys/logging/backends/Kconfig.native_posix, subsys/logging/backends/Kconfig.net, subsys/logging/backends/Kconfig.rtt, subsys/logging/backends/Kconfig.semihost, subsys/logging/backends/Kconfig.spinel, subsys/logging/backends/Kconfig.swo, subsys/logging/backends/Kconfig.uart, subsys/logging/backends/Kconfig.xtensa_sim, subsys/logging/backends/log_backend_semihost.c, subsys/logging/log_output.c, subsys/logging/log_output_dict.c
Cherry-picked from https://github.com/zephyrproject-rtos/zephyr/pull/79506
=> logging: Fix case where logging strings were not stripped from the binary when dictionary logging was used

west.yml
This Pulls in PRF-256 code from upstream hostap. Picking a SHA commit which is 1 level above my commit SHA for upstream as there is a CI build fix in this SHA for my commit.
=> Pull in PRF-256 Implementation from upstream Hostap

boards/nordic/nrf54l20pdk/nrf54l20_cpuapp_common.dtsi, dts/common/nordic/nrf54l20.dtsi
The Softdevice Controller is enabled using the device tree. Added a device tree node that enables the SDC and disables the Zephyr Bluetooth controller on nRF54L20.
=> [nrf noup] dts: Select SoftDevice Controller DTS binding as default

samples/basic/blinky/boards/nrf54l15dk_nrf54l15_cpuapp_egpio.overlay
Align eGPIO overlay to nRF54L15 DK.
=> [nrf noup] samples: basic: blinky: align eGPIO overlay to L15 DK

drivers/entropy/Kconfig.nrf_prng, dts/arm/nordic/nrf54l20_enga_cpuapp.dtsi
nrf-squash! [nrf noup] entropy: Add fake entropy nRF PRNG driver
Change psa driver to nordic entropy. nRF54L20 needs it as well as nRF54H20.
=> [nrf noup] drivers: entropy: Switch entropy driver in nRF54L20

doc/connectivity/usb/device_next/usb_device.rst, doc/releases/migration-guide-4.0.rst, drivers/serial/serial_test.c, drivers/serial/uart_async_to_irq.c, drivers/serial/uart_emul.c, drivers/serial/uart_nrfx_uart.c, drivers/serial/uart_nrfx_uarte.c, drivers/usb/udc/udc_dwc2.c, include/zephyr/drivers/uart.h, subsys/usb/device/class/cdc_acm.c, subsys/usb/device_next/class/usbd_cdc_acm.c, subsys/usb/device_next/usbd_core.c
Fixes suspend current when connected to already suspended bus and prevents possible CDC ACM endless workqueue processing.
=> USB cherry picks for NCS 2.8.0

west.yml
Update the HW models module to:
eeed2591d38e5e9bf89658df67555f2777249fc0
eeed259 RADIO: Do not warn about TASK_RSSISTART during RXIDLE
565220e 54L15.mk: Fix flipper hal target name
bb8c6fd Makefile: Let's install libraries by default
6dbb843 RADIO: Implement immediate RSSI measurement when needed
3a5d567 RADIO: Allow triggering TASK_RSSISTART from register writes
Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
(cherry picked from commit fb010719ed5a1682bc946dd2153ef964b87ff2cc)
=> [nrf fromtree] manifest: Update nRF hw models to latest

drivers/usb/udc/Kconfig.dwc2, drivers/usb/udc/udc_dwc2_vendor_quirks.h, include/zephyr/drivers/usb/udc.h
Adds CONFIG_UDC_DWC2_USBHS_VBUS_READY_TIMEOUT_MS that allows for waiting for a USBHS VBUS ready event for a specified amount of time. Earlier it waited forever and because of that, the udc_enable() was blocked forever if the USB cable was disconnected. Now the function returns error on timeout.
Signed-off-by: Aleksander Strzebonski <aleksander.strzebonski@nordicsemi.no>
(cherry picked from commit 18fb3f9a329ade44495983206a5263f7aa2a84a4)
=> [nrf fromtree] usb: dwc2: Allow for enabling USB if the cable is disconnected

drivers/sensor/nordic/qdec_nrfx/qdec_nrfx.c, tests/boards/nrf/qdec/src/main.c
Fixed overflow handling in nrf QDEC sensor driver. It failed to inform user of an overflow in the ACC register, that caused the fetched sample to be invalid because of discarding data that would cause the overflow.
Now, `qdec_nrfx_sample_fetch()` returns error code if an overflow occured, based on overflow field in qdec data structure.
Also, driver is now more adjusted to sensor driver API. It is guaranteed that two subsequent calls of `sensor_channel_get()` function for the same channels will yield the same value, if `sensor_sample_fetch()` has not been called in the meantime.
=> [nrf fromtree] drivers: sensor: qdec: fix QDEC overflow handling

subsys/net/CMakeLists.txt
add `ALLOW_EMPTY TRUE` property to silence cmake warnings in case when no sources are added to subsys__net library
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79913
=> [nrf fromtree] net: silence no sources cmake warning

dts/common/nordic/nrf54l20.dtsi
Last 1k is used for saving VPR context and shall not be exposed. Limiting RAM to 511k.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79795
=> [nrf fromtree] dts: common: nordic: nrf54l20: Adjust RAM size to 511k

samples/boards/nordic/system_off/Kconfig, samples/boards/nordic/system_off/sample.yaml, samples/boards/nordic/system_off/src/main.c
Extend system_off sample to use GRTC timer as a wake up source.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79095
=> [nrf fromlist] samples: boards: nordic: system_off: Add GRTC wakeup

drivers/dp/swdp_bitbang.c, drivers/dp/swdp_ll_pin.h
pull upstream fixes for cmsis-dap library
to be used in connectivity bridge
=> Pull cmsis dap fixes

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_0_8_0.dtsi, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp_0_8_0.overlay, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuflpr_0_8_0.overlay, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuppr_0_8_0.overlay, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpurad_0_8_0.overlay, dts/bindings/arm/nordic,nrf-uicr-v2.yaml, dts/common/nordic/nrf54h20.dtsi, dts/common/nordic/nrf9280.dtsi
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79507
=> [nrf-fromlist] dts: update memory map and remove ext-uicr

drivers/pwm/pwm_nrfx.c, include/zephyr/pm/device.h, subsys/pm/device.c
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/78759
=> drivers: pwm: nrfx: Add runtime PM and fix stopping PWM

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuppr.dts, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpurad.dts, boards/nordic/nrf54l15dk/nrf54l15_cpuapp_common.dtsi, boards/nordic/nrf54l15dk/nrf54l15dk_nrf54l15_cpuflpr.dts, boards/nordic/nrf54l15pdk/nrf54l15_cpuapp_common.dtsi, boards/nordic/nrf54l15pdk/nrf54l15pdk_nrf54l15_cpuflpr.dts, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280_cpuapp.dts, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280_cpuppr.dts, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280_cpurad.dts
Like in all other legacy boards, hw-flow-control should not be enabled for console UART. With hw-flow-control sample stuck during printing some initial information and sample appears to be not working correctly unless com port is opened.
(cherry picked from commit 01f2740015fec36b1d9b000be95fd88ebb42edf0)
=> [nrf fromtree] boards: nordic: Do not enable hw-flow-control on console

samples/subsys/ipc/ipc_service/icmsg/sample.yaml
Change regex for no_multithreading test version for nRF54L15 platform. This needs to be changed because LOG is running in MINIMAL mode.
Signed-off-by: Jakub Zymelka <jakub.zymelka@nordicsemi.no>
(cherry picked from commit df201e4b4bc6b23d7d80b9b2298f4e6dfb87d47b)
=> [nrf fromtree] samples: icbmsg: Change regex for no_multithreading test

drivers/sensor/nordic/qdec_nrfx/qdec_nrfx.c, tests/boards/nrf/qdec/boards/nrf52840dk_nrf52840.overlay, tests/boards/nrf/qdec/boards/nrf5340dk_nrf5340_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54l15dk_nrf54l15_cpuflpr.overlay, tests/boards/nrf/qdec/boards/nrf54l15pdk_nrf54l15_common.dtsi, tests/boards/nrf/qdec/src/main.c, tests/boards/nrf/qdec/testcase.yaml
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/78660
=> drivers: sensor: nrf: qdec: Add device runtime power management

doc/services/ipc/ipc_service/backends/ipc_service_icmsg.rst
The details of how the ICMsg communication is done, are hidden inside the source code. This specification adds details about the ICMsg  protocol.
Upstream commit: https://github.com/zephyrproject-rtos/zephyr/commit/7574602108879a1d86c8361272ccff02456c8cda
=> [nrf fromtree] doc: ipc: Add detailed protocol specs for ICMsg

drivers/modem/modem_cellular.c
`+C*REG:` may be received as AT read command answer or unsolicited notification.
Their syntax differs, and even the overall parameter count varies depending on what `<n>` is used in the `AT+CEREG=` write command.
To handle all cases properly, check the parameter count and the presence of the `<tac>` parameter (which is a string and thus begins with `"`) to figure out what is the position of `<stat>`.
(cherry picked from commit 46366b9a4330b18d1eb0210d001532c75a215885)
Upstream PR #: 80512
=> [nrf fromlist] drivers: modem_cellular: fix handling of `+C*REG` answers

tests/drivers/i2s/i2s_api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/i2s/i2s_speed/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Add overlay to support nRF54L15 DK.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79930/
=> [nrf fromlist] tests: drivers: i2s: Add overlay to support nRF54L15 DK

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-ipc_conf.dtsi, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280-ipc_conf.dtsi, doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst, doc/services/ipc/ipc_service/backends/ipc_service_icmsg.rst, dts/bindings/ipc/zephyr,ipc-icmsg.yaml, samples/subsys/ipc/ipc_service/icmsg/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/subsys/ipc/ipc_service/icmsg/boards/nrf54l15dk_nrf54l15_cpuapp_icbmsg.overlay, samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf54l15dk_nrf54l15_cpuflpr.overlay, samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf54l15dk_nrf54l15_cpuflpr_icbmsg.overlay, subsys/ipc/ipc_service/backends/ipc_icbmsg.c
The nRF54 and nRF92 chips has data cache, which means the ICMsg and ICBMsg must be configured to follow required cache alignment of the shared memory.
The `dcache-alignement` needs to be defined for that.
Upstream commit: https://github.com/zephyrproject-rtos/zephyr/commit/cbaafe209c17f03feea3760be855dc76ef5612cc
=> [nrf fromtree] boards: nordic: ipc: added dcache alignement

modules/hal_nordic/nrfx/CMakeLists.txt, soc/nordic/Kconfig
To configure APPROTECT on nRF54L15 different set of MDK symbols must be used. Additionally, nRF54L15 does not support loading APPROTECT configuration from the UICR in runtime.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/80366
=> [nrf fromlist] soc: nordic: nrf54l15: fix APPROTECT handling

drivers/modem/modem_cellular.c
Backport c2097f6acea271ca69201de1c70f0f45bcbb5571 from #2176.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] drivers: modem_cellular: fix handling of `+C*REG` answers

tests/drivers/i2s/i2s_api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/i2s/i2s_speed/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Backport e6b24cbaf05dcbd9d5579751c86d8a2ef2a4d466 from #2141.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] tests: drivers: i2s: Add overlay to support nRF54L15 DK

modules/hal_nordic/nrfx/CMakeLists.txt, soc/nordic/Kconfig
Backport e49e65b4b052d6e1406c73add257fcbc377126db from #2162.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] soc: nordic: nrf54l15: fix APPROTECT handling

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-ipc_conf.dtsi, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280-ipc_conf.dtsi, doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst, doc/services/ipc/ipc_service/backends/ipc_service_icmsg.rst, dts/bindings/ipc/zephyr,ipc-icmsg.yaml, samples/subsys/ipc/ipc_service/icmsg/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, samples/subsys/ipc/ipc_service/icmsg/boards/nrf54l15dk_nrf54l15_cpuapp_icbmsg.overlay, samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf54l15dk_nrf54l15_cpuflpr.overlay, samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf54l15dk_nrf54l15_cpuflpr_icbmsg.overlay, subsys/ipc/ipc_service/backends/ipc_icbmsg.c
Backport 6c435d6d9b1ffa8782d38ddb338edac2447a502e from #2154.
=> [Backport v3.7.99-ncs1-branch] [nrf fromtree] boards: nordic: ipc: added dcache alignement

modules/hal_nordic/nrfx/CMakeLists.txt, soc/nordic/Kconfig
This reverts commit e49e65b4b052d6e1406c73add257fcbc377126db.
Revert the change until TFM is fixed.
=> Revert "[nrf fromlist] soc: nordic: nrf54l15: fix APPROTECT handling"

dts/common/nordic/nrf54l15.dtsi, samples/boards/nordic/nrf_sys_event/CMakeLists.txt, samples/boards/nordic/nrf_sys_event/prj.conf, samples/boards/nordic/nrf_sys_event/sample.yaml, samples/boards/nordic/nrf_sys_event/src/main.c, soc/nordic/common/CMakeLists.txt, soc/nordic/common/Kconfig, soc/nordic/common/nrf_sys_event.c, soc/nordic/common/nrf_sys_event.h
Backport 4c7f4d4219899a497853e432636a0344e064c0f4~3..4c7f4d4219899a497853e432636a0344e064c0f4 from #2177.
=> [Backport v3.7.99-ncs1-branch] Pull in sys nrf event

modules/hal_nordic/nrfx/CMakeLists.txt, soc/nordic/Kconfig
Backport c1dc2ca3cf756b007a87b6d30c5a240c0e013275 from #2193.
=> [Backport v3.7.99-ncs1-branch] Revert "[nrf fromlist] soc: nordic: nrf54l15: fix APPROTECT handling"

tests/drivers/can/api/src/canfd.c, tests/drivers/can/api/src/classic.c
Bring in additional CAN tests.
=> tests: drivers: can: api: Bring in new tests

samples/boards/nordic/system_off/README.rst
Update DK naming - NRF54L15PDK is deprecated.
Signed-off-by: Bartlomiej Buczek <bartlomiej.buczek@nordicsemi.no>i
(cherry picked from commit 8cd361a51a4e7954d58ca7f06ed554bd3a7ef076)
=> [nrf fromtree]: samples: boards: nordic: system_off: Update README.

samples/sensor/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Change pins that are used for qdec nrf54h20dk to align with shield
(loopbacks) used in internal CI. This change is needed to start
qdec driver power management testing.
Upstream PR: [80562](https://github.com/zephyrproject-rtos/zephyr/pull/80562)
=> [nrf fromlist] samples: sensor: qdec: change pins used for qdec nrf54h20dk

samples/boards/nordic/system_off/README.rst
Backport d9f282cee5327f69155171c2b02e7f26a4b76f47 from #2196.
=> [Backport v3.7.99-ncs1-branch] [nrf fromtree]: samples: boards: nordic: system_off: Update README.

soc/nordic/nrf54l/soc.c
DCDC regulator on nRF54L may not always works as intended. Apply a fix addressing that.
Upstream PR #: 80635
=> [nrf fromlist] soc: nordic: nrf54l: fix configuration of DCDC regulator

soc/nordic/nrf54l/soc.c
Backport d59b845455e7e4d1637ed994afabf95ea5af58f8 from #2201.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] soc: nordic: nrf54l: fix configuration of DCDC regulator

Kconfig.zephyr
LTO support was added with Zephyr 3.6.0, and it has been used in production with Nordic devices for a long time. Remove the experimental label to mark it ready for production.
(cherry picked from commit 2fd8cc8d881940f1c5b1c5499cc5384fc1a93c73)
=> [nrf fromtree] linker: lto: Remove experimental label

Kconfig.zephyr
Backport b6c23193700be7e7744bccf0c3aec159c1aaedfb from #2215.
=> [Backport v3.7.99-ncs1-branch] [nrf fromtree] linker: lto: Remove experimental label

arch/arm/core/cortex_m/pm_s2ram.S, arch/arm/core/cortex_m/pm_s2ram.c, include/zephyr/arch/common/pm_s2ram.h, soc/nordic/nrf54h/pm_s2ram.c
The S2RAM procedure requires marker checking after reset. Such checking is performed on very early stage of the system initialization and must ensure that the stack is not used due to the TLS pointer which is not initialized yet.
=> Nrfx 6553 fix tls handling for s2ram

drivers/wifi/nrfwifi/Kconfig.nrfwifi, drivers/wifi/nrfwifi/src/net_if.c, drivers/wifi/nrfwifi/src/qspi/src/spi_if.c, west.yml
* Crash in unprogrammed OTP board
* Remove noisy print
* Enable RPU recovery by default
=> wifi: Fixes from RC1 testing

soc/nordic/nrf54l/soc.c
Backport 9ee72ff9751e3ef0183c9f9e9896bd4b474fa350 from #2217.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] soc: nordic: nrf54l: tune configuration of DCDC regulator

drivers/timer/nrf_grtc_timer.c
Backport 822bd4f6d37746bc9b060e1d5d24327d4cf73ae1 from #2200.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] drivers: timer: grtc: Add LFPRC as the source of GRTC

drivers/pwm/pwm_nrfx.c, dts/common/nordic/nrf54h20.dtsi
Fast PWM120 instance works with 320MHz clock, thus `pwm_nrfx_get_cycles_per_sec` needs to be adjusted.
Also, it uses cachable RAM, thus sys_cache function needs to be added to flush the cached sequence.
Upstream PR : https://github.com/zephyrproject-rtos/zephyr/pull/80672
=> [nrf fromlist] drivers: pwm: nrfx: adjust PWM driver to fast PWM120

samples/sensor/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Backport 06d6b00c41b1ce0cd9e3ffc3d53958e4b5dc052b from #2192.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] samples: sensor: qdec: change pins used for qdec nrf54h20dk

drivers/pwm/pwm_nrfx.c, dts/common/nordic/nrf54h20.dtsi
Backport ada0489ebf78d4f1db1da831a6d886fb819346da~2..ada0489ebf78d4f1db1da831a6d886fb819346da from #2209.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] drivers: pwm: nrfx: adjust PWM driver to fast PWM120

drivers/wifi/nrfwifi/Kconfig.nrfwifi, west.yml
Backport 57dd05f7e713ec8c70a5820a7c289a37cc1eb9d9~2..57dd05f7e713ec8c70a5820a7c289a37cc1eb9d9 from #2235.
=> [Backport v3.7.99-ncs1-branch] wifi: nrf70: Fix EAP AKM

tests/drivers/gpio/gpio_basic_api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/sensor/temp_sensor/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Incorrectly removed during transfer pdk->dk.
=> Restore missing tests for nrf54l15

tests/drivers/gpio/gpio_basic_api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/sensor/temp_sensor/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Backport 1e549f5f6eb8ff6cf212af7fc2b5df7082a0d3c3~2..1e549f5f6eb8ff6cf212af7fc2b5df7082a0d3c3 from #2246.
=> [Backport v3.7.99-ncs1-branch] Restore missing tests for nrf54l15

drivers/wifi/nrfwifi/Kconfig.nrfwifi
Backport 5a391483191e8720b7556107337c8adf0ae655e0 from #2247.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] drivers: nrfwifi: Fix recovery for SAP

drivers/dp/swdp_bitbang.c
This patch fixes an issue where the reset pin is used even when it's not given.
(cherry picked from commit 4f85ce6eda93199946277d09bd5220b5eddd997e)
=> [nrf fromtree] dp: swdp_bitbang: fix missing reset pin error

modules/Kconfig.mcuboot, samples/subsys/mgmt/mcumgr/smp_svr/prj.conf, subsys/mgmt/mcumgr/grp/img_mgmt/include/mgmt/mcumgr/grp/img_mgmt/img_mgmt_priv.h, subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c, subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt_state.c
Backport c5efe1f601490fdb365fb17f28ec33d59409e54f~3..c5efe1f601490fdb365fb17f28ec33d59409e54f from #2257.
=> [Backport v3.7.99-ncs1-branch] Fix MCUmgr support for images hashed with sha512

drivers/spi/spi_nrfx_spim.c
Add pins retention control when GPD is enabled for SPIM.
Upstream PR #: 81134
=> [nrf_fromlist] drivers: spi: nrfx_spim: set/clear pins retention

drivers/spi/spi_dw.c
FAST_ACTIVE1 domain needs to be kept ON while the peripheral is active (always in this driver).
=> [nrf noup] drivers: spi: dw: turn on FAST_ACTIVE1 domain

drivers/spi/spi_nrfx_spim.c
Backport 87e5b3f36d215898b127ad25aadf56f0e3d162ed from #2249.
=> [Backport v3.7.99-ncs1-branch] [nrf_fromlist] drivers: spi: nrfx_spim: set/clear pins retention

drivers/pwm/pwm_nrfx.c
Backport b524b0e61990b415fe3b011611d031b28c29d279 from #2263.
=> [Backport v3.7.99-ncs1-branch] [nrf fromlist] drivers: pwm: nrfx: add pin retention

drivers/spi/spi_dw.c
Backport b9bc0846b926d339b042c4faa3c43c8276a37009 from #2261.
=> [Backport v3.7.99-ncs1-branch] [nrf noup] drivers: spi: dw: turn on FAST_ACTIVE1 domain

arch/arm/core/cortex_m/pm_s2ram.S, soc/nordic/nrf54h/pm_s2ram.c, soc/nordic/nrf54h/power.c
IRQs must be disabled before starting any procedures to prepare for low-power states.
=> soc: nordic: nrf54h: disable IRQ before PM config

arch/arm/core/cortex_m/pm_s2ram.S, soc/nordic/nrf54h/pm_s2ram.c, soc/nordic/nrf54h/power.c
Backport dab9c11bdcc80f1e0670ef686e6066ee3304ac47~2..dab9c11bdcc80f1e0670ef686e6066ee3304ac47 from #2258.
=> [Backport v3.7.99-ncs1-branch] soc: nordic: nrf54h: disable IRQ before PM config

cmake/modules/dts.cmake
Uses a temporary file when sysbuild is being used for images then uses CMake to copy to the correct file if it has changed. This prevents a ping-pong of configuring and building cycle when nothing has changed and there is sysbuild code which loads in the devicetree data from an image
Upstream PR #: 81340
=> cmake: dts: Use temporary file for dts.cmake with sysbuild

modules/openthread/platform/CMakeLists.txt, modules/openthread/platform/messagepool.c, modules/openthread/platform/openthread-core-zephyr-config.h, subsys/net/l2/openthread/Kconfig
* Add CONFIG_OPENTHREAD_PLATFORM_MESSAGE_MANAGEMENT to allow enabling message management by the platform.
* Add implementation of `otPlatMessagePoolInit`, `otPlatMessagePoolNew` and `otPlatMessagePoolFree`.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/80508
=> [nrf fromtree] net: openthread: Add platform message management

drivers/usb/udc/udc_dwc2.c, drivers/usb/udc/udc_nrf.c, subsys/usb/device_next/usbd_ch9.c
PR cherry-picks:
- an UDC nRF fix for FLASH erase interoperability issues
- a small USBD CH9 improvement
=> usb: device_next: Cherry-pick USB fixes

drivers/usb/common/nrf_usbd_common/nrf_usbd_common.c, drivers/usb/udc/udc_dwc2.c, drivers/usb/udc/udc_dwc2_vendor_quirks.h, drivers/usb/udc/udc_nrf.c, subsys/usb/device_next/class/usbd_uac2.c, subsys/usb/device_next/usbd_ch9.c
Prevent nRF52/nRF53 USBD DMA transfer in Low Power mode (because it won't work).
Fixes for UAC2 High-Speed support on nRF54H20.
=> Cherry-pick USB fixes for NCS 2.9.0

modules/hal_nordic/nrfx/CMakeLists.txt, soc/nordic/nrf54l/soc.c
Since nrfx 3.9 integration, configuration is executed in MDK SystemInit().
Additionally, add workaround for nRF54L anomaly 31.
Upstream PR #: 82268
Link: https://github.com/zephyrproject-rtos/zephyr/pull/82268
=> [nrf fromlist] soc: nordic: nrf54l: remove configuration of DCDC regulator

dts/common/nordic/nrf54l20.dtsi
Add missing nodes: i2c23, i2c24, spi23, spi24, uart23, uart24.
(cherry picked from commit d87bafea305900693b34ae60ac524b45491b69d0)
=> [nrf fromtree] dts: common: nordic: nrf54l20: Add missing nodes

CMakeLists.txt, Kconfig.zephyr, cmake/bintools/llvm/target_bintools.cmake
bintools improvement / gapfill
=> bintools improvement / gapfill

drivers/i2c/CMakeLists.txt, drivers/i2c/i2c_nrfx_twi_common.h, drivers/i2c/i2c_nrfx_twim.c, drivers/i2c/i2c_nrfx_twim_common.c, drivers/i2c/i2c_nrfx_twim_common.h, drivers/i2c/i2c_nrfx_twim_rtio.c, dts/arm/nordic/nrf52805.dtsi, dts/arm/nordic/nrf52810.dtsi, dts/arm/nordic/nrf52811.dtsi, dts/arm/nordic/nrf52820.dtsi, dts/arm/nordic/nrf52832.dtsi, dts/arm/nordic/nrf52833.dtsi, dts/arm/nordic/nrf52840.dtsi, dts/arm/nordic/nrf5340_cpuapp_peripherals.dtsi, dts/arm/nordic/nrf5340_cpunet.dtsi, dts/arm/nordic/nrf91_peripherals.dtsi, dts/common/nordic/nrf54h20.dtsi, dts/common/nordic/nrf54l15.dtsi, dts/common/nordic/nrf54l20.dtsi, dts/common/nordic/nrf9280.dtsi
Cherry-pick all changes required for I2C RTIO support.
=> I2C RTIO support

dts/bindings/arm/nordic,nrf-tddconf.yaml, snippets/nordic-log-stm-dict/boards/nrf54h20_cpuapp.overlay, snippets/nordic-log-stm/boards/nrf54h20_cpuapp.overlay
Introduce etrbuffer in the tddconf bindings to support flexible placement in the memory map.
=> [nrf fromtree] dts: bindings: arm: nordic: tddconf: Add etrbuffer

soc/nordic/Kconfig
APPROTECT symbols were already aligned to nRF54L15, but did not take into account similar SoCs like nRF54L05 or L10.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/82478
=> [nrf fromlist] soc: nordic: nrf54l: fix APPROTECT handling

drivers/wifi/nrf_wifi/Kconfig.nrfwifi, drivers/wifi/nrf_wifi/inc/fmac_main.h, drivers/wifi/nrf_wifi/src/net_if.c, drivers/wifi/nrf_wifi/src/wifi_util.c, west.yml
Add RPU recovery information in wifi utils.
=> Add RPU recovery info

subsys/bluetooth/mesh/adv.c, subsys/bluetooth/mesh/cfg_cli.c, subsys/bluetooth/mesh/gatt.h, subsys/bluetooth/mesh/net.c, subsys/bluetooth/mesh/pb_gatt_srv.c, subsys/bluetooth/mesh/proxy.h, subsys/bluetooth/mesh/proxy_msg.c, subsys/bluetooth/mesh/proxy_srv.c
=> Mesh 2.9 cherry picks

drivers/ieee802154/Kconfig, drivers/ieee802154/ieee802154_nrf5.c, include/zephyr/net/ieee802154_pkt.h, include/zephyr/net/ieee802154_radio.h, include/zephyr/net/ieee802154_radio_openthread.h, modules/hal_nordic/Kconfig, modules/openthread/Kconfig.features, modules/openthread/platform/diag.c, modules/openthread/platform/platform-zephyr.h, modules/openthread/platform/radio.c
Cherry-pick commits that introduce modcarrier command in openthread diags.
=> Mod carrier

drivers/audio/dmic_nrfx_pdm.c, dts/bindings/audio/nordic,nrf-pdm.yaml, dts/common/nordic/nrf54h20.dtsi
PDM driver can now be used on nRF54H20. It required an addition of DMM mechanism and minor changes to clock management,
nRF54H20 does not require clock control in case of PDM driver.
Currently, product specification for nRF54H20 PDM does not provide fully correct formula to calculate PDM clock frequency, thus master clock source frequency has to be passed as 8 MHz to ensure proper driver behavior. To be corrected and removed once correct formula is found.
=> [nrf fromlist] drivers: audio: dmic_nrfx: Add support for nRF54H20

drivers/wifi/nrf_wifi/src/wifi_mgmt_scan.c, west.yml
Backport 4092e6df311e18779fe1bb28ca29fff9e7931891~2..4092e6df311e18779fe1bb28ca29fff9e7931891 from #2341.
=> [Backport v3.7.99-ncs2-branch] wifi: Pull latest fixes

drivers/flash/soc_flash_nrf_rram.c
To read the secure memory we need to use soc_secure_mem_read function instead of memcpy.
This commit allows to use the soc_secure_mem_read function if the CONFIG_TRUSTED_EXECUTION_NONSECURE and PARTITION_MANAGER is enabled.
ref.: NCSDK-29300
=> [nrf noup] drivers: flash: Allow reading secure mem by nrf_rram.

scripts/west_commands/runners/__init__.py, scripts/west_commands/runners/blackmagicprobe.py, scripts/west_commands/runners/bossac.py, scripts/west_commands/runners/canopen_program.py, scripts/west_commands/runners/core.py, scripts/west_commands/runners/dfu.py, scripts/west_commands/runners/esp32.py, scripts/west_commands/runners/ezflashcli.py, scripts/west_commands/runners/intel_adsp.py, scripts/west_commands/runners/intel_cyclonev.py, scripts/west_commands/runners/jlink.py, scripts/west_commands/runners/linkserver.py, scripts/west_commands/runners/mdb.py, scripts/west_commands/runners/native.py, scripts/west_commands/runners/nios2.py, scripts/west_commands/runners/nrf_common.py, scripts/west_commands/runners/nrfutil.py, scripts/west_commands/runners/nsim.py, scripts/west_commands/runners/openocd.py, scripts/west_commands/runners/pyocd.py, scripts/west_commands/runners/renode-robot.py, scripts/west_commands/runners/renode.py, scripts/west_commands/runners/silabs_commander.py, scripts/west_commands/runners/spi_burn.py, scripts/west_commands/runners/stm32cubeprogrammer.py, scripts/west_commands/runners/stm32flash.py, scripts/west_commands/runners/teensy.py, scripts/west_commands/runners/uf2.py, scripts/west_commands/tests/test_canopen_program.py
Use sysbuild to build and configure SUIT Manifest Provisioning Information.
Ref: NCSDK-30461
=> suit: Move MPI to sysbuild Kconfig

subsys/dfu/boot/mcuboot.c
fixup! [nrf noup] dfu/boot/mcuboot: fix confirmation in case of USE_PARTITION_MANAGER
Fixes this code to correctly check which slot is active, albeit without firmware loader support
=> [nrf noup] dfu: boot: mcuboot: Fix selecting wrong active slot

drivers/flash/soc_flash_nrf_rram.c
Backport 711346aa377a65263784cd0d37efc9230e68229b from #2352.
=> [Backport v3.7.99-ncs2-branch] [nrf noup] drivers: flash: Allow reading secure mem by nrf_rram.

soc/nordic/common/poweroff.c
nRF54L05 and nRF54L10 devices that are emulated on nRF54L15 needs to have manually disabled remaining RAM blocks that are outside of their RAM region definitions.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/82262
=> [nrf fromlist] soc: nordic: poweroff: disable remaining RAM on emul l05/l10 targets

soc/nordic/nrf54l/soc.c
Noup as it patches code that does not exist in zephyr. arch_busy_wait and k_busy_wait waited half the expected time due to SystemCoreClock being set back to the default value when ns builds. Changed to rely on device tree as to avoid hardcoded clock frequencies
=> [nrf noup] soc: nordic: nrf54l Fix for wait lasting half expected time

subsys/dfu/boot/mcuboot.c
Backport d99f13efc7fe216de96ab072b353ffdbe3f96ae1 from #2252.
=> [Backport v3.7.99-ncs2-branch] [nrf noup] dfu: boot: mcuboot: Fix selecting wrong active slot

scripts/west_commands/runners/jlink.py, tests/drivers/spi/spi_controller_peripheral/boards/nrf52840dk_nrf52840.overlay
The commit 221199e15b85a070b3d81709eee3d533c9f99967 presents a bug that makes west flash failed with error.
AttributeError: 'NoneType' object has no attribute 'startswith'
In function is_tunnel(), tunnel may contain None and has no attribute "startswith". Fix it.
Signed-off-by: Phi Bang Nguyen <phibang.nguyen@nxp.com>
(cherry picked from commit 829c03bcdca378fa2fa55484d16a190d379f754c)
=> [nrf fromtree] runners: jlink: Fix NoneType object error

drivers/clock_control/clock_control_nrf2_common.c, drivers/spi/spi_nrfx_spim.c, dts/common/nordic/nrf54h20.dtsi
*drivers: clock_control_nrf2: Add missing cancelation of request*
This is a follow-up to commit https://github.com/zephyrproject-rtos/zephyr/commit/fe0e2dbc6044ffa74b27bfcba335980bc5a6ae64.
If `nrf_clock_control_request_sync()` ends up with a timeout, before returning it must cancel the request that was not fulfilled on time. Otherwise, the request may actually finish succesfully a bit later, but the caller will not be aware that the clock needs to be released (since the call resulted in an error).
*dts: nrf54h20: Add clocks property in fast SPIM nodes*
Fast SPIM instances in nRF54H20 (SPIM120 and SPIM121) are driven by the global HSFLL (HSFLL120). Add `clocks` property in these nodes to reflect this.
*drivers: spi_nrfx_spim: Add clock requests for fast SPIM instances*
Fast SPIM instances …
=> [nrf fromlist] drivers: spi_nrfx_spim: Add clock requests for fast SPIM instances

soc/nordic/common/poweroff.c
Backport 8798cb4caeedf0e78699cba48e4d3c7636d347a7 from #2360.
=> [Backport v3.7.99-ncs2-branch] [nrf fromlist] soc: nordic: poweroff: disable remaining RAM on emul l05/l10 targets

cmake/linker/lld/target.cmake
fixup! [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
=> [nrf noup] use -DUSE_PARTITION_MANAGER=1 for lld linker script template

boards/shields/nrf7002eb/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, drivers/wifi/nrf_wifi/Kconfig.nrfwifi, drivers/wifi/nrf_wifi/src/coex.c
Application core fails to boot if Wi-Fi is enabled due to unsupported GPIO.
=> nrf54H: wifi: Fix application core boot

modules/openthread/platform/diag.c
Commit adds `diag transmit` used for transmission IEEE802154 packets in specific amount and interval.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
(cherry picked from commit 1512ed2d3c6575ca3f1d0d62f8dab9966ae0b03d)
=> [nrf fromtree] net: openthread: Adding `diag transmit` command.

drivers/clock_control/clock_control_nrf2_hfxo.c, include/zephyr/drivers/clock_control/nrf_clock_control.h
Implement the zero latency interrupt safe APIs to the HFXO clock commonly used by the Bluetooth stack from zero latency interrupt context.
The PR brings changes done in upstream (+ one cleanup change that is in a PR).
=> nRF clock_control add ZLI API

dts/common/nordic/nrf9280.dtsi
Add definition of the SUIT storage partition for the nRF9280 SiP.
Signed-off-by: Tuomas Parttimaa <tuomas.parttimaa@nordicsemi.no>
(cherry picked from commit 342c25924d916b562a7a847fc97f842b5ce7dd4f)
=> [nrf fromtree] dts: nordic: Add SUIT storage partition for nRF9280 SiP

tests/drivers/uart/uart_async_api/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, tests/drivers/uart/uart_async_api/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/uart/uart_async_api/sysbuild/vpr_launcher/prj.conf
Add configuration for nrf54h20dk/nrf54h20/cpuppr.  https://github.com/zephyrproject-rtos/zephyr/pull/80550
Rework test to support multiple instances and add UARTE120 configuration https://github.com/zephyrproject-rtos/zephyr/pull/76061
=> [nrf fromtree] tests: drivers: uart: async_api: Add nrf54h20 cpuppr and UARTE120 test

include/zephyr/drivers/clock_control/nrf_clock_control.h
Some devices do not support nrf_clock HAL.
Upstream PR #: 83115 : https://github.com/zephyrproject-rtos/zephyr/pull/83115
=> [nrf fromlist] include: drivers: nrf_clock_control: make nrf_clock inclusion stricter

tests/drivers/uart/uart_async_api/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, tests/drivers/uart/uart_async_api/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/uart/uart_async_api/sysbuild/vpr_launcher/prj.conf
Backport 09b87e9262d6bc87206114dc14d1d10c585fbc0f from #2187.
=> [Backport v3.7.99-ncs3-branch] [nrf fromtree] tests: drivers: uart: async_api: Add nrf54h20 cpuppr and UARTE120 test

drivers/pwm/pwm_nrfx.c
Clock requesting in case of PWM120 needed fixes to control whether clock is requested when entering s2ram.
Upstream PRs : 
https://github.com/zephyrproject-rtos/zephyr/pull/82133
=> [nrf fromlist] drivers: pwm: fixes for fast PWM120

subsys/dfu/boot/mcuboot.c
Fix image confirmed for Direct XIP.
Signed-off-by: Fin Maaß <f.maass@vogl-electronic.com>
(cherry picked from commit e3f935650b976f098d19ff304344e83103ad0491)
=> [nrf fromtree] dfu: boot: mcuboot: fix boot_is_img_confirmed

drivers/pwm/pwm_nrfx.c
Backport 3098bb289f1050f5984e9fefdb1d12ea450234a4~2..3098bb289f1050f5984e9fefdb1d12ea450234a4 from #2415.
=> [Backport v3.7.99-ncs3-branch] [nrf fromlist] drivers: pwm: fixes for fast PWM120

drivers/watchdog/wdt_nrfx.c
In order to ensure that watchdog channels are freed in proper driver state, synchronization in form of semaphore needs to be added after stopping. In no irq variant, it is already done on nrfx level.
Signed-off-by: Michał Stasiak <michal.stasiak@nordicsemi.no>
(cherry picked from commit b578ffa49a13f58288e44af5f44a11a3f44b3d00)
=> [nrf fromtree] drivers: watchdog: nrfx: add synchronization after stop

drivers/misc/nordic_vpr_launcher/nordic_vpr_launcher.c, dts/common/nordic/nrf54h20.dtsi
Write-back cache after copying VPR's code and data to the destination memory. It allows VPRs to run from RAM regions cacheable by its host.
It allows to use FLPR in nRF54H20.
Upstream PR #: 84104
=> nrf54h20 flpr fixes

west.yml
Includes CRACEN model and compatibility with newest nrfx/mdk. See commits for details.
=> manifest: Update nRF hw models

subsys/net/l2/openthread/openthread.c
Some time ago three Kconfigs dedicated for the child timeouts configuration were added, but changing them does not apply when using OpenThread libraries. Added setting these values using openthread API on openthread start.
Upstream PR #: 84355
=> [nrf fromtree] net: Added configuring child timeouts on openthread start

boards/nordic/nrf54l15dk/nrf54l15dk_nrf54l15_cpuapp_ns.yaml
Enables forcing use of sysbuild to build nrf54l15dk non-secure board target when using twister
It fixes Twister nightly regression, can be tested with comamnd:
`$ZEPHYR_BASE/scripts/twister -vv -p nrf54l15dk/nrf54l15/cpuapp/ns -T $ZEPHYR_BASE/tests/subsys/mgmt/mcumgr`
Similar fix on Upstream: https://github.com/zephyrproject-rtos/zephyr/pull/82907
(however this board is only on NCS, why it is [nrf noap] commit)
=> [nrf noup] boards: Update non-secure target for nrf54l15

subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c
This fixes the compiler warning -Wstringop-truncation in version 13 of gcc.
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>
(cherry picked from commit 614f55f8bec29ca67a774eb568441ac099827eaa)
=> [nrf fromtree] ipc: ipc_service: Null terminate RPMsg endpoint names

drivers/usb/udc/udc_dwc2.c
Backport d0bef36f9bda4c30f58382d57413f01d8d55ba2f~7..d0bef36f9bda4c30f58382d57413f01d8d55ba2f from #2474.
=> [Backport v3.7.99-ncs3-branch] [nrf fromtree] drivers: udc_dwc2: Rework control endpoint feeding

modules/hal_nordic/Kconfig
Due to internal dependencies on other modules init priority the 802.15.4 priority level must be increased. Former init priority caused the module to be initialied before those it depends on, so that lead to hard faults.
The direct reason for this change is https://github.com/nrfconnect/sdk-nrf/pull/19498
Cherry-picked from https://github.com/zephyrproject-rtos/zephyr/pull/85527
=> modules: hal_norfic: rise 802.15.4 NET core init priority

tests/boards/nrf/comp/CMakeLists.txt, tests/boards/nrf/comp/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/boards/nrf/comp/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/boards/nrf/comp/prj.conf, tests/boards/nrf/comp/src/test.c, tests/boards/nrf/comp/testcase.yaml
Tests use nordic specific comparator api which enable it's runtime reconfiguration.
As there were no tests prepared when introducing this api, PR adds some to extend test coverage.
Signed-off-by: Bartlomiej Buczek <bartlomiej.buczek@nordicsemi.no>
(cherry picked from commit dc7c396a0b5e9b5a8a30bd60b29bdba059670041)
=> [nrf fromtree] tests: boards: nordic: add nrf comp tests.

lib/net_buf/buf.c
This warning is raised in many places when using bluetooth. However, it is not very useful for the user to see.
This is a noup PR as there is currently more changes coming in around this code and how to handle deadlocks in zephyr.
=> [nrf noup] lib: net_buf: buf: Revert alloc DBG to WRN change

cmake/modules/extensions.cmake, doc/kernel/code-relocation.rst, scripts/build/gen_relocate_app.py, tests/application_development/code_relocation/CMakeLists.txt, tests/application_development/code_relocation/src/test_file1.c, tests/application_development/code_relocation/src/test_file2.c
One might want to select the symbols to be relocated inside a file or
a library. To do this, one can use the FILTER argument of
zephyr_code_relocate which must contain a regular expression of the
section names to be selected for relocation.
The test_function_in_sram2 test case in
`tests/application_development/code_relocation` has been updated to
verify that only one function `function_in_sram()` is relocated to ram
and that the function `function_not_relocated()` is not being relocated
when using relocation filter.
Signed-off-by: Sylvain Chouleur <sylvain.chouleur@gmail.com>
(cherry picked from commit 4454734d127ad5519c2f8d72e002d5471add4d24)
=> [nrf fromtree] scripts: code_relocate: support section filter

samples/basic/blinky_pwm/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, samples/basic/blinky_pwm/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/basic/blinky_pwm/sysbuild/vpr_launcher/prj.conf, samples/basic/fade_led/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, samples/basic/fade_led/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/basic/fade_led/sysbuild/vpr_launcher/prj.conf, tests/drivers/pwm/pwm_api/boards/nrf54h20dk_nrf54h20_cpuppr.overlay, tests/drivers/pwm/pwm_api/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/pwm/pwm_api/sysbuild/vpr_launcher/prj.conf
Added overlays for nrf54h20_cpuppr to PWM samples and tests.
=> [nrf fromtree] tests: drivers: pwm: add support for nRF54H20 cpuppr PWM

cmake/reports/CMakeLists.txt
Adds support for prefixing files with the target of bl2 or tfm
Signed-off-by: Jamie McCrae <jamie.mccrae@nordicsemi.no>
(cherry picked from commit f80446973a3d2d83037e0413a09b62258649a617)
=> [nrf fromtree] cmake: reports: Add support for JSON prefix

dts/arm/nordic/nrf54l09_enga_cpuapp.dtsi
This adds temporary entropy driver simulation for
nRF54l09 device since final entropy source is not
available yet.
TODO: Remove this commit when proper solution will be available.
=> [nrf noup] entropy: Add fake entropy nRF PRNG driver

boards/native/nrf_bsim/nrf54l15bsim_nrf54l15_cpuapp.dts, tests/bsim/ci.uart.sh, tests/drivers/uart/uart_async_api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
Add the fast uart instance of 54l15 for testing
=> [nrf fromlist] tests: drivers: uart: add 54l15 fast uart

boards/nordic/nrf54l09pdk/nrf54l09_cpuapp_common.dtsi, dts/arm/nordic/nrf54l09_enga_cpuapp.dtsi, dts/common/nordic/nrf54l09.dtsi
The SDC HCI controller is defined as a device tree node. A node representing the SDC controller is added and selected as the default over the open source link layer. This is consistent with other SoCs.
=> [nrf noup] dts: Select SoftDevice Controller on nRF54L09

include/zephyr/net_buf.h, lib/net_buf/buf.c, subsys/bluetooth/mesh/Kconfig
Pulls a commit to revert disallowing blocking in syswq.
Pulls updates to the Mesh Kconfig BT_MESH_WORKQ_SYS as a result of this change.
=> Pull net buf revert

soc/nordic/nrf54l/Kconfig.defconfig.nrf54l20_enga_cpuapp
Change number of IRQ parameter for nRF54L20 devices.
Signed-off-by: Adam Kondraciuk <adam.kondraciuk@nordicsemi.no>
(cherry picked from commit 50c21f159143e18c8a05cbb946a5e7610033355f)
=> [nrf fromtree] soc: nordic: nrf54l: Fix num of irq for nRF54L20

soc/nordic/nrf54l/CMakeLists.txt
The linker script inclusion which places the KMU reserved buffer on the top of RAM doesn't work for non XIP builds. The Zephyr linker script will firstly load the code for an non XIP build in RAM and then include this KMU related linker script which results in an unpredictable placement of the KMU reserved area and a failed build.
In order to support non XIP builds the linker file is not included and the a DTS reserved-memory entry should be used.
To limit the scope, the DTS reserved memory region is currently only supported for non XIP builds.
This is a noup since the KMU is not supported upstream.
=> [nrf noup] soc: nrf54l: Non XIP KMU reserved memory fix

drivers/bluetooth/hci/Kconfig, drivers/bluetooth/hci/ipc.c
Add HCI IPC retry handling in case of full IPC
queue. This mechanism improves reliability.
The ipc_service_send can return -ENOMEM in case
of full queue. If this happens the retries are
executed in order to wait for queue to empty
and not drop messages.
If the retry mechanism reaches maximum then
the error code is passed back to the host.
The change should improve the handling of
passing messages to full ipc and reduce
dropping of packets.
Upstream PR #: 85649
=> [nrf fromlist] drivers: bluetooth: hci: Add retries for IPC interface

dts/common/nordic/nrf54l20.dtsi, modules/hal_nordic/Kconfig, modules/hal_nordic/nrf_802154/sl_opensource/platform/nrf_802154_clock_zephyr.c
Added functionality to enable the constant latency mode in the nrf_802154 driver, alongside the HFXO.
Added the missing power node to nRF54L20 to allow the NRFX_POWER Kconfig to be enabled.
=> modules: hal_nordic: nrf_802154: enable constant latency

cmake/reports/CMakeLists.txt
=> cmake: reports: Fix report targets

tests/drivers/mspi/api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
~Remove definition of dummy device since there is already external flash defined in SDP MSPI snippets.~
Changed to fix device frequency. Due to changes from https://github.com/nrfconnect/sdk-nrf/pull/20209 the device frequency now needs to be one of the specified.
=> [nrf noup] tests: drivers: mspi: api: nRF54L15 fix device frequency

drivers/adc/adc_nrfx_saadc.c, dts/arm/nordic/nrf52805.dtsi, dts/arm/nordic/nrf52810.dtsi, dts/arm/nordic/nrf52811.dtsi, dts/arm/nordic/nrf52832.dtsi, dts/arm/nordic/nrf52833.dtsi, dts/arm/nordic/nrf52840.dtsi, dts/arm/nordic/nrf5340_cpuapp_peripherals.dtsi, dts/arm/nordic/nrf91_peripherals.dtsi, dts/common/nordic/nrf54h20.dtsi, dts/common/nordic/nrf54l09.dtsi, dts/common/nordic/nrf54l20.dtsi, dts/common/nordic/nrf54l_05_10_15.dtsi, dts/common/nordic/nrf9280.dtsi
=> Cherry pick saadc pm device

soc/nordic/nrf54h/gpd/gpd.c
The main thread, if configured with coop priority (don't do that :D) breaks gpd since it has a non yielding while loop (also don't do that)
Add an explicit yield() to allow other threads to run if main or other threads use gpd with coop prio.
Upstream PR #: 84598
=> Cherry pick GPD yield() to not block if thread is coop

drivers/mbox/mbox_nrf_vevif_event_tx.c
Due to errata 16 VPR is triggering an event and immediately clears that event.
Pend until requested event is set before clearing it. Without that check event could be cleared too early and APP core is not waken up.
Upstream PR #: 86249
=> [nrf fromlist] drivers: mbox: nrf_vevif_event_tx: Fix errata 16 workaround

subsys/ipc/ipc_service/backends/Kconfig.icbmsg, subsys/ipc/ipc_service/backends/ipc_icbmsg.c, tests/arch/arm/arm_thread_swap/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
Fix failing arm/arch tests for nRF54H20
=> Ncsdk 31820 fix failing arch tests

tests/drivers/mspi/api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay
nrf-squash! [nrf noup] tests: drivers: mspi: api: Add nRF54L15 overlay file
Fix the test for nRF54L15 after changing definition of external flash in DTS.
=> [nrf noup] tests: drivers: mspi: api: fix for nRF54L15

subsys/bluetooth/host/att.c, subsys/bluetooth/host/l2cap.c
The buffer allocation in conn.c will trigger warnings if we try to use anything else than K_NO_WAIT for the timeout when called from within the system workqueue.
The calls in l2cap.c and att.c which may pass non-zero timeouts already have proper handling for failed allocations, so make sure we use K_NO_WAIT to avoid unnecessary warnings from conn.c.
Signed-off-by: Aleksandr Mirlenko <aleksandr.mirlenko@nordicsemi.no>
(cherry picked from commit 05b16b971bfad509206337a6ae22e8d7f5159ffd)
=> [nrf fromtree] Bluetooth: Host: Fix buffer allocation warnings in system workqueue

samples/bluetooth/hci_ipc/boards/nrf54h20dk_nrf54h20_cpurad.conf
A larger stack is needed to accomodate the Cracen driver.
=> [nrf noup] samples: bluetooth: hci_ipc: increase main stack size for Cracen driver on nRF54H20

include/zephyr/net/socket_ncs.h
* Removes leftover socket options `TLS_SESSION_CACHE_DISABLED`
and `TLS_SESSION_CACHE_ENABLED`. These exist already
in `socket.h`.
* Adds a base value for NCS specific socket options to
prevent overlaps with Zephyr's socket options.
=> Remove leftover socket options

drivers/clock_control/clock_control_nrf.c
=> Backport 2513 to v3.7.99 ncs2 branch

soc/nordic/nrf54l/Kconfig.defconfig.nrf54l09_enga_cpuapp
Change number of IRQ parameter for nRF54L09 devices.
Upstream PR #: 86350
=> [nrf fromlist] soc: nordic: nrf54l: Fix num of irq for nRF54L09

include/zephyr/arch/common/sys_bitops.h
When left-shifting '1' by 31, the result is undefined. This is something ASAN detects.
Solve this by explicitly defining that the integer is unsigned.
Upstream PR #: 86624
=> include: common: sys_bitops: Specify sign when bitshifting

drivers/flash/flash_mspi_nor.c, drivers/flash/spi_nor.h
drivers: flash: mspi_nor: support MODE_SINGLE and MODE_QUAD_1_4_4
=> [nrf fromlist] drivers: flash: mspi_nor: support MODE_SINGLE and MODE_QUAD_1_4_4

dts/common/nordic/nrf54l09.dtsi
Added clocks to GRTC node to allow GRTC output and access to frequency property.
Upstream PR #: 86701
=> [nrf fromlist] dts: nordic: nrf54l09: add clocks to GRTC

subsys/logging/frontends/log_frontend_stmesp.c
String location information should only be sent for core which do not append strings to the log message (PPR, FLPR). Without this, cpurad was also sending that information and that was redundant.
Upstream PR #: 86242
=> [nrf fromlist] logging: frontends: stmesp: Fix sending string location

boards/nordic/nrf54l20pdk/nrf54l20pdk_nrf54l20_cpuapp.yaml, samples/drivers/audio/dmic/boards/nrf54l20pdk_nrf54l20_cpuapp.overlay, tests/drivers/audio/dmic_api/boards/nrf54l20pdk_nrf54l20_cpuapp.overlay, tests/drivers/audio/dmic_api/src/main.c
Enable PDM tests on nRF54L20pdk.
=> [nrf fromtree] Run pdm tests on nrf54l20pdk

soc/nordic/nrf54h/pm_s2ram.c
For the Suspend to RAM procedures the SCB content
also needs to be retained.
=> [nrf fromlist] soc: nordic: nrf54h: Add SCB retention for s2ram

samples/subsys/mgmt/mcumgr/smp_svr/sample.yaml
Add proper configs to sample.yaml.
Ref: NCSDK-31608
=> [nrf noup] Fix smp_svr sample for external memory using PM

.github/workflows/commit-tags.yml, .github/workflows/compliance.yml, .github/workflows/license_check.yml, subsys/net/l2/ethernet/Kconfig, subsys/net/l2/ethernet/ethernet.c
The RFC1122 section 3.3.6 says we SHOULD drop the packets if L2 address is brodcast but L3 address is unicast, but we had seen some Wi-Fi access points in the field not conforming to that, and DHCP offer is dropped due to this and causes Wi-Fi connectivity issues.
As the RFC saus it's SHOULD and not a MUST, add a config option to allow such packets, disabled by default.
Signed-off-by: Chaitanya Tata <Chaitanya.Tata@nordicsemi.no>
(cherry picked from commit 4cd6654b2196bf00d62a528707e45c15db8b627d)
=> net: l2: Add a config option to allow mismatched L3/L2 address packets

drivers/regulator/regulator_npm1300.c, dts/bindings/regulator/nordic,npm1300-regulator.yaml
SW workaround for the nPM1300 anomaly 38
=> [nrf fromtree] nPM1300 LDO bug workaround

include/zephyr/net/socket_ncs.h
Reduces the NCS_BASE to a lower number to simplify
those use cases where certain applications would let
the user input the socket option name by number.
The base is still high enough to prevent collisions
with Zephyr's own socket options for many years.
=> [nrf noup] include: net: socket_ncs: reduce NCS_BASE

drivers/mfd/mfd_npm2100.c, drivers/regulator/regulator_npm2100.c, include/zephyr/drivers/mfd/npm2100.h
npm2100 driver fixes needed for NCS 3.0.0
=> Npm2100 cherrypicks

modules/hal_nordic/CMakeLists.txt
Added additional analog channels for ADC and COMP/LPCOMP and new pin functionality mapping for TDM.
=> Bump nrfregtool v8.1.3 ncs

subsys/shell/Kconfig
Set the default maximum argument count for the shell to 30 when the Wi-Fi shell is enabled, to ensure all Wi-Fi
commands work without failure.
=> [nrf fromtree] shell: Set default max argc count when WiFi shell is enabled

tests/drivers/i2s/i2s_speed/Kconfig, tests/drivers/i2s/i2s_speed/boards/nrf5340dk_nrf5340_cpuapp_aclk.overlay, tests/drivers/i2s/i2s_speed/src/test_i2s_speed.c, tests/drivers/i2s/i2s_speed/testcase.yaml
Change frame clock frequency to a global variable so it can be changed inside a test.
Add short transfer test at 16000, 32000, 44000, 44100, 48000 and 96000 frame clock frequency.
Add configuration for nrf5340dk where i2s peripheral is clocked from ACLK.
Upstream PR #: 85126
=> [nrf fromtree] tests: drivers: i2s: Add tests at typical audio sample rates

scripts/west_commands/runners/jlink.py
See https://nordicsemi.atlassian.net/browse/NCSIDB-1492
=> Jlink runner fixes

drivers/wifi/nrf_wifi/Kconfig.nrfwifi, drivers/wifi/nrf_wifi/src/fmac_main.c
Setting reorder buffer size to half of the RX buffers configured and  Disable mgmt buffer offload.
=> [nrf fromtree] drivers: wifi:  Disable mgmt buffer offload and Set reorder buffer size

.github/test-spec.yml
Sidewalk becomes NCS Add-on.
There is no need to trigger Sidewalk tests.
=> [nrf noup] ci: remove Sidewalk from test-spec

boards/nordic/nrf54l09pdk/nrf54l09pdk_nrf54l09-common.dtsi
P1.7 used for led 0 was not passing gpio_api_1pin test (probably shortened with another pin in the test setup. Use different pin that passes the gpio_api_1pin test. At current stage this PDK is 'virtual' so this pin is not attached to any LED and it can be changed.
(cherry picked from commit b298faa5e35e48dd6137f260946bc0eff1b1bbd4)
=> [nrf fromtree] boards: nordic: nrf54l09pdk: Change pin used for led0

doc/connectivity/bluetooth/api/gatt.rst, doc/releases/release-notes-4.2.rst, drivers/bluetooth/hci/hci_nxp.c, drivers/bluetooth/hci/ipc.c, include/zephyr/bluetooth/bluetooth.h, include/zephyr/bluetooth/gatt.h, include/zephyr/bluetooth/hci_types.h, subsys/bluetooth/Kconfig, subsys/bluetooth/Kconfig.adv, subsys/bluetooth/audio/bap_broadcast_assistant.c, subsys/bluetooth/host/adv.c, subsys/bluetooth/host/att.c, subsys/bluetooth/host/ecc.c, subsys/bluetooth/host/gatt.c, subsys/bluetooth/host/hci_core.c, subsys/bluetooth/host/hci_core.h, subsys/bluetooth/host/smp.c, tests/bsim/bluetooth/host/gatt/ccc_store/src/peripheral.c, tests/bsim/bluetooth/host/gatt/general/src/gatt_client_test.c, tests/bsim/bluetooth/host/security/ccc_update/src/peripheral.c
Cherry-pick Bluetooth Host commits
=> cherry-pick Bluetooth Host commits

drivers/flash/flash_mspi_nor.c
Pull in changes from upstream that switch to single lane when required, enable high performance bit when needed and use fast read in single.
=> drivers: flash: mspi_nor: initial config, high performance and fast read

.github/test-spec.yml
`CI-zigbee-test` not to be triggered anymore.
=> [nrf noup] ci: remove `CI-zigbee-test`

subsys/bluetooth/host/monitor.c
This fixes out of scope IRQ lock key by using SEGGER_RTT_Write version that locks the IRQ by itself.
Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>
(cherry picked from commit 27c18adf28a08de4fa04f1dde8afee6ce185dee3)
=> [nrf fromtree] Bluetooth: monitor: Fix SEGGER RTT compilation error

include/zephyr/bluetooth/cs.h, subsys/bluetooth/host/cs.c
added function to calculate antenna path
based on the antenna permutation index and
total number of antenna paths
Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
(cherry picked from commit ded9c1f44d4a537a77c0e46b77d99b1899977977)
=> [nrf fromtree] bluetooth: CS: add bt_le_cs_get_antenna_path()

doc/build/sysbuild/index.rst, scripts/west_commands/zcmake.py
Calling `west build --build-opt="-v" --build-opt="-j=<n>"`
passes the build options to `cmake --build ... -- <build-opt>` which
again is passed to the native build tool, such as ninja or make.
However, when ExternalProjects are used in CMake, such as in TF-M or
sysbuild builds then those extra build options are only passed to the
first image build and not those build as external projects.
CMake supports environment variables for those flags, so translate
verbosity and number of jobs to those environment variables and there
=> scripts: support number of jobs and verbosity in west build.

subsys/bluetooth/mesh/adv_ext.c, subsys/bluetooth/mesh/main.c, subsys/bluetooth/mesh/pb_adv.c, subsys/bluetooth/mesh/pb_gatt.c, subsys/bluetooth/mesh/prov_bearer.h, subsys/bluetooth/mesh/provisionee.c, subsys/bluetooth/mesh/proxy_srv.c, subsys/bluetooth/mesh/rpr_srv.c, subsys/bluetooth/mesh/settings.c, tests/bsim/bluetooth/mesh/src/test_provision.c, tests/bsim/bluetooth/mesh/tests_scripts/provision/pb_cancel.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/pb_remote_parallel.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/pb_remote_reprovision.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/pb_remote_timeout.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/prov_multi.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/prov_no_oob.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/prov_oob_auth_ib_pk.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/prov_oob_auth_ignore_oob_pk.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/prov_oob_auth_oob_pk.sh, tests/bsim/bluetooth/mesh/tests_scripts/provision/prov_reprovision.sh
This PR cherry-picks the following upstream mesh PRs:
- 87396
- 87428
- 87399
- 86927
- 87620
- 87691
=> Bluetooth: Mesh: Cherry pick BLE Mesh 27.03.2025

subsys/net/l2/wifi/wifi_utils.c
The check for index out of bound is missing, It turns into a crash for input channel more than WIFI_MGMT_SCAN_CHAN_MAX_MANUAL.
=> [nrf fromtree] wifi: utils: Fix crash for scan

drivers/adc/adc_nrfx_saadc.c, samples/drivers/adc/adc_sequence/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, samples/drivers/adc/adc_sequence/src/main.c
Add channel configuration build-time validation.
Demonstrate use of AIN8+ channel in `adc_sequence` sample.
=> drivers: saadc: Add support for nrf54h20 AIN8-14 pins

arch/arm/core/cortex_m/pm_s2ram.S, arch/arm/core/cortex_m/pm_s2ram.c, arch/arm/core/cortex_m/reset.S, arch/arm/core/cortex_m/swap_helper.S, include/zephyr/arch/common/pm_s2ram.h, soc/nordic/nrf54h/pm_s2ram.c
Restore pm s2ram procedures to C code form and use temporarily interrupt stack at the early stage.
=> Nrfx none revert s2ram procedures

soc/nordic/common/CMakeLists.txt, soc/nordic/common/Kconfig, soc/nordic/common/reboot.c
RAM power configuration is preserved through soft reset, meaning that there is a risk of accessing powered off RAM blocks when booting in different application (i.e. bootloader). Add option to force all RAM blocks to be powered on before triggering soft reset to prevent this from happening.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/87814
=> [nrf fromtree] soc: nordic: add option for forcing RAM power on reboot

soc/nordic/nrf54h/Kconfig.defconfig
nrf54h20 device requires device runtime PM to be enabled when device PM is in use.
Upstream PR #: 87807
=> [nrf fromlist] soc: nordic: nrf54h: Change PM_DEVICE_RUNTIME default

cmake/modules/zephyr_module.cmake
Upstream PR #: 87962
MODULE_EXT_ROOT allows Zephyr modules to provide glue code for Zephyr modules using `cmake-ext: True` and/or `kconfig-ext:True`.
A module ext root provides a `modules.cmake` file which defines variables like: `set(ZEPHYR_FOO_CMAKE_DIR  <glue-code-path>/foo)`
It is intended that a downstream module can replace Zephyr's default glue code, which again can be replaced further downstream.
Setting values in first modules.cmake (Zephyr's) are replaced by later processed modules.cmake (downstream) when the setting name is identical.
Therefore the module ext root list should not be reversed, and Zephyr itself should be placed as first entry in the list.
(cherry picked from commit …
=> [nrf fromlist] cmake: fix Zephyr module ext order

include/zephyr/bluetooth/conn.h, samples/bluetooth/channel_sounding/src/connected_cs_initiator.c, samples/bluetooth/channel_sounding/src/connected_cs_reflector.c, subsys/bluetooth/host/conn.c, subsys/bluetooth/host/conn_internal.h, subsys/bluetooth/host/cs.c, subsys/bluetooth/host/shell/bt.c, tests/bluetooth/host/cs/mocks/conn.c, tests/bluetooth/host/cs/mocks/conn.h
If the HCI status of a complete event is not BT_HCI_ERR_SUCCESS,
the remaining parameters could be invalid.
In this case, the params is passed as NULL pointer to the callbacks.
- LE CS Read Remote Supported Capabilities Complete event
- LE CS Read Remote FAE Table Complete event
- LE CS Config Complete event
- LE CS Security Enable Complete event
- LE CS Procedure Enable Complete event
This change avoids forwarding the invalid fileds to the applications.
=> [nrf fromtree] Cherry pick cs complete events with status

tests/drivers/spi/spi_controller_peripheral/boards/nrf54h20dk_nrf54h20_cpuapp_fast_spis.overlay
Both EXMIF and SPIS peripherals are claiming GPIO port 6 pin 0, but with different CTRLSEL values. This will trigger a build error with nrf-regtool 9.0.0 as it is not possible to apply this configuration to hardware.
Fix the issue by disabling the EXMIF node that is enabled by default.
Upstream PR#: 88017
=> [nrf fromlist] tests: spi_controller_peripheral: fix CTRLSEL conflict

drivers/audio/dmic_nrfx_pdm.c, dts/bindings/clock/nordic,nrf-aclk.yaml, dts/common/nordic/nrf54l20.dtsi
Allowed use of audio clock in DMIC PDM driver for nRF54L20. Added binding for audio clock node.
Upstream PR #: 87105
=> [nrf fromlist] drivers: audio: dmic_nrfx: allow use of ACLK for nRF54L20

.github/workflows/manifest-PR.yml
new arg base-branch defaults to main,
but can map zephyr release branch to nrf release base
Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>
=> [nrf noup] ci: enable custom base for `manifest-PR`

drivers/timer/nrf_grtc_timer.c, drivers/timer/nrf_rtc_timer.c, include/zephyr/sys_clock.h, kernel/nothread.c, kernel/sched.c, kernel/timeout.c, kernel/timer.c, tests/drivers/timer/nrf_grtc_timer/src/main.c
Cherry-picking from tree. Optimization in z_nrf_grtc_timer_get_ticks() and fix for failing GRTC test (on flpr).
=> [nrf fromtree] Fix nrfx_grtc test and optimize z_nrf_grtc_timer_get_ticks

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi
Due to compatibility reasons, we should either revert those or provide a clear and tested way to migrate between the v2.9.0-nRF54H20-1 and v3.0.0.
=> NCSDK-32650: Revert incompatible memory changes

drivers/usb/udc/udc_ambiq.c, drivers/usb/udc/udc_common.c, drivers/usb/udc/udc_common.h, drivers/usb/udc/udc_dwc2.c, drivers/usb/udc/udc_it82xx2.c, drivers/usb/udc/udc_kinetis.c, drivers/usb/udc/udc_mcux_ehci.c, drivers/usb/udc/udc_mcux_ip3511.c, drivers/usb/udc/udc_nrf.c, drivers/usb/udc/udc_numaker.c, drivers/usb/udc/udc_renesas_ra.c, drivers/usb/udc/udc_rpi_pico.c, drivers/usb/udc/udc_skeleton.c, drivers/usb/udc/udc_smartbond.c, drivers/usb/udc/udc_stm32.c, drivers/usb/udc/udc_virtual.c
This solves not working enumeration on nRF54H20 on subsequent cable connection when cable was disconnected while device was hibernated.
=> [nrf fromlist] drivers: udc_dwc2: Mark endpoint idle on disable while hibernated

subsys/net/l2/openthread/openthread.c
Upstream PR #: 88166
Some OpenThread functions were called without verifying the return value, which not only is not the best practice, but also could lead to build warnings with llvm. This commit fixes it.
=> [nrf fromlist] net: openthread: Add missing error checks

drivers/clock_control/Kconfig.nrf, drivers/clock_control/clock_control_nrf.c
Backport b2e0b7a37f74dcbd625a58cd4778e1933c245f8d from #2705.
=> [Backport v4.0.99-ncs1-branch] [nrf fromlist] drivers: clock_control: nrf: Apply fix for nRF54L anomaly 30.

drivers/usb/udc/udc_ambiq.c, drivers/usb/udc/udc_common.c, drivers/usb/udc/udc_common.h, drivers/usb/udc/udc_dwc2.c, drivers/usb/udc/udc_it82xx2.c, drivers/usb/udc/udc_kinetis.c, drivers/usb/udc/udc_mcux_ehci.c, drivers/usb/udc/udc_mcux_ip3511.c, drivers/usb/udc/udc_nrf.c, drivers/usb/udc/udc_numaker.c, drivers/usb/udc/udc_renesas_ra.c, drivers/usb/udc/udc_rpi_pico.c, drivers/usb/udc/udc_skeleton.c, drivers/usb/udc/udc_smartbond.c, drivers/usb/udc/udc_stm32.c, drivers/usb/udc/udc_virtual.c
Backport 7a28ef1dc00aeeae17034631b79cdc0d52a13c6b~2..7a28ef1dc00aeeae17034631b79cdc0d52a13c6b from #2717.
=> [Backport v4.0.99-ncs1-branch] [nrf fromlist] drivers: udc_dwc2: Mark endpoint idle on disable while hibernated

subsys/net/l2/openthread/openthread.c
Backport 06c6605ca152de466718b0cb3f73ae7bba17e6ff from #2718.
=> [Backport v4.0.99-ncs1-branch] [nrf fromlist] net: openthread: Add missing error checks

subsys/bluetooth/mesh/access.c, tests/bsim/bluetooth/mesh/src/test_cdp1.c
Commit fixes bug when corresponding group ID was never incremented for independent corresponding relationships.
(cherry picked from commit 69c5c6f40ea01946bc419067fc1577d74ae3e5f4)
=> [nrf fromtree] Bluetooth: Mesh: make corresponding group ID unique

subsys/bluetooth/mesh/access.c, tests/bsim/bluetooth/mesh/src/test_cdp1.c
Backport eacfed3332af6f473c97b6888594ea9d74e0149f from #2715.
=> [Backport v4.0.99-ncs1-branch] [nrf fromtree] Bluetooth: Mesh: make corresponding group ID unique

modules/openthread/platform/radio.c, subsys/net/l2/openthread/openthread_utils.c
Pull more fixes for OT clang builds from upstream
=> [nrf fromlist] net: openthread: Fix ignored return values in OT utils 

modules/openthread/platform/radio.c, subsys/net/l2/openthread/openthread_utils.c
Backport 8e6457ef04460a53081477ff1094176e518eba09~2..8e6457ef04460a53081477ff1094176e518eba09 from #2738.
=> [Backport v4.0.99-ncs1-branch] [nrf fromlist] net: openthread: Fix ignored return values in OT utils 

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280_cpuapp.dts, drivers/flash/flash_mspi_nor.c, drivers/flash/flash_mspi_nor.h, drivers/flash/flash_mspi_nor_quirks.h, drivers/flash/spi_nor.h
Backport 80ef7970f0d1fdf506a3b1b644849a92a46f7c6f~4..80ef7970f0d1fdf506a3b1b644849a92a46f7c6f from #2701.
=> [Backport v4.0.99-ncs1-branch] drivers: flash: mspi_nor: update

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi
Due to compatibility reasons, we should either revert those or provide a clear and tested way to migrate between the v2.9.0-nRF54H20-1 and v3.0.0.
=> [Backport v3.0-branch] NCSDK-32650: Revert incompatible memory changes

subsys/bluetooth/mesh/proxy_srv.c, tests/bluetooth/tester/src/btp/btp_mesh.h, tests/bluetooth/tester/src/btp_mesh.c
backport from https://github.com/nrfconnect/sdk-zephyr/pull/2704
=> [Backport v4.0.99-ncs1-branch] Mesh pts test bug fix for pnid

subsys/net/lib/zperf/zperf_shell.c
Declaration of variables after a label inside a switch statement is a c23 extension, not c99.
This results in the following warning when compiling with clang:
> .../subsys/net/lib/zperf/zperf_shell.c:912:4: warning: label followed
>                by a declaration is a C23 extension [-Wc23-extensions]
>   912 |                      int seconds = parse_arg(&i, argc, argv);
>       |                         ^
> .../subsys/net/lib/zperf/zperf_shell.c:1145:4: warning: label followed
>                by a declaration is a C23 extension [-Wc23-extensions]
>  1145 |                      int seconds = parse_arg(&i, argc, argv);
>       |                         ^
> 2 warnings generated.
There are no practical reasons why the variable should be declared inside the switch statement, therefore move …
=> [nrf fromlist] zperf: moving declaration of variable to top of function

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp_iron.dts
Support IPC between SEC and APP. This is needed for PSA Crypto support.
This patch is expected to be removed within a couple of weeks by the ongoing work in NCSDK-32158.
Upstream PR #: 88285
=> [nrf fromlist] boards: 54h20: Support IPC between SEC and APP

dts/common/nordic/nrf54h20.dtsi, soc/nordic/nrf54h/pm_s2ram.c, soc/nordic/nrf54h/power.c, soc/nordic/nrf54h/power.h
By moving cache enabling earlier wake up time is reduced from 180us to 33us.
=> Reduce restore time when waking up from s2ram on nrf54h20

subsys/mgmt/mcumgr/CMakeLists.txt, subsys/mgmt/mcumgr/Kconfig, subsys/mgmt/mcumgr/bootutil_hooks/nrf53_hooks.c, subsys/mgmt/mcumgr/grp/img_mgmt/Kconfig
Fixes an issue whereby just enabling hooks would enable the nrf5340 network core hook despite lacking other requirements
=> [nrf noup] mgmt: mcumgr: Fix nRF5340 network core hook

drivers/clock_control/clock_control_nrf.c
Adding support for handling XOTUNE event in clock_control. Right now XOTUNE event reflects situation when HFCLK is stable and tuned.
Signed-off-by: Karol Lasończyk <karol.lasonczyk@nordicsemi.no>
(cherry picked from commit 9a052d8366222f6029608ce5bf81f097a6ce0f1b)
=> [nrf fromlist] drivers: clock_control: Add support for XOTUNE in nRF54L

drivers/wifi/nrf_wifi/Kconfig.nrfwifi
This was not getting enabled because label was passed instead of path and dependency was not met.
Fix the DT function to use label.
Upstream PR #: 88306
=> [nrf fromlist] drivers: nrf_wifi: Fix SR co-ex RF switch configuration

subsys/net/lib/zperf/zperf_shell.c
Backport 25e27e349f6f3873e9b0d48573eccbf73dbab2fb from #2741.
=> [Backport v4.0.99-ncs1-branch] [nrf fromlist] zperf: moving declaration of variable to top of function

modules/hal_nordic/CMakeLists.txt
Upstream PR #: 88055
Added support for VPR GPIOs and a more concise output print.
=> modules: hal_nordic: bump regtool to 9.0.1

drivers/flash/flash_mspi_nor.c, drivers/flash/flash_mspi_nor.h, drivers/flash/flash_mspi_nor_quirks.h
Backport c9a539dac2900d053e57d80c6f381f1b6e46dbd6 from #2745.
=> [Backport v4.0.99-ncs1-branch] drivers: flash: Optimize mspi_nor driver memory

drivers/wifi/nrf_wifi/Kconfig.nrfwifi
Backport b4d256022e3be724062cc5f55fbfde259875395a from #2732.
=> [Backport v4.0.99-ncs1-branch] [nrf fromlist] drivers: nrf_wifi: Fix SR co-ex RF switch configuration

drivers/wifi/nrf_wifi/src/net_if.c, subsys/net/ip/net_pkt.c, tests/net/vlan/testcase.yaml
Backport 81eaa466f86919803d7a1e12f26f214a49e61fb1~3..81eaa466f86919803d7a1e12f26f214a49e61fb1 from #2759.
=> [Backport v4.0.99-ncs1-branch] nrf70: Fix zero copy

modules/nrf_wifi/bus/spi_if.c
In order to support higher frequencies than 8MHz, we need to implement frequency switching while waking up the RPU, as it has to be done only at 8MHz, once RPU is awake, we can switch back to the configured (DTS) frequency.
Signed-off-by: Chaitanya Tata <Chaitanya.Tata@nordicsemi.no>
(cherry picked from commit 4818585006d3ab231d842dbda1eb614a4639cadc)
=> [nrf fromtree] modules: nrf_wifi: spi: Implement frequency switching

drivers/spi/spi_nrfx_spis.c
ISR safe runtime PM can only be used for all instances except for spis120 which requires standard runtime PM.
Added compilation guard against using CONFIG_PM_DEVICE_SYSTEM_MANAGED with spis120.
Upstream PR #: 88428
=> [nrf fromlist] drivers: spi: nrfx_spis: Fix spis120

drivers/pinctrl/pinctrl_nrf.c, include/zephyr/dt-bindings/pinctrl/nrf-pinctrl.h, samples/basic/blinky/boards/nrf54l15dk_nrf54l15_cpuapp_hpf_gpio.overlay
Backport a4c0f9551c0cb9abc58fb555ca3eb9c677f75edb~2..a4c0f9551c0cb9abc58fb555ca3eb9c677f75edb from #2729.
=> [Backport v4.0.99-ncs1-branch] Nrfx 7252 rename to hpf

.github/workflows/manifest-PR.yml
[nrf noup] ci: enable custom base for `manifest-PR`
new arg base-branch defaults to main,
but can map zephyr release branch to nrf release branch
Signed-off-by: Thomas Stilwell <thomas.stilwell@nordicsemi.no>
=> [nrf noup] ci: enable custom base for manifest-PR

soc/nordic/nrf54h/pm_s2ram.c
Cache was not enabled when s2ram did not completed which lead to system malfunction. Always power up cache when returning from s2ram function.
Upstream PR #: 88709
=> [nrf fromlist] soc: nordic: nrf54h: Fix s2ram

drivers/usb/udc/udc_common.c, drivers/usb/udc/udc_dwc2.c, subsys/usb/device_next/usbd_ch9.c
PR88642 is backported to apply on 2.9.0-nRF54H20 sdk-zephyr without requiring to pull in other changes.
=> nRF54H20 USB cherry-picks for 2.9.0-nRF54H20-2

soc/nordic/soc.yml
Backport 37e76921f9fecbd6a43e98ae82428b40590460ac from #2774.
=> [Backport v4.0.99-ncs1-branch] soc: nordic: Add missing flash runner config

tests/drivers/clock_control/nrf_clock_calibration/src/test_nrf_clock_calibration.c
This change plays with situation in nRF54L devices where XOTUNE make LF clock calibration process starts a bit longer. Now HF clock is configured to be ready right before LF calibration test.
Upstream PR #: 88797
=> [nrf fromlist] tests: drivers: Turn on HFCLK before LFCLK calibration in nRF devices

drivers/audio/dmic_nrfx_pdm.c
Pull latest version of PDM driver.
=> Pull latest version of the PDM driver

drivers/wifi/nrf_wifi/CMakeLists.txt, drivers/wifi/nrf_wifi/Kconfig.nrfwifi, drivers/wifi/nrf_wifi/src/fmac_main.c, drivers/wifi/nrf_wifi/src/fw_load.c, drivers/wifi/nrf_wifi/src/net_if.c, modules/nrf_wifi/bus/CMakeLists.txt, modules/nrf_wifi/bus/Kconfig, modules/nrf_wifi/bus/device.c, modules/nrf_wifi/bus/ipc_if.c, modules/nrf_wifi/bus/ipc_if.h, modules/nrf_wifi/bus/ipc_service.c, modules/nrf_wifi/bus/ipc_service.h, modules/nrf_wifi/bus/spsc_qm.c, modules/nrf_wifi/bus/spsc_qm.h, modules/nrf_wifi/os/CMakeLists.txt, modules/nrf_wifi/os/shim.c, west.yml
Pulls in preliminary nRF71 (upcoming SoC) support.
=> nrf_wifi: Add nRF71 support

modules/hal_nordic/CMakeLists.txt
Upstream PR #: 88898
Changes for this package version:
* CTRLSEL is now set appropriately for the SPIS121 pins.
* DPPI.LINK configuration is now skipped when processing
the 'dppic130' devicetree node.
=> bump regtool to 9.1.0

samples/boards/nordic/system_off/sample.yaml, samples/boards/nordic/system_off/src/main.c
For reasons other than system off, the retained data should be cleared.
Upstream PR #: 89044
=> [nrf fromlist] samples: boards: nordic: system_off fixes

modules/hostap/Kconfig
SoftAP operation needs around 5700 bytes of stack. With a buffer of 100 bytes, set the supplicant stack size to 5800. Fixes SHEL-3604.
Upstream PR #: 89116
=> [nrf_fromlist] modules: hostap: Increase supplicant stack size

samples/subsys/mgmt/mcumgr/smp_svr/boards/nrf54h20dk_nrf54h20_cpuapp_iron.conf, soc/nordic/nrf54h/gpd/Kconfig
Disable GPD for MCUBoot build, as it cannot be reinitialized later in application (SDFW does not
support reinitialization).
Also, remove the GPD disabling from the mcumgr sample for nRF54H20 iron board app - it was the reinitialization that caused problems.
Upstream PR #: 88958
Signed-off-by: Michal Kozikowski <michal.kozikowski@nordicsemi.no>
(cherry picked from commit bece1c22bbf04d417839635e482ecc9e45bd5c15)
=> soc: nordic: nrf54h: Disable GPD for MCUBoot

drivers/usb/udc/udc_dwc2_vendor_quirks.h
Initial implementation of nRF54L quirks necessary for nRF54L20.
=> [nrf noup] drivers: udc_dwc2: Add nRF54L quirks

include/zephyr/drivers/clock_control/nrf_clock_control.h
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/88164
=> [nrf fromtree] include: drivers: clock_control: Remove strict inclusion for nrf_clock.h

dts/bindings/net/wireless/nordic,nrf21540-fem.yaml
The tx-en-settle-time-us is set to 26 to take into account the time needed for the RF output power rise time of the nRF5 SoC.
Upstream PR #: 89465
Ref: KRKNWK-20212
=> [nrf fromlist] bindings: nrf21540: set default tx-en-settle-time-us to 26

west.yml
Updated MDK improves support for nRF54L05 and nRF54L10 erratas. As NCS 2.9.x uses legacy nrfx 3.9 version, changes had to be introduced via sdk-hal_nordic repository.
=> [nrf noup] manifest: Update hal_nordic with MDK 8.68.2 release

west.yml
Update hal_nordic with errata workaround in nrfx_spim.
Upstream PR #: 89489
=> [nrf fromlist] manifest: Update hal_nordic with SPI workaround

scripts/ci/check_compliance.py
~~Not to be merged until after upmerge is completed~~
Will allow the sysbuild CI checks to be enabled
=> [nrf noup] scripts: ci: check_compliance: Add NCS sysbuild Kconfigs

.github/test-spec.yml
Neither NFC nor FindMy use Bluetooth Mesh, but CI is triggered and may fail.
FindMy excludes Bluetooth Mesh in sdk-nrf: https://github.com/nrfconnect/sdk-nrf/blob/3bda0a8675b1a51e30539bb2491cd0758877229c/.github/test-spec.yml#L430-L431
NFC doesn't include all `subsys/bluetooth` in sdk-nrf.
=> [nrf noup] ci: exclude mesh from find-my and nfc

arch/Kconfig, arch/arm/core/cortex_m/coredump.c, doc/releases/release-notes-4.2.rst, kernel/include/kernel_arch_interface.h, lib/hash/hash_func32_murmur3.c, modules/lvgl/Kconfig, modules/lvgl/lvgl_display_mono.c, subsys/debug/coredump/Kconfig, subsys/debug/coredump/coredump_core.c
[nrf fromtree] lib: hash: murmur3: Account for unaligned 32-bit access
The code was casting a byte array to 32-bit words without accounting for
alignment. On some platforms (e.g. Arm Cortex-M with multiple load/store
instructions) this will fault. Fix it by using the UNALIGED_GET() macro
whenever the array is passed unaligned.
[nrf fromtree] debug: coredump: support dumping stack top only
Add Kconfig option to dump only a portion of stack from the
current stack pointer to the stack end. This is enough to
let gdb reconstruct the stack trace and can significantly
reduce the dump size. This is crucial if the core dump needs
to be sent over radio.
Additionally, add another option to set the limit for the
dumped stack portion.
---
Also, add one random change from Zephyr to make the merge …
=> Cherry-pick two fromtree commits needed by protocols serialization

drivers/clock_control/clock_control_nrf2_common.c, drivers/clock_control/clock_control_nrf2_common.h, drivers/clock_control/clock_control_nrf2_fll16m.c, drivers/clock_control/clock_control_nrf2_global_hsfll.c, drivers/clock_control/clock_control_nrf2_hsfll.c, drivers/clock_control/clock_control_nrf2_lfclk.c, tests/drivers/clock_control/nrf_clock_control/src/main.c
Cherry-picking of commits from https://github.com/zephyrproject-rtos/zephyr/pull/89952.
Ref. NCSDK-33603
=> [nrf fromlist] drivers: clock_control_nrf2_common: Add resetting of the on-off services

boards/nordic/nrf7002dk/nrf5340_cpuapp_common_pinctrl.dtsi, boards/shields/nrf7002ek/boards/nrf5340dk_nrf5340_cpuapp.overlay
Put the GPIOs in low-power state when not in use.
=> wiif: Pull IOVDD current improvements

cmake/linker/ld/target.cmake
Original implementation of `toolchain_linker_finalize` duplicates the `LINK_FLAGS` in the link command. This can cause some problems like duplicate definitions when using link options like `--whole-archive`.
This commit fixes it by removing the duplicate `LINK_FLAGS`.
Fixes #82281
(cherry picked from commit 841311330b03d01c4b224b7031a21c6350390206)
=> [nrf fromtree] cmake: linker: ld: fix duplicate LINK_FLAGS

boards/nordic/nrf7002dk/nrf5340_cpuapp_common_pinctrl.dtsi, boards/shields/nrf7002ek/boards/nrf5340dk_nrf5340_cpuapp.overlay
Put the GPIOs in low-power state when not in use.
=> Pull iovdd fixes 30

soc/nordic/common/dmm.c
sys_heap alloc and free are not thread safe so lock is needed to prevent data corruption.
Upstream PR #: 90280
=> [nrf fromlist] soc: nordic: dmm: Add lock around sys_heap operations

tests/drivers/gpio/gpio_hogs/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/gpio/gpio_hogs/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/gpio/gpio_hogs/testcase.yaml
Add overlays and entries in testcase.yaml to enable tests execution on nrf54 DKs.
(cherry picked from commit 5406259c477d657f8a62a86a4c1a1ec1a6ba560b)
=> [nrf fromtree] tests: drivers: gpio_hogs: Add nrf54 platforms.

boards/nordic/nrf21540dk/nrf21540dk_nrf52840.dts, boards/nordic/nrf52833dk/nrf52833dk_nrf52833.dts, boards/nordic/nrf52840dk/nrf52840dk_nrf52840.dts, boards/nordic/nrf52dk/nrf52dk_nrf52832.dts, boards/nordic/nrf5340_audio_dk/nrf5340_audio_dk_nrf5340_cpuapp_common.dtsi, boards/nordic/nrf5340dk/nrf5340_cpuapp_common.dtsi, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, boards/nordic/nrf54l15dk/nrf54l_05_10_15_cpuapp_common.dtsi, boards/nordic/nrf54l20pdk/nrf54l20_cpuapp_common.dtsi, boards/nordic/nrf7002dk/nrf5340_cpuapp_common.dtsi, boards/nordic/thingy52/thingy52_nrf52832.dts, boards/nordic/thingy53/thingy53_nrf5340_common.dtsi
Enable NFCT device in dts of the boards that have
NFC connector.
This is part of NCSDK-32456, since it didn't make it before upmerge.
(cherry picked from commit e37b68bfa4b62b7fc19c29eeec6521fd56e6cd30)
=> [nrf fromtree] boards: nordic: Enable nfct on the supporting boards

drivers/serial/Kconfig.nrfx, soc/nordic/common/Kconfig.peripherals
Extends configuration to support instances used in new SOCs.
Upstream PR #: 90373
=> [nrf fromlist] soc: drivers: nrf: Add support for UARTE23 and UARTE24

west.yml
Add request to enable/disable dPlus pullup.
Upstream PR #: 88429
=> [nrf fromlist] modules: hal_nordic: nrfs: update manifest

share/sysbuild/cmake/modules/sysbuild_extensions.cmake
Allow to add an image-specific DTS overlay, that is applied based on the `FILE_SUFFIX`.
Up to this point, it was possible to specify such Kconfig files (`sysbuild/<image>_<file_suffix>.conf`), but it did not work with dts overlays (`sysbuild/<image>_<file_suffix>.overlay`).
This commit aligns the logic of finding configuration files for both scenarios mentioned above.
=> Allow to add suffix overlays

tests/drivers/clock_control/clock_control_api/testcase.yaml
CONF_FILE parameter in testcase.yaml overwrites board specific configurations. Change it to EXTRA_CONF_FILE to apply both configurations.
Upstream PR #: 90869
=> [nrf fromlist] test: drivers: clock_control_api: Fix conf file application

drivers/adc/adc_nrfx_saadc.c, west.yml
New nrfx release contains MDK 8.71.1 and various fixes for nRF devices.
Upstream PR #: 90944
Link: https://github.com/zephyrproject-rtos/zephyr/pull/90944
=> [nrf fromlist] update hal_nordic revision to integrate nrfx 3.12.0

share/sysbuild/cmake/modules/sysbuild_extensions.cmake
Fix the incorrect syntax in the cmake foreach directive.
Upstream PR #: 90643
=> [nrf fromtree] sysbuild: Allow to use file suffix DTS overlays

tests/kernel/timer/cycle64/testcase.yaml
For GRTC timer a longer timeout is required:
(2 ^ 32) * 2 * 1us
=> [nrf fromtree] tests: kernel: timer: cycle64: Add support for GRTC

drivers/adc/adc_nrfx_saadc.c
Current target-reference mapping does not cover all cases.
Upstream PR #: 91581
=> [nrf fromlist] drivers: adc: adc_nrfx_saadc: Extend internal reference values

west.yml
Errata 55 applies to nRF54LV10A Eng A as well.
Upstream PR #: 91682
Link: https://github.com/zephyrproject-rtos/zephyr/pull/91682
=> [nrf fromlist] manifest: update hal_nordic for errata 55 on nRF54LV10A Eng A

drivers/cache/cache_nrf.c
Upstream zephyr: https://github.com/zephyrproject-rtos/zephyr/pull/90682
Add new function called _cache_all_check that cache all if NRF_CACHE has no LINEADDR.
=> [nrf fromtree] drivers: cache: nrf: Resolve NRF_CACHE_HAS_LINEADDR issue

drivers/clock_control/clock_control_nrf2_fll16m.c, drivers/clock_control/clock_control_nrf2_global_hsfll.c, drivers/clock_control/clock_control_nrf2_hfxo.c, drivers/clock_control/clock_control_nrf2_hsfll.c, drivers/clock_control/clock_control_nrf2_lfclk.c, dts/bindings/clock/nordic,nrf-fll16m.yaml, dts/bindings/clock/nordic,nrf-lfclk.yaml, dts/vendor/nordic/nrf54h20.dtsi, include/zephyr/drivers/clock_control/nrf_clock_control.h, samples/boards/nordic/clock_control/src/main.c
Clock control cherry pick new resolve and get_startup_time APIs
=> Clock control cherry pick new resolve and get_startup_time APIs

dts/bindings/usb/zephyr,hid-device.yaml, samples/subsys/usb/hid-keyboard/app.overlay, samples/subsys/usb/hid-keyboard/large_in_report.overlay, samples/subsys/usb/hid-mouse/usbd_next.overlay, subsys/usb/device/class/bluetooth.c, subsys/usb/device_next/class/bt_hci.c, subsys/usb/device_next/class/usbd_hid.c, subsys/usb/device_next/usbd_ch9.c, subsys/usb/device_next/usbd_device.c
=> usb: fixes for USB device support

subsys/bluetooth/host/cs.c
There was a change in HCI fuffers encoding: #88710. First byte in the HCI buf->data[0] is HCI type.
The header starts from buf->data[1].
Current implementation was overwriting the opcode field in the buffer when updating the hdr->param_len.
=> [nrf noup] bluetooth: host: cs: Fix bt_le_cs_start_test param_len update

drivers/gpio/gpio_nrfx.c
Fix an issue where calling gpio_pin_interrupt_configure with edge mode and later calling it with level mode, did not release the allocated gpiote channel.
Repeating the above sequence caused us to run out of gpiote channels.
(cherry picked from commit 581f75656d01f37aec6280326a1924d7d80f2d30)
=> [nrf fromtree] drivers: gpio_nrfx: Free channel when changing mode

include/zephyr/bluetooth/bluetooth.h, subsys/bluetooth/host/Kconfig, subsys/bluetooth/host/adv.c, subsys/bluetooth/host/adv.h, subsys/bluetooth/host/hci_core.h, subsys/bluetooth/host/id.c, subsys/bluetooth/host/id.h, subsys/bluetooth/host/keys.c, subsys/bluetooth/host/keys.h, subsys/bluetooth/host/smp.c
This PR adds a feature to allow bonding with the same Central using multiple identities.
The PR consists of 2 commits.
The first commit adds a new Kconfig option by enabling which Host will keep
bonding with the same Central instead of rejecting pairing.
Brief implementation details:
This implementation adds a new flag to bt_keys struct:
BT_KEYS_ID_CONFLICT. The flag is set, when:
- bonding with the same peer and conflict identified
- when loading conflicting keys from persistent storage.
When bonding and conflict is identified, the new keys aren't added to
the Resolving List immediately. Instead, the old keys stay in the
Resolving List.
When start advertising, Host finds conflicting keys that are already
added to the Resolving List and substitues them.
If, however, there is another …
=> Bluetooth: Host: Bonding with the same Central using multiple identities

drivers/firmware/nrf_ironside/dvfs.c
Until register ABB->STATUSANA is visible it must be checked using defined offset to base ABB register.
Upstream PR #:92313
=> [nrf fromlist] drivers: nrf_ironside: dvfs abb analog status workaround

boards/nordic/nrf54h20dk/support/nrf54h20_cpuapp.JLinkScript, drivers/firmware/nrf_ironside/CMakeLists.txt, drivers/firmware/nrf_ironside/Kconfig, drivers/firmware/nrf_ironside/tdd.c, include/zephyr/drivers/firmware/nrf_ironside/tdd.h, soc/nordic/nrf54h/Kconfig, soc/nordic/nrf54h/soc.c
Added support for the IronSide TDD service which allows configuring and
powering the trace and debug domain of the nrf54h20.
Also provide option to start the trace and debug domain in the soc start
sequence.
=> ironside tdd service

drivers/gpio/gpio_nrfx.c, drivers/i2c/i2c_nrfx_twim.c, drivers/i2c/i2c_nrfx_twim_common.c, drivers/i2c/i2c_nrfx_twim_common.h, drivers/i2c/i2c_nrfx_twim_rtio.c, drivers/i2c/i2c_nrfx_twis.c, drivers/pinctrl/pinctrl_nrf.c, drivers/spi/spi_nrfx_spim.c, include/zephyr/drivers/i2c.h, include/zephyr/drivers/spi.h, tests/drivers/i2c/i2c_target_api/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/i2c/i2c_target_api/src/main.c, tests/drivers/spi/spi_loopback/boards/nrf54h20dk_nrf54h20_common.dtsi, tests/drivers/spi/spi_loopback/src/spi.c
=> Device deinit driver support

scripts/pylib/twister/twisterlib/runner.py, scripts/tests/twister/test_runner.py
If test plan is used, memory usage metrics are overridden. Result of this operation is missing memory footprint.
This change removes redundand metrics update and fixes described inconvenience.
(cherry picked from commit bec789d364bf24d5b1a6604bc1d6cd37c06cecf3)
=> [nrf fromtree] twister: Enable gathering footprint if test plan exists

boards/seeed/xiao_ble/pm_static.yml
The xiao_ble boards ship with a bootloader requiring an app offset of 0x27000. 
The upstream board defines this via DT partitions, which will not be used if partition manager is enabled.
Add a static partition configuration to allow binaries built for this board to work out-of-the-box in NCS, and match the behavior with sysbuild disabled.
The partitions match https://github.com/nrfconnect/sdk-zephyr/blob/main/dts/vendor/nordic/nrf52840_partition_uf2_sdv7.dtsi which is included by https://github.com/nrfconnect/sdk-zephyr/blob/main/boards/seeed/xiao_ble/xiao_ble_common.dtsi#L9
=> [nrf noup] boards: xiao_ble: Add static partition manager configuration

scripts/ci/check_compliance.py
nrf-squash! [nrf noup] ci: set `ZEPHYR_<MODULE_NAME>_KCONFIG` for NCS modules
Adds a static path for the NRF Kconfig variable in the check compliance script, this is a temporary workaround due to supporting an external root for NCS that should be reworked to use package helper in future
=> [nrf noup] ci: Add static entry for NRF Kconfig path

drivers/pwm/Kconfig.nrfx, drivers/pwm/pwm_nrfx.c, dts/bindings/pwm/nordic,nrf-pwm.yaml, dts/vendor/nordic/nrf54h20.dtsi, dts/vendor/nordic/nrf54l20.dtsi, dts/vendor/nordic/nrf54l_05_10_15.dtsi, dts/vendor/nordic/nrf9280.dtsi
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/90781
=>  [nrf fromtree] drivers: pwm: nrfx: Add option to glitch free 100% duty cycle

drivers/spi/spi_nrfx_spim.c, tests/drivers/spi/spi_controller_peripheral/boards/1m333333hz.overlay, tests/drivers/spi/spi_controller_peripheral/boards/2m666666hz.overlay, tests/drivers/spi/spi_controller_peripheral/testcase.yaml
Disabled spim frequency approximation algorithm when device has prescaler
=> [nrf fromlist] Spim custom frequencies downstream

subsys/settings/src/settings.c, subsys/settings/src/settings_init.c, subsys/settings/src/settings_priv.h, subsys/settings/src/settings_store.c
Allows usage of settings when multithreading is disabled
Upstream PR #: 92886
=> [nrf fromlist] settings: Only use mutexes when multithreading is enabled

boards/nordic/nrf54l15dk/nrf54l_05_10_15_cpuapp_common.dtsi
Adds aliases so that these devices can use MCUboot serial recovery
Upstream PR #: 93090
=> [nrf fromlist] boards: nordic: nrf54l15dk: Add button/LED aliases

drivers/timer/nrf_grtc_timer.c
This is a followup to #2740 which was causing a failure of `kernel/timer/timer_behavior` test where timeout that was set with 0 ticks was not expiring.
=> [nrf fromlist] drivers: timer: nrf_grtc: Fix for optimization

drivers/serial/uart_nrfx_uarte.c, drivers/spi/spi_nrfx_spim.c, drivers/spi/spi_nrfx_spis.c, dts/bindings/serial/nordic,nrf-uarte.yaml, dts/bindings/spi/nordic,nrf-spi-common.yaml, dts/vendor/nordic/nrf54l_05_10_15.dtsi, tests/drivers/spi/spi_controller_peripheral/boards/nrf54l15dk_nrf54l15_cpuapp_cross_domain.overlay, tests/drivers/spi/spi_controller_peripheral/testcase.yaml, tests/drivers/uart/uart_elementary/boards/nrf54l15dk_nrf54l15_cpuapp_cross_domain.overlay, tests/drivers/uart/uart_elementary/testcase.yaml
UARTE20, UARTE21, SPI(M/S)20 and SPIM(M/S)21 instances enable usage of pins on different port, but require request for constant latency mode. Added handling of such scenario in the driver. Added testcases to cover it.
=> [nrf fromlist] drivers: nrfx: enable cross domain pins for nRF54L15

drivers/serial/Kconfig.nrfx, drivers/serial/Kconfig.nrfx_uart_instance, drivers/serial/uart_nrfx_uarte.c, dts/bindings/serial/nordic,nrf-uarte.yaml, tests/drivers/uart/uart_async_api/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/uart/uart_async_dual/Kconfig, tests/drivers/uart/uart_async_dual/boards/nrf54h20dk_nrf54h20_common.dtsi, tests/drivers/uart/uart_async_dual/boards/nrf54l15dk_nrf54l15_cpuapp.overlay, tests/drivers/uart/uart_async_dual/src/main.c, tests/drivers/uart/uart_async_dual/sysbuild/vpr_launcher/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/uart/uart_async_dual/testcase.yaml
=> [nrf fromlist] drivers: serial: nrfx_uarte: Add mode with TIMER byte counting

drivers/spi/spi_nrfx_spim.c, drivers/spi/spi_nrfx_spis.c, tests/drivers/spi/spi_controller_peripheral/Kconfig, tests/drivers/spi/spi_controller_peripheral/src/main.c, tests/drivers/spi/spi_controller_peripheral/testcase.yaml
Some nRF SoCs (i.e. nRF54H20) can peform DMA transfers only from specific memory regions - dmm facilitates that.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/93487
=> [nrf fromlist] drivers: spi: nrfx_spim: use dmm

drivers/modem/hl7800.c, drivers/wifi/esp_at/esp.c, include/zephyr/net/dns_resolve.h, subsys/net/ip/Kconfig.stack, subsys/net/ip/ipv6_nbr.c, subsys/net/l2/ppp/ipcp.c, subsys/net/lib/dhcpv4/Kconfig, subsys/net/lib/dhcpv4/dhcpv4.c, subsys/net/lib/dhcpv6/Kconfig, subsys/net/lib/dhcpv6/dhcpv6.c, subsys/net/lib/dns/Kconfig, subsys/net/lib/dns/resolve.c, subsys/net/lib/shell/conn.c, subsys/net/lib/shell/dns.c, tests/net/lib/dns_addremove/src/main.c, tests/net/lib/dns_addremove/testcase.yaml, tests/net/lib/dns_dispatcher/src/main.c, tests/net/lib/dns_dispatcher/testcase.yaml
A set of commits improving handling of DNS addresses assigned via DHCP in multi-interface environment.
=> net: Cherry-pick DHCP/DNS improvements

drivers/mspi/mspi_dw.c
In Single IO mode, where the clock stretching feature is not available, the RX FIFO could get overflowed if the TX FIFO was filled with more dummy bytes than the RX FIFO could receive data items at a given moment. Such problem could be quite easy hit on nRF54H20, for example for longer RX transfers (like 8 kB) at 8 MHz.
This commit limits accordingly the number of dummy bytes that can be enqueued in the TX FIFO.
Upstream PR #: 93777
=> [nrf fromtree] drivers: mspi_dw: Prevent RX FIFO overflows in Single IO mode

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280_cpuapp.dts, drivers/flash/flash_mspi_nor.c, drivers/flash/flash_mspi_nor.h, drivers/flash/flash_mspi_nor_quirks.h, drivers/flash/flash_mspi_nor_sfdp.h, dts/bindings/mtd/jedec,jesd216.yaml, dts/bindings/mtd/jedec,mspi-nor.yaml
Cherry-pick commits from https://github.com/zephyrproject-rtos/zephyr/pull/93093.
=> [nrf fromlist] drivers: flash_mspi_nor: Apply a few improvements

include/zephyr/bluetooth/hci_types.h, subsys/bluetooth/host/hci_core.c
Bluetooth 6.1 has version number 0x0F and was released in May 2025. This commit ensures this version number is properly decoded.
Going forward we may consider removing printing the version number as a string because the feature set is more important than the version number.
(cherry picked from commit b63b993491633e699567ff0d71a3465ecfb9fa50)
=> [nrf fromtree] Bluetooth: Decode Bluetooth 6.1 version number

samples/boards/nordic/spis_wakeup/boards/nrf54h20dk_nrf54h20_cpuapp.conf
Explicit start radio core.
Upstream PR #: 93966
=> [nrf fromlist] samples: boards: nordic: spis_wakeup: fix boot for h20

cmake/mcuboot.cmake, modules/Kconfig.mcuboot
Update signing script to use proper arguments for imgtool when SHA512 or pure signature is needed.
Upstream PR #: 93813
=> [nrf fromlist] cmake: mcuboot: SHA512/pure image signing

drivers/hwinfo/hwinfo_nrf.c, samples/boards/nordic/system_off/src/main.c
Added missing supported reset reasons based on conditional guards.
=> [nrf fromlist] drivers: hwinfo: nrf: extend supported reset reasons

tests/boards/nrf/qdec/boards/bl54l15_dvk_nrf54l15_common.dtsi, tests/boards/nrf/qdec/boards/bl54l15u_dvk_nrf54l15_common.dtsi, tests/boards/nrf/qdec/boards/nrf52840dk_nrf52840.overlay, tests/boards/nrf/qdec/boards/nrf5340dk_nrf5340_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/boards/nrf/qdec/boards/nrf54l15dk_nrf54l15_common.dtsi, tests/boards/nrf/qdec/boards/nrf54lm20dk_nrf54lm20_common.dtsi, tests/boards/nrf/qdec/dts/bindings/test-qdec-loopback.yaml, tests/boards/nrf/qdec/src/main.c
Add testing of multiple QDEC instsances in tests/boards/nrf/qdec test.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/93927
=> tests: boards: nrf: qdec: Add testing with multiple QDEC instances

drivers/adc/adc_nrfx_saadc.c
Add support for DMM which manages cache and dedicated memory spaces.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/90751
=> [nrf fromlist] drivers: adc: nrfx_saadc: Add support for DMM

include/zephyr/bluetooth/gatt.h, include/zephyr/bluetooth/l2cap.h, subsys/bluetooth/host/gatt.c, subsys/bluetooth/host/l2cap.c, subsys/bluetooth/host/l2cap_internal.h, subsys/bluetooth/host/smp.c, tests/bsim/bluetooth/host/l2cap/many_conns/src/main.c
Pulls various bugfixes for 3.1
=> BLE Host cherry pick for 3.1

.github/workflows/manifest-PR.yml
new arg base-branch defaults to main,
but can map zephyr release branch to nrf release base
Signed-off-by: Sebastian Wezel <sebastian.wezel@nordicsemi.no>
=> [nrf noup] ci: enable custom brase for manifest-PR

drivers/timer/Kconfig.nrf_rtc, drivers/timer/nrf_rtc_timer.c, include/zephyr/drivers/timer/nrf_rtc_timer.h, tests/drivers/counter/counter_nrf_rtc/fixed_top/boards/nrf52dk_nrf52832.overlay, tests/drivers/counter/counter_nrf_rtc/fixed_top/testcase.yaml, tests/drivers/timer/nrf_rtc_timer/src/main.c
Allowed use of counter bit width lower than hardware 24. In that case, PPI connection is established to trigger clear task once maximum value is reached.
=> [nrf fromlist] drivers: timer: nrf_rtc_timer: Allow use of custom bit width

include/zephyr/bluetooth/l2cap.h, subsys/bluetooth/host/l2cap.c
L2CAP channels will now, along with the ident, store the opcode of the pending request. This commit expands the ident lookup function to also compare received response types to this opcode, and will ignore unsolicited responses.
Setting of idents for channels are moved after verification of buffer allocation for the request to be sent. A TODO is added for improving this functionality at a later time.
Upstream PR #: 94080
=> [nrf fromlist] Bluetooth: Host: Add req/rsp l2cap validation

drivers/adc/adc_nrfx_saadc.c
The SAMPLERATE register can be used as a local timer instead
of triggering individual SAMPLE tasks. When SAMPLERATE.MODE is set
to Timers, it is sufficient to trigger SAMPLE task only once in order
to start the SAADC and triggering the STOP task will stop sampling.
The SAMPLERATE.CC field controls the sample rate.
The SAMPLERATE timer should not be combined with SCAN mode and
only one channel should be enabled when using the internal timer.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/91368
=> drivers: adc: nrfx_saadc: Add support for SAADC internal sampling timer

arch/arm/core/cortex_m/pm_s2ram.c, boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, subsys/pm/Kconfig
Upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/93818
ref. NCSIDB-1657
=> [nrf fromtree] Optional context memeory section section for suspend to RAM CPU context.

drivers/adc/adc_nrfx_saadc.c, include/zephyr/dt-bindings/adc/nrf-saadc.h
Backport https://github.com/nrfconnect/sdk-zephyr/commit/05746fdc63754ddf8eee3ce25485760dbcb86df4 from #3094.
Backport https://github.com/nrfconnect/sdk-zephyr/commit/77547f89162265a6a4a285175b8e60b1dac7ae04 from #3095.
Backport https://github.com/nrfconnect/sdk-zephyr/commit/84ab620777ceec9b286f3fe6640ed0869c682c0b from #3147.
These commits are related, so they need to be merged together.
=> [Backport ncs-v3.1-branch] Backport commits from #3094 and #3095.

drivers/timer/nrf_rtc_timer.c
Use channel 0 for RTC wrapping. Skip that channel when processing channels.
Fix algorithm that prevents setting CC=0 when custom wrapping is used.
Upstream PR #: 94259
=> [nrf fromlist] drivers: timer: nrf_rtc: Fix custom wrapping

soc/nordic/nrf54l/CMakeLists.txt
nrf-squash! [nrf noup] soc: nrf54l: Add custom section for KMU
Change how the KMU reserved area is included in the linker file. Now there is a separate Kconfig which shows it the there is a dts entry for the KMU
reserved area.
=> soc: nrf54l: Change logic for KMU reserved area

tests/crypto/mbedtls_psa/boards/nrf54l05dk_nrf54l05_cpuapp.conf, tests/crypto/mbedtls_psa/boards/nrf54l15dk_nrf54l10_cpuapp.conf, tests/crypto/mbedtls_psa/boards/nrf54l15dk_nrf54l15_cpuapp.conf, tests/crypto/mbedtls_psa/boards/nrf54lm20dk_nrf54lm20a_cpuapp.conf, tests/crypto/mbedtls_psa/boards/nrf54lv10dk_nrf54lv10a_cpuapp.conf
Add ENTROPY_GENERATOR=y in overlays for l series devices. This fixes an error where a trng source is not included in ncs.
I attempted to fix this without an ugly noup here: https://github.com/nrfconnect/sdk-nrf/commit/8479106bf17e1fdcd06c1d8af8e92a7ec87be9ce, but this causes regressions in `benchmarks.current_consumption.systemoff.grtc_wakeup` and `tests/drivers/uart/uart_mix_fifo_poll/drivers.uart.uart_mix_poll_fifo`. The issue here is with the mismatch between how zephyr handles including the rng and how it is handled in NCS. In NCS the assumption is made that when required it is enabled explicitly, while in zephyr it is implicitly enabled  as long as it exists in the device tree. In the L series the assumption is also made that rng will not be called inside an interrupt as it owns and …
=> [nrf noup] tests: crypto: Add ENTROPY_GENERATOR in overlays

drivers/adc/adc_nrfx_saadc.c, include/zephyr/dt-bindings/adc/nrf-saadc.h
Rollback of obsolete commits and replacing them with correct ones already merged in upstream.
=> drivers: adc: nrfx: synchronize upstream changes

soc/nordic/nrf54h/Kconfig, soc/nordic/nrf54h/soc.c
The upcoming release of IronSide SE no longer disables RETAIN
in all GPIO instances on boot, so the application must be able
to handle the hardware default state of RETAIN being enabled.
The GPIO retention is properly handled by changes that are
currently only upstream and will be pulled in by the next upmerge.
This patch exists a workaround to be able to integrate
IronSide SE before the proper solution is pulled in.
=> [nrf noup] soc: nrf54h: work around missing power domain handling

tests/drivers/timer/nrf_grtc_timer/src/main.c
If test is to be run in coverage mode, wait for output to dump at the end of a failing testcase.
Upstream PR #: 95162
=> [nrf fromlist] tests: drivers: timer: nrf_grtc_timer: wait for coverage dump

doc/_extensions/zephyr/kconfig/__init__.py
Allows listing sysbuild Kconfigs for boards and SoCs
=> [nrf noup] doc: extensions: kconfig: Add SoC sysbuild Kconfigs

drivers/i2s/i2s_nrf_tdm.c
TDM should have clock divider bypass enabled when calculated clock divider exceeds maximum allowed value which is `CKDIV2`.
Upstream PR #: 95166
=> [nrf fromtree] drivers: i2s: nrf_tdm: Allow using 8 channels

boards/ezurio/bl54l15_dvk/bl54l15_dvk_nrf54l10_cpuapp_ns.dts, boards/ezurio/bl54l15_dvk/bl54l15_dvk_nrf54l10_cpuapp_ns.yaml, boards/nordic/nrf54l15dk/nrf54l15dk_nrf54l10_cpuapp_ns.dts, boards/nordic/nrf54l15dk/nrf54l15dk_nrf54l10_cpuapp_ns.yaml
Fixed incorrect size of the n54l10 ns board.
=> boards: Fix nRF54L10 size for the non secure target

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, soc/nordic/nrf54h/CMakeLists.txt, soc/nordic/nrf54h/Kconfig, soc/nordic/nrf54h/pm_s2ram.c, soc/nordic/nrf54h/pm_s2ram.h
Added infrastructure needed for redirect execution to the Application reset vector in case SoC gets woke-up from S2RAM and MCUboot is the first code entity. Thanks to that bootloader can implement its own routine for resume support (CONFIG_SOC_NRF54H20_PM_S2RAM_OVERRIDE) which overrides `zephyr/soc/nordic/nrf54h/pm_s2ram.c` implementation in case of MCUboot.
Introduce additional source of true using additional check over independent source (variable with magic value).
=> nRF54h20 pm s2ram resume redirect (bootloader -> App)

dts/vendor/nordic/nrf54h20.dtsi
The uart driver for nRF54h20 doesn't call pm_device_runtime_enable().
During an uart driver init `pm_device_driver_init()` return early,
because the `pm_device_is_powered()` returns `false`. Power domains,
where uarts are instantiated, are disabled: `pm->domain->pm_base->state`
is not equal to `PM_DEVICE_STATE_ACTIVE`.
At the end of the day, an uart instance is left disabled.
This is a workaround to make the uart usable when CONFIG_PM,
CONFIG_PM_DEVICE and CONFIG_PM_DEVICE_RUNTIME are enabled.
(cherry picked from commit eaede77351a75cca14acafc470eae6beb03d5852)
Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>
=> [nrf fromtree] dts: nrf54h20: Add zephyr,pm-device-runtime-auto; to uart instances

dts/arm/nordic/nrf54l_05_10_15_cpuapp.dtsi, dts/arm/nordic/nrf54lm20a_enga_cpuapp.dtsi
Set PSA as the entropy source for nRF54lm20a target. PSA is the only NCS-supported interface to CRACEN. There is no other entropy source in 54lm20a than CRACEN.
The commit also disables `rng` compatible with
`nrf-cracen-ctrdrbg`, the nrfx based interface to CRACEN that is used in upstream Zephyr. Only one CRACEN interface may be enabled.
=> [nrf noup] dts: choose a psa-rng for entropy for 54lm20a

drivers/i2c/i2c_nrfx_twis.c
In case of nRF TWIS i2c shim, SoC header include is needed for memory region property presence checker macro.
Upstream PR #: 96413
=> [nrf fromlist] drivers: i2c: nrfx_twis: fix missing SoC header include

subsys/net/ip/tcp.c, subsys/net/lib/dns/llmnr_responder.c, subsys/net/lib/dns/mdns_responder.c, tests/net/socket/getaddrinfo/src/main.c, tests/net/tcp/src/main.c
Just brought those regressions with the upmerge, so get the fixes ASAP.
=> net: Cherry-pick TCP and mDNS regressions bugfixes

cmake/modules/extensions.cmake
This potentially fixes an issues whereby when sysbuild projects import dts configuration from images and images are reconfigured, that sysbuild will needlessly rerun even if the output has not changed by using a temporary output file and then only updating the actual file if the contents have changed
Upstream PR #: 96259
=> [nrf fromlist] cmake: Use temp. for edt pickle CMake output

drivers/mspi/Kconfig.dw, drivers/mspi/mspi_dw.c, tests/drivers/mspi/flash/boards/nrf54h20dk_nrf54h20_cpuapp.overlay, tests/drivers/mspi/flash/testcase.yaml
Provide a Kconfig option that allows offloading handling of the SSI FIFOs, which the driver normally executes in the interrupt handler, to the system workqueue.
=> [nrf fromtree] drivers: mspi_dw: Add option to offload handling of FIFOs

scripts/requirements-actions.in, scripts/requirements-actions.txt, scripts/requirements-compliance.txt, scripts/requirements-extras.txt
Gitlint-core has loose requirements and not conflicting with scancode-toolkit v32.4.1 (click==8.1.3 vs click>=8.2.0).
(cherry picked from commit 67b4063a207ab87c28851513246b28433ef101ed)
=> [nrf fromtree] scripts: requirements: Use gitlint-core for loose requirements

soc/nordic/common/uicr/gen_periphconf_entries.py
Add the mapping for the GRTC_CLKOUT_FAST pinctrl mapping to the periphconf generation. This allows clocking out the 16MHz clock with a user selectable divider.
(cherry picked from commit 19f709910fe53fcff64fb36fd02c0a56f6042365)
=> [nrf fromtree] soc: nordic: common: uicr: Add GRTC fast clkout

drivers/ieee802154/ieee802154_nrf5.c, modules/hal_nordic/Kconfig, modules/hal_nordic/nrf_802154/CMakeLists.txt, west.yml
Upstream PRs: 
96068
96557
96616
=> [nrf fromlist] manifest: Update hal_nordic to pull latest mdk 8.72.4

subsys/mgmt/mcumgr/grp/img_mgmt/Kconfig, subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt_state.c
In Direct XIP with revert, it should be possible to block confirmation of the non-active slot, so only a bootable binaries are marked as valid.
Upstream PR #: 95467
Upstream PR #: 96606
=> [nrf fromtree] mgmt: Allow to block confirming non-acive slots

tests/arch/arm/arm_irq_vector_table/boards/nrf54h20dk_nrf54h20_cpuapp.conf, tests/arch/arm/arm_irq_vector_table/boards/nrf54h20dk_nrf54h20_cpurad.conf
SSF was removed.
This is basically a revert of 8c97493e725979a39138d9a13956ac2c8a5c04bf
but it does not apply cleanly.
Both can be dropped at next upmerge.
=> [nrf noup] tests: arm_irq_vector_table: remove SSF_CLIENT_SYS_INIT

scripts/ci/check_compliance.py
nrf-squash! [nrf noup] scripts: ci: check_compliance: Add NCS sysbuild Kconfigs
Adds Kconfigs to the allow list as they are used in documentation but are not defined
=> [nrf noup] scripts: ci: check_compliance: Add NCS sysbuild Kconfig

soc/nordic/nrf54l/CMakeLists.txt
This adds the required parts for nrf54l kmu in
cmake linker generator.
=> [nrf noup] cmake: nrf54l: iar: fix cmake linker generator for kmu

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts, soc/nordic/nrf54h/pm_s2ram.h
!nrf_squash: [nrf noup] soc/nordic/nf54h/pm_s2ram: S2RAM resume hardening
Extended mcuboot_resume_s suture by slot_info field intended to be used by MCUboot for recognize proper boot slot in direct-xp mode.
=> [nrf noup] soc/nordic/nrf54h20/pm_s2ram: extend mcuboot_resume_s

subsys/bluetooth/host/Kconfig.gatt, subsys/bluetooth/host/att.c, subsys/bluetooth/host/conn.c, subsys/bluetooth/host/l2cap.c
The `delay ATT sent callback until data transmission is done by controller` feature introduces an extra `net_buf` reference which is removed on sent callback. Make sure to remove the reference on BLE disconnection to free the buffer as the registered sent callback will not be called.
Jira: NCSDK-35650
=> [nrf noup] bluetooth: att: Fix `CONFIG_BT_ATT_SENT_CB_AFTER_TX`
