nrfconnect/sdk-zephyr

dts/common/secureboot.overlay

This provides support for BOARD=nrf52810_pca10040.

[nrf noup] dts: Add nRF52810 to secureboot.overlay

---

scripts/meta/west/runners/nrfjprog.py

This file will disappear when we upmerge next, but we need this fix in
the meantime to be able to flash the nRF91.

[nrf noup] scripts: west: nrfjprog: Support nRF91

---

include/arch/arm/cortex_m/scripts/linker.ld

Fix up for linker script to place firmware metadata in the built hexfile
for secure bootloader.

[nrf temphack] include: arm: linker.ld

---

CMakeLists.txt
Kconfig.zephyr
arch/CMakeLists.txt

Certain components (e.g. bootloaders) will get conflicts
with symbols defined in 'drivers' and 'arch', create kconfig
which allows them to opt out of these.

[nrf temphack] cmake: kconfig: Support building without kernel

---

Jenkinsfile

CI does not pass with the old NCS toolchain.

[nrf noup] jenkinsfile: Update NCS toolchain version

---

include/net/net_ip.h
include/net/socket.h

Adding socket family type AF_LOCAL.
Adding socket type SOCK_MGMT used in conjuction with with AF_LTE.
Adding socket protocol NPROTO_PDN to be used in conjuction with AF_LTE.
Adding socket protocol NPROTO_DFU to be used in conjuction with AF_LOCAL.
Adding SOL_PDN and SOL_DFU socket option levels, and associated socket
option values.
Signed-off-by: Glenn Ruben Bakke <glenn.ruben.bakke@nordicsemi.no>

[nrf noup]: include: net: Align with bsdlib defines.

---

include/arch/arm/cortex_m/scripts/linker.ld

This will be changed when linker snippets (PR #109) is merged.
This change is required for https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/556, because it seems unlikely that #109 will be merged in the near future. If and when #109 is merged, this change is no longer needed.

[nrf temphack] cortex_m: linker: Add ext_abi section

---

CMakeLists.txt

Without this patch multi image builds will fail
as the modules' build directories are the same
for each image, resulting in an error.
With this patch, each module build dir is placed
within each images build dir, making them unique.

cmake: re-apply patch needed for multi image

---

cmake/app/boilerplate.cmake

This is done so that sub-images of a non-secure image
is built as secure.
This is needed for https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/613

cmake: automatically board change from 'xns' to 'x'

---

scripts/partition_manager.py

This is coupled with
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/657
where a split on ':' would result in a split on 'c:\' on windows.
Changing the split deliminator to '|' will fix this problem as you
are not allowed to named folders on windows or linux to '|'.

[nrf noup] scripts: cmake: partition_manager: Bug fix for windows

---

cmake/partition_manager.cmake

Added missing dependency from 'flash' to 'pm_mergehex'.

[nrf noup] cmake: fix flash dependency on mergehex

---

cmake/zephyr_module.cmake
scripts/zephyr_module.py

On some systems where you don't have access to `PATH` and you can't set the `ENV{PATH}` variable to what you need it to be. This means that the path where west is won't be passed down to the python script this should have been set explicit.
This is a bugfix to get NCS to work with SES on OSX

[nrf toup] cmake: zephyr_modules: Add west executable argument

---

cmake/target_toolchain.cmake

The C compiler does not change between the different images.
Add a check to ensure that the C compiler variable is only
unset for the first boilerplate execution.

cmake: only unset CMAKE_C_COMPILER in first boilerplate execution

---

tests/drivers/counter/counter_basic_api/src/test_counter.c

Xtal LF clock source starts hundreds of milliseconds. When it is
not start, test may fail due to wrong timing. Added pending
on LF clock being start in test setup.
Fix is part of PR: https://github.com/zephyrproject-rtos/zephyr/pull/15623
Fixes broken counter test on pca10040.

[nrf toup] tests: drivers: counter: Add clock stabilization nRF

---

cmake/partition_manager.cmake

In some corner cases, it is required to depend on both
the wrapper target for a file generated through add_custom_command
AND the file being generated.
Prior to this fix, the dependency from 'merged_to_sign.hex'
to 'signed.hex' was not being enforced. This resulted in
outdated 'merged.hex' files when re-building.
This commit fixes this dependency, making a re-build
correctly re-generate the 'signed.hex' and hence 'merged.hex'.

cmake: depend on file AND wrapper target for merged_to_sign

---

cmake/app/boilerplate.cmake
cmake/extensions.cmake

Global properties:
- ${IMAGE}PROJECT_BINARY_DIR.
Helper function:
- get_image_name() to strip the '_'.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

[nrf toup] cmake: Improve access to other images in multi-image builds.

---

cmake/partition_manager.cmake
scripts/partition_manager.py

…manager
This commit adds support for predefined configuration.
This is a feature intended for deployed products consisting of multiple images.
It is crucial that any new versions of these images are linked to the correct
location. This is solved by this commit.
Also, this fixes the issue of building sub-images with mixed build strategies.

Partition manager: predefined configuration

---

Jenkinsfile

Fixes some missing KConfig argument errors in check_compliance.py

[nrf noup] ci: move ci-tools to latest on master

---

doc/application/index.rst

Language fixes for Application Development > Building and
configuring multiple images.
Note that this is only a copy edit. I find the documentation very hard to understand.
Signed-off-by: Ruth Fuchss <ruth.fuchss@nordicsemi.no>

doc: application: fix doc for multi-image builds

---

arch/arm/core/cortex_m/tz/CMakeLists.txt

1. Seamlessly call into secure zone to do reboot.
2. Add extra Cmake target so SPM builds before app when using secure entry functions.

Extra changes for Non-Secure Callable support

---

Jenkinsfile

This is a temporary fix. We will find a permanent solution after v1.0.0 release.

ci: Skip Kconfig compliance check temporarily

---

cmake/app/boilerplate.cmake

This is done so that sub-images of a nrf9160_pca20035ns image
are built as secure.
Signed-off-by: Jan Tore Guggedal <jantore.guggedal@nordicsemi.no>

[nrf noup] cmake: Automatic board change for PCA20035

---

subsys/logging/log_core.c

Detection of missing log_strdup call was applied to every message
while it applies only to standard messages (string + arguments).
Appling it to hexdump messages could lead to fault as seen on
nrf9160_pca10090ns board.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/16718

[nrf fromlist] logging: Fix log_strdup detection on nonstandard message

---

include/arch/arm/cortex_m/scripts/linker.ld

FW_METADATA is its own subsys now.
This improves user experience with B0 + MCUboot.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>

[nrf noup] linker.ld: Change ifdef from SECURE_BOOT to FW_METADATA

---

Jenkinsfile

Managing Docker version, Agent Labels, Github Status,
manifest updates, downstream jobs from CI_LIB.
More info: https://projecttools.nordicsemi.no/confluence/display/NCS/Linking+Jenkins+Jobs+Together

[nrf noup] ci: use Standard Library in Jenkinsfile to link sub-projects together

---

subsys/dfu/img_util/flash_img.c
subsys/net/lib/lwm2m/ipso_accelerometer.c
subsys/net/lib/lwm2m/ipso_onoff_switch.c
subsys/net/lib/lwm2m/ipso_push_button.c
subsys/net/lib/lwm2m/ipso_temp_sensor.c

Let's add a timestamp field to the following objects for better
event tracking:
- IPSO Accelerometer
- IPSO On/Off switch
- IPSO Push Button
- IPSO Temperature
Signed-off-by: Michael Scott <mike@foundries.io>

[nrf noup] net: lwm2m: add timestamp fields to several IPSO obj

---

CMakeLists.txt

Misc. multi-image related build fixes:
Add an IMAGE prefix to new targets that have been introduced and ensure that variables are initialized before de-referenced.
This fixes the build issues with nrf91ns+userspace.

Multi image fixes

---

CMakeLists.txt

Previously the build code in the 'drivers' folder included
some files which caused a compilation error for B0.
This problem has been fixed, and the folder can now
safely be included in the build.
This aligns with upstream code.

[nrf-noup] cmake: remove check for including 'drivers'

---

cmake/kconfig.cmake

Allow CONFIG parameters to be specified in command line to cmake
This will e.g. make cmake [...] -DCONFIG_BOOTLOADER_MCUBOOT work again
It also allows e.g. cmake [...] -Dmcuboot_CONFIG_xxx to enable configs in mcuboot.
The second commit I'm a bit unsure if of. Double check if it is ok.

Multi-image: Fixes in kconfig.cmake

---

doc/getting_started/installation_win.rst
scripts/requirements.txt
scripts/sanitycheck

- Small tweaks to fix paths/memory allocation
- Uses make from chocolatey
- upstream PR is in review. https://github.com/zephyrproject-rtos/zephyr/pull/16619

[nrf temphack] ci: enable windows "sanitycheck --build-only"

---

CMakeLists.txt
include/arch/arm/cortex_m/scripts/linker.ld

To support upgrade of mcuboot we need to build a candidate of mcuboot which is linked against the partition "s1".

Build s1 variant of mcuboot

---

CMakeLists.txt

The size of partition 's0' includes the pad, which should not be
included when calculating the offset from partition 's0_image'
(which mcuboot is linked against originally) to 's1_image'.

cmake: use size of s0_image when offsetting mcuboot for s1

---

drivers/flash/soc_flash_nrf.c

When current image is non-secure and address being read is configured
as secure, use the Non Secure Callable function spm_request_read to
try and read the secure flash area.

[nrf toup] drivers/flash: leverage nsc flash read

---

CMakeLists.txt

The dependency in the wrapper target 's1_image_hex' did not
point to the correct path. Fix this to make the target
work correctly as a dependency.

cmake: fix incorrect path in wrapper target

---

drivers/flash/soc_flash_nrf.c

Only include secure read call if SPM is enabled and partition manager is
in use.

[nrf toup] drivers/flash: limit secure read inclusion

---

Kconfig.zephyr
arch/CMakeLists.txt

This reverts commit 5bbd740cf32a21fe61e3f0a9ec42299ad3083615.
This is no longer needed by b0.

Revert "[nrf temphack] cmake: kconfig: Support building without kernel"

---

include/net/socket.h

Adding SO_PDN_CONTEXT_ID option value for PDN sockets.
Signed-off-by: Christopher Métrailler <christopher.metrailler@nordicsemi.no>

[nrf noup]: include: net: Add option for PDN sockets.

---

CMakeLists.txt

Calculate the offset needed for S1-linked mcuboot based on address
of S1 and S0. This change is needed since empty partitions
can be injected between any partition when alignment is used.
If an empty partition was inserted between S0 and S1 the old way
of calculating the offset would be incorrect.

[nrf noup] cmake: adjust offset after introducing alignment

---

CMakeLists.txt
include/arch/arm/cortex_m/scripts/linker.ld

This symbol is used to ensure that s0 mcuboot points to s1 as
image 1 primary slot, and s1 mcuboot points to s0 as image 1
primary slot.

[nrf noup] linker: add symbol for image 1 primary slot

---

include/net/socket.h

Add SO_PDN_STATE option for PDN sockets
to retrieve the state of the PDN connection.
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>

[nrf noup] net: socket: add SO_PDN_STATE socket option

---

include/net/socket.h

Add SO_DFU_ERROR socket option for DFU socket.
The option can be used when a operation on a DFU socket
returns -ENOEXEC, indicating that the modem has rejected
the operation, to retrieve the reason for the error.
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>

[nrf noup] net: socket: add SO_DFU_ERROR socket option

---

include/net/socket.h

Change from `SO_DFU_RESOURCE` to `SO_DFU_RESOURCES`, as intended.

[nrf noup] net: socket: fix SO_DFU_RESOURCES definition

---

cmake/app/boilerplate.cmake

As the board was merged in the upstream earlier today (commit 62cb2a96abb70b2d805c93836c697d1460a2af30) I am submitting this PR to patch the boilerplate, for your consideration once the mergeup is done. Thank you.

Add cmake boilerplate patch for Actinius Icarus IoT Dev Board

---

CMakeLists.txt
cmake/extensions.cmake

This PR allows amending to a Zephyr library created inside Zephyr repo in a generic way.
Currently, if no files are added to a library, as example the drivers/entropy zephyr library because no drivers (c-files) are selected using Kconfig, the following error when running cmake / menuconfig:
```
CMake Error at /projects/github/ncs/zephyr/cmake/extensions.cmake:411 (add_library):                       
No SOURCES given to target: drivers__entropy
Call Stack (most recent call first):
/projects/github/ncs/zephyr/cmake/extensions.cmake:388 (zephyr_library_named)
/projects/github/ncs/zephyr/drivers/entropy/CMakeLists.txt:3 (zephyr_library)
```
This PR allows to amend drivers files out-of-tree to an existing zephyr library.
As example:
`drivers/entropy/CMakeLists.txt` creates a zephyr library …

[nrf fromlist] cmake: zephyr_library_amend feature

---

tests/subsys/settings/fcb/src/settings_test_delete_fcb.c

This commit fixes the FCB delete test after PR #19541.
Now the entity callback is not called on deleted element.
Signed-off-by: Radoslaw Koppel <radoslaw.koppel@nordicsemi.no>

[nrf fromtree] Test: Settings: Fix FCB delete test

---

samples/net/sockets/echo_client/CMakeLists.txt
samples/net/sockets/echo_client/Kconfig
samples/net/sockets/echo_client/src/ca_certificate.h
samples/net/sockets/echo_client/src/dummy_psk.h
samples/net/sockets/echo_client/src/echo-client.c
samples/net/sockets/echo_client/src/tcp.c
samples/net/sockets/echo_client/src/udp.c
samples/net/sockets/echo_server/CMakeLists.txt
samples/net/sockets/echo_server/Kconfig
samples/net/sockets/echo_server/src/certificate.h
samples/net/sockets/echo_server/src/dummy_psk.h
samples/net/sockets/echo_server/src/echo-server.c
samples/net/sockets/echo_server/src/tcp.c
samples/net/sockets/echo_server/src/udp.c

PSK support is added to echo-client.c.
Enabled by `CONFIG_MBEDTLS_KEY_EXCHANGE_PSK_ENABLED=y`

[nrf fromlist] samples: echo client echo server PSK support

---

scripts/zephyr_module.py

This commit fixes an issue in windows where zephyr_modules.txt contains
a \ as path separator.
This causes issues later when using the path generated by
zephyr_module.txt are used as variables in CMake on windows.

[nrf fromlist] cmake: ensure zephyr_module.py creates posix path output

---

doc/CMakeLists.txt
doc/reference/index.rst

Depends on
NordicPlayground/fw-nrfconnect-nrf#1258.
The Kconfig reference is being turned into a separate shared
documentation set, which needs three nRF-specific Zephyr tweaks:
1. Do not build the Kconfig docs as part of the Zephyr documentation
2. Do not link the index page of the Kconfig docs in the Zephyr
documentation
3. Pass some extra variables with output paths through to sphinx-build,
so that they can be referenced in nrf/doc/zephyr/conf.py. They're
used for the Intersphinx linking.

[nrf noup] doc: Share Kconfig documentation between repos

---

boards/arm/nrf9160_pca10090/nrf52840_reset.c

The reset line wait time of 1 ms has been shown to not be enough for the reset. Increasing to 10 ms.
Signed-off-by: Sigurd Olav Nevstad <sigurdolav.nevstad@nordicsemi.no>

[nrf fromlist] boards: arm: nrf9160_pca10090: increase reset line wait time

---

doc/CMakeLists.txt
doc/reference/index.rst

This reverts commit 943a8651224470b6594e992fd2c58a454540796a.
This commit should have been applied simultaneously with a commit in
nrf but it was not and is now causing problems.

[nrf noup] revert: "943a8651224470b6594e"

---

CMakeLists.txt
cmake/app/boilerplate.cmake
cmake/extensions.cmake
doc/reference/usermode/memory_domain.rst

See also: https://github.com/zephyrproject-rtos/zephyr/pull/20333
This commit allows a more dynamic approach for specifying that a zephyr
library must be placed in a dedicated app memomory partition.
This is still done by defining the partition in code using
K_APPMEM_PARTITION_DEFINE, but now the zephyr library can be added to
the generation of partition table using zephyr_library_app_memory
instead of modifying the overall zephyr/CMakeLists.txt file.

[nrf fromlist] cmake: app mem partion flexibility

---

subsys/bluetooth/Kconfig

Fix dependency on the Host to include the PHY update procedure and the
data length update procedure. In a host-only build this feature should
be possible to select without relying on the supported features of the
controller. The host will check support using HCI command to read
attached controller features and commands supported.
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

[nrf fromtree] Bluetooth: Kconfig: Fix host phy and data length update

---

scripts/west_commands/build.py

APPLICATION_SOURCE_DIR is not in the cache due to multi-image
requiring cache variables to be image-prefixed and due to a desire to
not image-prefix this variable.
But west expects it to be so. To resolve this, have west use a
different variable that points to the same thing.

[nrf noup] west: multi-image: Change variable used to find app dir

---

subsys/settings/src/settings_init.c

New code was introduced upstream, which is not PM-aware. In result NVS
settings backend initialization failed on nRF91.

[nrf noup] settings: Fix NVS initialization with PM enabled

---

subsys/settings/Kconfig

NCSDK-3857: Lowering so we don't use too much settings storage by
default.
@hakonfam @ppryga

[nrf noup] settings: Lower partition settings storage to 0x2000

---

include/arch/arm/cortex_m/scripts/linker.ld

This reverts commit 4cc4339719d422995e65a48c09b8ed6572505bd4.

Revert "[nrf temphack] cortex_m: linker: Add ext_abi section"

---

scripts/west_commands/build.py

This reverts commit 58ee03b3ab9f9effcfb4d2c5b2bcff616db08f9f.
The commit was previously needed for multi-image and is therefore no
longer needed.
An nrf PR for updating west.yml correspondingly will not be created as there is no rush to get this in.

Revert "[nrf noup] west: multi-image: Change variable used [...]"

---

samples/drivers/soc_flash_nrf/sample.yaml

Added harness config to sample in order for the sanitycheck tool
to run and understand whether the samples output is as expected.
Signed-off-by: Łukasz Hejnak <lukasz.hejnak@nordicsemi.no>

NCSDK-3401 Fix soc_flash_nrf sample.

---

Jenkinsfile
scripts/sanitycheck

This PR adds the appropriate coverage platform to avoid the issue that 4a309fb9baa47cef7242e9c46f951653321ae907 was fixing, and then
reverts the previous fix.

Revert "[nrf temphack] ci: work around sanitycheck issue"

---

dts/arm/nordic/nrf9160.dtsi

This commit adds cryptocell definitions to the nRF9160 dts file.

[nrf fromlist] dts: added cryptocell to the dts file for nRF9160

---

Jenkinsfile
scripts/requirements.txt

- Install ci-tools requirementx.txt before check_compliance.py
-- missing python-magic
- edit python requirement versions
-- setting sphinx!=2.4.0
-- (sphinx:2.4.0 released yesterday with a bug that breaks the build)

[nrf noup] ci: python requirement updates

---

subsys/bluetooth/host/Kconfig

Submitted upstream as:
zephyrproject-rtos/zephyr#22717

[nrf fromlist] bluetooth: host: fix RPMsg driver [...]

---

cmake/reports/CMakeLists.txt

To make patches simpler and diff smaller.
nrf pr https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1741

[nrf noup] cmake: include nrf reports cmake from repo

---

include/arch/arm/aarch32/cortex_m/scripts/linker.ld

Since any image (not only mcuboot) can be linked into S1, update the linker
script so that its naming is generic.
nrf pr https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1939

[nrf noup] linker: generalize linking into alternate slot

---

cmake/host-tools.cmake

West version 0.7.0 introduced `west topdir` command.
Unfortunately version 0.7.0 would print the path in windows path style
when executed in Windows.
This commit ensure that `west topdir` is only used if west >= 0.7.1.

[nrf fromlist] cmake: Invoke west topdir only with version >= 0.7.1

---

arch/arm/core/aarch32/cortex_m/tz/secure_entry_functions.ld
soc/arm/Kconfig
soc/arm/nordic_nrf/nrf53/Kconfig.defconfig.nrf5340_CPUAPP_QKAA
soc/arm/nordic_nrf/nrf53/soc.c
soc/arm/nordic_nrf/nrf53/soc.h

This PR adds a kconfig for nRF53 erratum 19 (https://infocenter.nordicsemi.com/topic/errata_nRF5340_EngA/ERR/nRF5340/EngineeringA/latest/anomaly_340_19.html?cp=3_0_1_0_1_15).
Review the solution conceptually, and if you see any problems in putting this upstream as is.
@bjorn-tore-taraldsen: Please review the wording on the config in particular.

Erratum 19 - SPU flash regions are 32 kB instead of 16 kB

---

scripts/requirements.txt

[nrf noup] ci: keep py-Sphinx on v2.x.x

---

cmake/extensions.cmake

The relative path from the build dir to the binary dir of a subsys
folder is not static. In a zephyr subsys it is
build/zephyr/subsys/path
whereas in a nrf subsys it is
build/modules/nrf/subsys/path
The previous way of setting the path to preprocessed pm.yml files
for subsystems only worked with the first of these.
This commit introduces the use of a cmake variable for the binary dir,
and a mechanism for setting the build dir path for each pm.yml
explicitly.
See https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2122

[nrf noup] cmake: change how path to subsys pm.yml is set

---

cmake/extensions.cmake
subsys/fs/CMakeLists.txt
subsys/fs/Kconfig
subsys/fs/pm.yml
subsys/settings/CMakeLists.txt
subsys/settings/Kconfig
subsys/settings/pm.yml

This commit should be squashed with the other partition manager
commits so that only the linker script patch remains of
partition manager patches.
Reduce size of downstream patches by moving as much as possible
of the partition manager (pm) functionality to the nrf repo.

[nrf noup] cmake: move pm patches from zephyr to nrf

---

modules/Kconfig.nordic

NRF_802154_RADIO_DRIVER will be split into 'Radio Driver' part and
'Service Layer' (SL) library. SL will be selectable. To make this possible NRF_802154_SL_CHOICE is added.
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>

[nrf toup] module: hal_nordic: Add NRF_802154_SL_CHOICE

---

drivers/ieee802154/ieee802154_nrf5.c

MPSL is responsible for managing RADIO NVIC settings. The 802.15.4
driver shall not configure RADIO IRQs directly.
Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>

[nrf toup] drivers: nrf_802154: Don't set RADIO NVIC when using MPSL

---

include/net/mqtt.h
include/net/socket.h
subsys/net/lib/mqtt/mqtt_transport_socket_tls.c

[nrf noup] net: socket: Add TLS_SESSION_CACHE option
Add socket opption for TLS session caching.
Signed-off-by: Jan Tore Guggedal <jantore.guggedal@nordicsemi.no>
---
[nrf noup] net: lib: mqtt: Provide option to enable TLS ession caching
Provides an option to enable TLS session caching for an MQTT
client's secure socket.
Signed-off-by: Jan Tore Guggedal <jantore.guggedal@nordicsemi.no>

Add socket option for TLS session cache

---

cmake/app/boilerplate.cmake
doc/guides/env_vars.rst
doc/guides/zephyr_cmake_package.rst
drivers/flash/Kconfig.nordic_qspi_nor
drivers/flash/nrf_qspi_nor.c

Adds the functionality of doing one byte read and write to QSPI nor
driver. This is achived through the use of stack in the function calls.
It also adds the functionality of using stack if the data passed to the
driver are stored in flash and not in RAM. So that the DMA will still
work if you refrence data in flash by copying the data onto the stack.

drivers: flash: Add one byte read write emulation to qspi nor nrf

---

drivers/serial/uart_nrfx_uarte.c

This is a follow-up to commit cf7dd4981fbd1490041cc4367d5d5aaf865b5dd0.
When disabling RX, it is necessary to clear the RXSTARTED event after
the ENDRX_STARTRX shortcut is deactivated, as the event might already
have been generated at this point. If the event is not cleared and
the disabling of RX is done from the user handler called in the context
of the ENDRX interrupt, a spurious UART_RX_BUF_REQUEST event will be
generated (although RX is already disabled) for which a corresponding
call to uart_rx_buf_rsp() would fail, as the second buffer is already
set. Depending on the application implementation, this can result in
other unexpected problems.
(cherry picked from commit 49627feb0380cb121e06bdb0710989d5828a5624)

[nrf fromtree] drivers: uart: Prevent spurious UART_RX_BUF_REQUEST

---

include/storage/flash_map.h

jira: NCSDK-5607
Partition_manager related code was moved to
flash_map_pm.h file in the nrf repository.

[nrf noup] flash_map: remove PM related code

---

modules/Kconfig.nordic
west.yml

This reverts commit 3bdcae3d69ea6652b9e566d1376ab3d085c1b832.
As other 802.15.4 commits in hal_nordic repo are also reverted,
this patch updates the hal_nordic commit hash in west.yml,
so that those commits can be reverted safely.

[nrf toup] module: hal_nordic: Remove NRF_802154_SL_CHOICE

---

include/net/socket.h

Add some socket options to Zephyr header, which will be useful
for nRF91.
-SO_SNDTIMEO
-MSG_TRUNC
Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

[nrf noup] include: net: add nRF91 extensions

---

drivers/bluetooth/hci/Kconfig

The CONFIG_BT_RPMSG_NRF53 should depend on the SOC, not the BOARD
definition. Otherwise this will break for custom boards.
Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>
---
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/26215

[nrf fromlist] Bluetooth: hci: Depend on SOC not BOARD

---

include/net/socket.h

New NRF91 socket options added:
- SO_SILENCE_ALL to disable/enable all replies to unexpected traffics
- SO_IP_ECHO_REPLY to disable/enable replies to IPv4 ICMPs
- SO_IPV6_ECHO_REPLY to disable/enable replies to IPv6 ICMPs
SO_REUSEADDR comment cleanup since it will be supported by NRF91.
Signed-off-by: Petri Honkala <petri.honkala@nordicsemi.no>
sdk-nrf PR: https://github.com/nrfconnect/sdk-nrf/pull/2540
sdk-zephyr PR: https://github.com/nrfconnect/sdk-zephyr/pull/325

[nrf noup] include: net: new socket options for NRF91

---

boards/arm/nrf5340dk_nrf5340/Kconfig

Boards does not map well to a domain.
Disassociate domains from boards.
NRF PR https://github.com/nrfconnect/sdk-nrf/pull/2527
Upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/26439

[nrf fromlist] boards: add domain board to nrf53 network

---

subsys/net/l2/openthread/openthread.c

Fix the OpenThread initialization to prevent the IPv6 interface to
be enabled when `CONFIG_OPENTHREAD_RAW` is set.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>
(cherry picked from commit a136f2f695ee27dfe81c516fb2608448c55e8816)

[nrf fromtree] net: openthread: fix initialization with link raw enabled

---

include/kernel_structs.h

The fix to handle long duration timeouts in 150e18de6e1806942 also
changed the duration value from signed to unsigned.  This can cause
delays in processing alarms when timer handlers run longer than a tick
(either due to delays or if there are many of them).  Revert to a
signed representation.
sdk-nrf PR: https://github.com/nrfconnect/sdk-nrf/pull/2913

[nrf fromtree] kernel/timeout: revert to signed dticks for timeout storage

---

subsys/bluetooth/controller/hci/hci.c
subsys/bluetooth/controller/include/ll.h

Fix regression in the disconnect complete event encoding where the
disconnect reason was accidentally deleted.
Regression introduced during conflict resolution of uint8_t and u8_t
differences in cherry-pick of:
736b79c
Change the LL version back to 5.1, to be able to re-use existing
Bluetooth conformance qualification.

Bluetooth: controller: Fix qualification issues

---

drivers/serial/uart_nrfx_uarte.c

Reset rx byte counters when hw timer/counter is disabled.
Fixes issue where disabling and re-enabling async uart rx can produce
"UART_RX_RDY" events with invalid data when power management is used.
Signed-off-by: Audun Korneliussen <audun.korneliussen@nordicsemi.no>

drivers: serial: nrf_uarte: Reset rx byte counters

---

subsys/bluetooth/controller/ll_sw/ull_conn.c
subsys/bluetooth/controller/ll_sw/ull_slave.c
subsys/bluetooth/controller/ll_sw/ull_slave_internal.h

Fix controller implementation to cancel peripheral latency
when initiating new control procedures.
Fixes #28699.
Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

[nrf fromtree] Bluetooth: controller: Fix latency cancel on LLCP initiation

---

include/arch/arm/aarch32/cortex_m/scripts/linker.ld

Partition manager now supports partitioning RAM as well as FLASH.
Use the RAM_ADDR and RAM_SIZE as defined by the partition manager.

[nrf noup] linker: use partition manager to set RAM

---

boards/arm/nrf5340dk_nrf5340/Kconfig

This is needed for when network core image is parent.
Upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/28988
Ref: NCSDK-6542

[nrf fromlist] kconfig: add config for cpuapp domain board

---

subsys/shell/Kconfig

Default shell stack size is not always enough when used with OpenThread. Increasing it to the found adequate value.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

[nrf toup] shell: increase stack size for OpenThread

---

drivers/ieee802154/ieee802154_nrf5.c
drivers/ieee802154/ieee802154_nrf5.h

Upstream PR #29123
Add support for transmission modes that send a packet
at a specific time in the future.

drivers: ieee802154: nrf5: Add support for tx in the future

---

dts/arm/nordic/nrf5340_cpuapp.dtsi

-Adding cryptocell as zephyr,entropy for nRF5340 in dts
ref: NCSDK-4638
Used by (dependent on):
manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/2758
nrfxlib PR: https://github.com/nrfconnect/sdk-nrfxlib/pull/242

[nrf toup] drivers: Adding cryptocell as chosen entropy for nRF5340

---

drivers/ieee802154/ieee802154_nrf5.c
drivers/ieee802154/ieee802154_nrf5.h

Remove the implementation of nrf_802154_tx_started
radio driver callback. Remove the semaphore dedicated
to this callback.
PR updating the manifest:
https://github.com/nrfconnect/sdk-nrf/pull/3108
Jira: KRKNWK-7789

drivers: ieee802154: nrf5: Remove nrf_802154_tx_started callback

---

subsys/net/l2/openthread/Kconfig.thread
subsys/net/lib/openthread/platform/openthread-core-zephyr-config.h

Another team reported that current default values for number of allowed
IP addresses per child (4) and and max number of children (10) are too
small for some customers.
Increased the values allowed configuring child count.
Jira
https://projecttools.nordicsemi.no/jira/browse/KRKNWK-7796
manifest: 
- https://github.com/nrfconnect/sdk-nrf/pull/3139
Signed-off-by: Marek Porwisz <marek.porwisz@nordicsemi.no>

[nrf fromlist] net: openthread: Increase the number of allowed children

---

tests/bluetooth/tester/src/gap.c
tests/bluetooth/tester/src/l2cap.c

Upstream PR: zephyrproject-rtos/zephyr/pull/29572
It implements the missing tests related to OOB pairing and LE COC.
Co-authored-by: Konstantinos Sotiropoulos
<konstantinos.sotiropoulos@nordicsemi.no>
Co-authored-by: Aytürk Düzen <ayturk.duzen@nordicsemi.no>
Signed-off-by: Ryan Chu <ryan.chu@nordicsemi.no>
(cherry picked from commit 385000e8d94f2a2caed91518b6c4e447fc50ff33)

[nrf fromtree] Bluetooth: tester: Support PTS tests related to OOB and LE COC

---

include/net/socket.h

Add MSG_WAITALL socket flag required to support the corresponding NRF
counterpart flag, for translation within the offloading interface.
Linked to https://github.com/nrfconnect/sdk-nrf/pull/3116

include: net: Add MSG_WAITALL flag definition

---

subsys/bluetooth/controller/Kconfig
subsys/bluetooth/mesh/Kconfig

Zephyr controller does not yet have a qualification for this release.
Bluetooth Mesh does not yet have a qualification for this release.
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/3370
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

[nrf noup] Bluetoooth: Add experimental for non-qualified options

---

drivers/ieee802154/ieee802154_nrf5.c

This commit depends on commit:
16786a8
drivers: ieee802154: nrf5: Add support for tx in the future
and should be reverted when
zephyrproject-rtos/zephyr#29123
is upmerged.
Remove TXTIME, TXTIME_CCA, CSMA_CA capabilities and their calls when
they are not supported by selected drivers. Add TXTIME flag in
get_capabilites function.
This commit induces code style warnings. Warnings are related to macro
alignment. Fixing them renders macros less readable. As consulted with
reviewers, in this case it is acceptable.
Signed-off-by: Pawel Kwiek <pawel.kwiek@nordicsemi.no>

 [nrf temphack] drivers: ieee802154: nrf5: Remove TX modes when not supported

---

drivers/ieee802154/ieee802154_nrf5.c

This commit allows the setting of ieee802154 EUI64 address
in the non-secure build by reading the FICR registers out
of the secure zone.
Signed-off-by: Czeslaw Makarski <Czeslaw.Makarski@nordicsemi.no>

[nrf noup] drivers: ieee802154: Use nRF Secure Services to read EUI64

---

drivers/flash/soc_flash_nrf.c

Will not call spm_request_read when secure services are disabled.
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

[nrf noup] drivers: flash: No spm_request_read when no secure services

---

scripts/west_commands/runners/mdb.py

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/30661/
Runner implementations are only allowed to unconditionally import
modules in the python standard library. They are not allowed to import
anything that comes from pip or other third party sources unless they
catch the ImportError and gracefully do nothing.
Fix the imports in the mdb runner accordingly, sorting the imports
into sections to make it clearer what's stdlib, what's runners, and
what's third party while we're here.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

[nrf fromlist] runners: mdb: fix imports

---

west.yml

This PR updates the used hal_nordic revision to the latest one.
(below is the description of the last cherry-picked commit)
This commit brings in a fix for a typo in hal_nordic repo.
(cherry picked from commit c284a72b45645549479e7b19f8403caf6c293415)
Signed-off-by: Czeslaw Makarski <Czeslaw.Makarski@nordicsemi.no>

[nrf fromtree] west.yml: Update hal_nordic revision

---

samples/subsys/mgmt/mcumgr/smp_svr/overlay-bt.conf

The known issue NCSDK-6832 regards the softdevice using  more stack than
what is allocated by default, causing a stackoverflow after booting the
app. Increasing the stack resolves the issue on nRF52 devices, as well
as compiling with CONFIG_BT_LL_SW_SPLIT=y.
Ref: NCSDK-6855
Signed-off-by: Stephen Stauts <stephen.stauts@nordicsemi.no>

[nrf noup] samples: smp_svr: Increase stack size for overlay-bt.conf

---

samples/net/lwm2m_client/sample.yaml

BLE and LwM2M grew in terms of RAM usage so that the sample does not
fit into nRF52832 anymore in the default configuration. This cause
twister to report an error when overflows errors are enabled.
Upstream PR 31350

[nrf fromlist] samples: net: lwm2m_client: Remove nrf52dk_nrf52832 from the allowlist

---

scripts/zephyr_module.py

West has introduced support for group tags in:
https://github.com/zephyrproject-rtos/west/pull/454
This means that manifest files might start containing groups.
Zephyr itself only requires west>=0.7.2 where groups are not supported
but other Zephyr based projects might start using the group feature.
When using a west version with group support, then only active projects
will be processed as Zephyr modules.
West versions without group support will consider all projects active.

[nrf fromtree]: scripts: modules: support west group feature

---

subsys/bluetooth/host/smp.c

Fail the pairing procedure when both devices have the same non-debug
public key.
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit 3102f3b0813d113a59dea8ff9d58e02a76b7ad0c)

[nrf fromtree] Bluetooth: host: Fail pairing with identical public key

---

drivers/gpio/Kconfig.nrfx
drivers/gpio/gpio_nrfx.c

The GPIO driver uses a proprietary GPIOTE channel allocator.
This commit makes it use the allocation mechanism provided by nrfx.
This PR cherry-picks commit introduced to upstream in https://github.com/zephyrproject-rtos/zephyr/pull/31606 in order to unblock https://github.com/nrfconnect/sdk-nrf/pull/3770 and https://github.com/nrfconnect/sdk-nrf/pull/3750.

[nrf fromtree] drivers: gpio_nrfx: Allocate GPIOTE channels with nrfx

---

drivers/ieee802154/ieee802154_nrf5.c
modules/hal_nordic/Kconfig
modules/hal_nordic/nrfx/nrfx_glue.h
west.yml

The cherry-picked commits originate from zephyrproject-rtos/zephyr#31474
This PR suppresses #439 and #435

nRF5340 multiprotocol fixes

---

include/device.h

Get rid of compilation warnings caused by additional parentheses (visible only when using C++ compilator - e.g. in CHIP).
Upstream merged PR: https://github.com/zephyrproject-rtos/zephyr/pull/31471

[nrf fromtree] api: remove unnecessary parentheses in DEVICE_NAME_GET.

---

cmake/zephyr_module.cmake
doc/guides/modules.rst

... ZEPHYR_MODULE_NAMES
This allows users to overrule a module from command line.
As example, the Zephyr build system loads the module FOO from
`modules/FOO`, but user has a custom FOO locally at `custom/FOO` and
would like to use this module instead of manifest specified.
If user does `-DZEPHYR_EXTRA_MODULES=custom/FOO` the following error
will be seen:
```
The binary directory
build/modules/FOO
is already used to build a source directory.  It cannot be used to build
source directory
custom/FOO
Specify a unique binary directory name.
```
Removing duplicates from the list allows a user to use
`-DZEPHYR_EXTRA_MODULES=custom/FOO` and thus replace `modules/FOO` for
the current build.

[nrf fromtree]: cmake: modules: remove Zephyr module duplicates from ..

---

subsys/settings/src/settings_nvs.c

Upstream commit: 563c24f
There was a case when the return code was ignored. This commit fixes it.

[nrf fromtree]: settings: Handle unhandled error

---

drivers/sensor/adxl362/adxl362.c

This patch fixes warnings for unused variables when accelerometer
range and sampling frequency are set to values different from
the defaults.
Copy of upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/31972

[nrf fromtree] drivers: sensor: adxl362: Fix unused variable warnings

---

drivers/serial/uart_nrfx_uarte.c

If statement was unconditionally reading a field from async struct
while pointer to this struct may be null if asynchronous API is
enabled but given driver instance is not using it.

[nrf fromtree] drivers: serial: nrfx_uarte: Add missing check

---

CMakeLists.txt

This is a temporary fix for excluding the `print-ot-config` from target ALL.
This temphack must be reverted when zephyr/openthread has been upmerged with
this commit: 32257403b04e437280379c7fba91dad213c73887
See more here:
https://github.com/openthread/openthread/pull/6175
This fixes the issue reported here:
https://devzone.nordicsemi.com/f/nordic-q-a/71586/ses-ncs-seem-to-build-ok-but-throws-error-starting-process-echo/294588
-------
Manifest: https://github.com/nrfconnect/sdk-nrf/pull/3956

[nrf temphack] cmake: exclude print-ot-config for target ALL

---

subsys/net/lib/openthread/platform/radio.c

The use of a single error variable for RX and TX operations has shown the OpenThread code to be asserting in some conditions.
Assert happens here: https://github.com/zephyrproject-rtos/openthread/blob/zephyr/src/core/mac/sub_mac.cpp#L494
KRKNWK-8998

[nrf fromlist] net: openthread: separated variable for rx/tx operations results

---

dts/arm/nordic/nrf5340_cpuappns.dtsi
dts/bindings/crypto/nordic,nrf-cc312-sw.yaml

-Adding cryptocell_sw as a chosen entropy source as the non-secure
does not have access to a entropy peripheral and need to SPM (and
later PSA APIs through the same driver)
-Not upstream as driver is only downstream
manifest pr: https://github.com/nrfconnect/sdk-nrf/pull/3978
ref: NCSDK-8246

[nrf noup] dts: Adding cryptocell_sw as chosen entropy

---

kernel/timeout.c

Time slices don't have a timeout struct associated and stored in
timeout_list. Time slice timeout is direct programmed in the system
clock and tracked in _current_cpu->slice_ticks.
There is one issue where the time slice timeout can be missed because
the system clock is re-programmed to a longer timeout. To this happens,
it is only necessary that the timeout_list is empty (any timeout set)
and a new timeout longer than remaining time slice is set. This is cause
because z_add_timeout does not check for the slice ticks.
The following example spots the issue:
K_THREAD_STACK_DEFINE(tstack, STACK_SIZE);
K_THREAD_STACK_ARRAY_DEFINE(tstacks, NUM_THREAD, STACK_SIZE);
K_SEM_DEFINE(sema, 0, NUM_THREAD);
static inline void spin_for_ms(int ms)
{
uint32_t t32 = k_uptime_get_32();
while …

[nrf fromtree] sched: timeout: Do not miss slice timeouts

---

west.yml

The new revision fixes a problem with long build paths on Windows.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>

[nrf fromlist] west.yml: Update hal_nordic revision

---

kernel/timeout.c

Fix an edge case that snuck in with the recent fix: if timeslicing is
enabled, the CPU's slice_ticks will be zero, and thus match a timeout
object's dticks value of zero, and thus get suppressed (because "we
already have a timeout scheduled for that") incorrectly.
Fixes #31789
Signed-off-by: Andy Ross <andrew.j.ross@intel.com>

[nrf fromtree] kernel/timeout: Schedule zero-time timeouts

---

scripts/pylib/twister/twisterlib.py

Currently duplicated testcases are only determined by the classname.
This results in testcases not beeing added to the twister.xml if the
testcases are from the same class (e.g. sample.yaml), but with different
names.
The changed check if the combination of classname and testname
already exists.
Signed-off-by: Sebastian Wezel <sebastian.wezel@nordicsemi.no>

[nrf fromtree] twisterlib: checking for classname and testname

---

subsys/storage/flash_map/flash_map_default.c

Remove custom flash_map_defult.c for Partition Manager.
Ref: NCSDK-5469
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>

[nrf noup] subsys: storage: Remove custom flash_map_default.c

---

include/posix/sys/socket.h

Needed by: https://github.com/nrfconnect/sdk-nrf/pull/4074
Signed-off-by: Jani Hirsimäki <jani.hirsimaki@nordicsemi.no>

[nrf noup] posix socket: sckt flags MSG_TRUNC and MSG_WAITALL added

---

drivers/flash/soc_flash_nrf.h
samples/subsys/mgmt/mcumgr/smp_svr/overlay-bt.conf
subsys/bluetooth/controller/Kconfig

Revert default selection of CONFIG_LL_SW_SPLIT since CONFIG_LL_SOFTDEVICE is now the default.
Revert main stack size configuration in SMP_SVR and instead change the default main stack size to for easier stack size managament.

Revert noup commits no longer needed

---

subsys/bluetooth/Kconfig
subsys/bluetooth/controller/Kconfig
subsys/bluetooth/host/Kconfig.l2cap
subsys/bluetooth/host/att.c
subsys/bluetooth/host/smp.c
subsys/bluetooth/mesh/Kconfig

Update experimental tag in Bluetooth to be aligned with unqualified bluetooth features:
- Zephyr controller does not yet have a qualification for this release.
- Bluetooth Mesh does not yet have a qualification for this release.
- Remove experimental on qualified feature Extended Advertising.
- Add experimental on unqualified feature L2CAP Enhanced Credit Based Flow Control.
Cherry-pick fixes:
- Fix ATT packet reordering
- Fix not overwriting the Bond when peer has stopped using the IRK stored in the Bond information.
- Fail pairing early during Pairing Feature Exchange if the required security cannot be reached.
- Fail pairing early during Pairing Feature Exchange in SC-only mode if security is initiated by remote that cannot reach L4.

Bluetooth: Update experimental and backport fixes

---

drivers/flash/soc_flash_nrf_ticker.c
subsys/bluetooth/controller/include/ll.h
subsys/bluetooth/controller/ll_sw/ull.c

Cherry-pick of the flash driver fixes that have been taken
from Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/33771
After upmerge the Bluetooth Mesh random tests started asserting on CI with:
`ZEPHYR FATAL ERROR 4: Kernel panic on CPU 0` within the flash driver.
The regression has been fixed by the flash driver code owner in upstream.
Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>

[nrf fromtree] Bluetooth: controller: Fix flash driver sync regression

---

boards/arm/mps2_an521/Kconfig.defconfig

...BUILD_WITH_TFM
We do not need to have dependencies any more on !OPENAMP
for BUILD_WITH_TFM in the mps2 an521 target, because we
now have different targets for the non-secure version of
the board and the remote core.
[nrf note]: This is already cherry-picked once in #511, but due to
reversal of a temphack, it was only partially picked, and the changes in
this patch were missing.
Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>
(cherry picked from commit e04a57de046e0e1fba25d3ecc11bd6d7611e3664)
Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>

[nrf fromtree] boards: mps2_an521: remove dependencies for

---

drivers/ieee802154/ieee802154_nrf5.c
west.yml

This commit updates the revision of hal_nordic component
and introduces necessary changes to the IEEE 802.15.4 driver
to match latest nRF IEEE 802.15.4 radio driver API.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/34451

[nrf fromlist] drivers: ieee802154: Udpate nRF IEEE 802.15.4 radio driver

---

include/net/socket.h

Add AI_PDNSERV flag, to to specify the ID
of the PDN to route DNS queries through.
Used since libmodem v1.1.0.
Needed by: https://github.com/nrfconnect/sdk-nrf/pull/4361

[nrf noup] include: net: add AI_PDNSERV flag

---

include/net/net_ip.h
include/net/socket.h
include/net/socket_ncs.h

Introduce new nRF91 specific TLS and RAI socket options. 
Additionally, rework how local extensions to the networking headers are handled downstream. Instead of modifying the upstream socket.h header, introduce a new one, specifically for NCS extensions, and keep all of the local changes in there. The only change needed in the original header is an inclusion of the new header. This should help to keep the local changes in order and facilitate the future upmerge process.

[nrf noup] net: sockets: Add new DTLS and RAI socket options 

---

.github/workflows/clang.yaml

Use the -M option to cleanup as we go to deal with any
disk space issues.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
(cherry picked from commit c71e2dc0077d658b61a8981df6181269890fbc66)

[nrf fromtree] actions: clang: invoke twister with -M to keep size down

---

modules/trusted-firmware-m/CMakeLists.txt

The TF-M build is passed a path to the mbedtls project
directory, however, NCS has its own mbedtls variant. When
building with TF-M we use a generator expression to allow
setting the path to mbedtls from nrf_security.
Signed-off-by: Ioannis Glaropoulos <Ioannis.Glaropoulos@nordicsemi.no>

[nrf toup] Override the TF-M MBEDCRYPTO_PATH

---

include/net/socket_ncs.h

This commit adds a new socket option `SO_TCP_SRV_SESSTIMEO` for
configuring TCP session server timeout in minutes. Legal values
range from 0 to 135.

[nrf noup] include: net: add TCP sesstimeo socket option for nRF91

---

modules/trusted-firmware-m/CMakeLists.txt
modules/trusted-firmware-m/Kconfig

These are needed to disable not needed crypto modules in
the trusted-firmware-m module.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/35901

[nrf fromlist] modules: tfm: add option for selecting crypto modules

---

west.yml

Update the hal_nordic module revision, to have Doxygen doc
fixes that solves warnings about non-existing CHANGELOG.md file
and nrfx_atomic Doxygen group.
This is needed for following PR: https://github.com/nrfconnect/sdk-nrf/pull/4722

[nrf fromtree] modules: hal_nordic: Update nrfx to have doc fixes

---

west.yml

Fixes twister errors on sdk-zephyr/master

[nrf fromtree] manifest: update hal_nordic

---

soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf53/soc.c

This is a follow-up to commit 60d9988401e59093edb0cd638b1b737288477cb0.
Add a third option for the HFXO capacitance that keeps the default
value of the XOSC32MCAPS register untouched. The message in the above
commit incorrectly claimed that external load capacitors for HFXO
(the reset value of the XOSC32MCAPS register) was the configuration
in effect before. In fact, the register value was modified during
the device trimming in the SystemInit() function to use the internal
capacitors, and that is the configuration required for proper RADIO
operation on nRF5340 DK, for instance.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/36320

[nrf fromlist] soc: nrf53: Fix configuration of HFXO capacitance

---

subsys/bluetooth/controller/ll_sw/nordic/lll/lll_slave.c
subsys/bluetooth/controller/ll_sw/ull_adv.c
subsys/bluetooth/host/l2cap.c
subsys/bluetooth/host/smp.c

[nrf fromtree] Bluetooth: host: Prevent race condition in pairing procedure
Moving the key check after checking that no pairing or encryption
procedure is started fixes a race condition that is seen in some PTS
tests:
GATT/CL/GAR/BI-04-C
GATT/CL/GAR/BI-16-C
GATT/CL/GAR/BI-21-C
GATT/CL/GAW/BI-05-C
GATT/CL/GAW/BI-12-C
[nrf fromlist] Bluetooth: L2CAP: Fix missing net_buf_unref()
In case of non-recoverable errors (e.g. the connection breaks while
transmitting), the l2cap_chan_tx_process deques the net_buf but does
not unreference it. As this is inside a work queue thread, the sending
thread gets no information on this error, relying on the tx_process to
ultimately free the buffer.
Upstream PR: zephyrproject-rtos/zephyr#36031
[nrf fromtree] Bluetooth: controller: Check length field of scan …

Bluetooth: Cherry-pick upstream commits

---

drivers/ieee802154/ieee802154_nrf5.c

This commit fixed buggy fall-throughs introduced with
recent changes to nRF5 shim layer.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/36252
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>

[nrf fromlist] drivers: ieee802154: fix unintentional case fall-through

---

modules/trusted-firmware-m/CMakeLists.txt
modules/trusted-firmware-m/Kconfig.tfm.crypto_modules

A new configuration is available in TFM, expose this configuration.
Ref: NCSDK-10031

[nrf fromlist] modules: tfm: add configuration for disabling the RNG … 

---

drivers/serial/uart_nrfx_uart.c
drivers/serial/uart_nrfx_uarte.c

Configured UARTE input pins to have pullups. Otherwise when
uart is disconnected pins are floating and generate receiver
errors.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/36366

[nrf fromlist] drivers: serial: nrfx_uarte: Add pullups to RXD and CTS

---

subsys/net/l2/openthread/Kconfig

`OPENTHREAD_SHELL` does no longer dependend on
`OPENTHREAD_COPROCESSOR` being disabled.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/36401
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>

[nrf fromlist] net: openthread: remove unneded Kconfig dependency

---

.github/workflows/compliance.yml

squash! [nrf noup] ci: Compliance workflow downstream tweaks
Those sauce tags have now been removed from the list of admissible ones.

[nrf noup]: Remove "toup" and "temphack" from sauce tags

---

modules/mbedtls/Kconfig

-This sets the default value for the mbedtls heap size
when we build with TF-M
Ref: NCSDK-10020
Signed-off-by: Georgios Vasilakis <georgios.vasilakis@nordicsemi.no>

[nrf noup] modules: Change mbedtls heap size config

---

subsys/net/lib/sockets/sockets.c

k_timeout_t was converted to ticks using a nonsense function
causing poll timeout corruption for offloaded sockets; this
commit uses ticks directly from the struct instead.

net: socket: fix regression causing corrupted poll timeout

---

drivers/ieee802154/ieee802154_nrf5.c
subsys/net/lib/openthread/platform/radio.c

This commit adds capability to disable CSL sampling by setting
CSL period to 0.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
(cherry picked from commit 678a1709259d8c23b2487b5d428049ac9d67722b)

[nrf fromtree] net: openthread: Add capability to disable properly CSL

---

drivers/flash/Kconfig.simulator
drivers/flash/flash_simulator.c
include/drivers/flash/flash_simulator.h
tests/drivers/flash_simulator/src/main.c

1)
origin https://github.com/zephyrproject-rtos/zephyr/pull/37783
For getting the address of the RAM region in the application we need to
extend the api for the flash_simulator.
This path introduce flash_simulator_get_memory() call which allow to
do so.
2)
origin: https://github.com/zephyrproject-rtos/zephyr/pull/38190
So fare flash simulator had been forced to use the statistic
subsystem.
This patch introduces CONFIG_FLASH_SIMULATOR_STATS which allow to select
whether the statistic is involved in flash_simulator operations.
This patch allows to reduce flash footprint when the statistic is
not required.

[nrf fromlist] drivers/flash/flash simulator: get RAM API + statistic Kconfig on/off

---

subsys/mgmt/mcumgr/Kconfig
west.yml

This is NRF update, taken from  upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/38359, that elevates mcumgr revision to include multi-image support and adds Zephyr commits that allow the feature to be selected via Kconfig.

Mcumgr revision update to add multi-image support to Zephyr

---

subsys/mgmt/mcumgr/Kconfig
west.yml

This is NRF update, taken from upstream PR zephyrproject-rtos/zephyr#38359, that elevates mcumgr revision to include multi-image support and adds Zephyr commits that allow the feature to be selected via Kconfig.

Mcumgr revision update to add multi-image support to Zephyr 

---

doc/getting_started/index.rst

The newly added CMake installation instruction incorrectly specified
*double* colon (literal block) instead of *single* colon after its list
item.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>

 [nrf fromtree] doc: getting_started: Fix incorrect literal block usage 

---

soc/arm/nordic_nrf/Kconfig.defconfig

This is a follow-up to commit 7c9139a300ace41d8f66270b3003684999c01d63
and should be squashed with it on the next upmerge.
The MPU-based null-pointer dereference detection cannot be used on
the network core in nRF5340 because of its flash base address and
this causes the zephyr/tests/arch/arm/arm_interrupt test to fail.
Use the DWT option instead for this core.
Ref. NCSDK-11348

[nrf noup] soc: Use DWT for null-pointer detection on nRF5340 net core

---

drivers/pwm/pwm_nrfx.c

Device data is cleared on deinitialization. This operation removes
some important information. Let's restore the defaults each time
the device is initialized.
Upstream PR:https://github.com/zephyrproject-rtos/zephyr/pull/38615
Jira:NCSDK-11329
Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>

[nrf fromlist] drivers: pwm: Restore default on re-initialization

---

soc/arm/nordic_nrf/nrf53/Kconfig.soc

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/38875
A few HAS_HW_NRF_* Kconfig options for peripherals available in nRF5340
are not selected. Fix it.

[nrf fromlist] soc: nrf53: Add missing HAS_HW_NRF_* entries

---

samples/subsys/mgmt/mcumgr/smp_svr/prj.conf

Upstream commit: ede29d849df914ccc4fb371fa32c2eba32e29d12
Some build variants will fail runtime for certain boards (e.g. nRF52832)
due to stack overflow. Avoid this by increasing the stack size.

[nrf fromtree] samples/mgmt/smp_svr: Increase main stack size

---

.buildkite/daily.yml
.buildkite/pipeline.yml
.github/workflows/bsim.yaml
.github/workflows/clang.yaml
.github/workflows/errno.yml
.github/workflows/footprint-tracking.yml
.github/workflows/footprint.yml

Now that SDK 0.13.1 is released bump buildkite & github workflows
to use this SDK version and the docker image that has it.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
(cherry picked from commit b312470bbb4d1d00bbdb1e8540c4c1752e8adefc)

[nrf fromtree] ci: Bump to use SDK 0.13.1

---

doc/guides/test/twister.rst
scripts/pylib/twister/twisterlib.py
scripts/schemas/twister/hwmap-schema.yaml
scripts/twister

Fix few limitation which do not allow to run Twister on Windows OS.
Especially turn off "import pty" module, due to the fact, that this
module can be used only on POSIX OS.
Fixes #40007
Signed-off-by: Piotr Golyzniak <piotr.golyzniak@nordicsemi.no>
(cherry picked from commit 8b773481e974ec952755e5cad1bd49604c6bb2a8)

[nrf fromtree] twister: reenable build samples on Windows OS

---

include/storage/flash_map.h
samples/subsys/nvs/src/main.c
tests/subsys/storage/flash_map/src/main.c

Upstream commit: a333ffce1d200110887d0cbb1970e947653d357f
The macro returns pointer to a device object the flash area
exists on.

[nrf fromtree] storage/flash_map: Add FLASH_AREA_DEVICE macro

---

subsys/bluetooth/host/hci_core.c

Avoid runtime warning in bt_enable when CONFIG_BT_SETTINGS
and CONFIG_BT_DEVICE_NAME_DYNAMIC is not set.
This warning was intoroduced in
commit d76bba4b5ef85c6b25dfdf9c9809fcead0f4da5c
("Bluetooth: host: Device name handling of invalid length")
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>
(cherry picked from commit 0d4f685dbdb521a35abbb2ad764b775eb3ecdc66)
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>
https://github.com/nrfconnect/sdk-nrf/pull/6103

[nrf fromtree] Bluetooth: Host: avoid runtime warning in bt_enable

---

modules/hal_nordic/nrfx/CMakeLists.txt
soc/arm/nordic_nrf/Kconfig

Add Kconfig option to enable the hardware trace port in the SystemInit()
function.
Signed-off-by: Gregers Gram Rygg <gregers.gram.rygg@nordicsemi.no>

[nrf fromtree] soc: nordic_nrf: Add Kconfig option for enabling trace port

---

include/net/socket_ncs.h

The PDN socket has been removed from Modem library in version v1.4.0.
Remove PDN-related macros from socket_ncs.h.

[nrf noup] net: socket_ncs: remove PDN socket and related macros

---

cmake/zephyr_module.cmake
scripts/ci/check_compliance.py

squash! [nrf noup] ci: set `ZEPHYR_<MODULE_NAME>_KCONFIG` for NCS modules
This commit extends the check_compliance to add
`NCS_<module_name>_KCONFIG` for nRF Connect SDK extended Kconfig which
are defined in their upstream repo and not in an `ext-root`.
This is needed so that users may remove optional modules in their
downstream manifest.
See: https://github.com/nrfconnect/sdk-nrf/pull/6080

[nrf noup] adding NCS_<module_name>_KCONFIG for NCS extended modules

---

doc/reference/bluetooth/mesh/access.rst
doc/reference/bluetooth/mesh/shell.rst
include/bluetooth/mesh/access.h
include/bluetooth/mesh/shell.h
subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/access.c
subsys/bluetooth/mesh/cfg.c
subsys/bluetooth/mesh/gatt_services.c
subsys/bluetooth/mesh/net.c
subsys/bluetooth/mesh/shell.c
tests/bluetooth/mesh_shell/src/main.c

Pulls in the following PRs from Zephyr main:
- zephyrproject-rtos/zephyr#40158
- zephyrproject-rtos/zephyr#40387
- zephyrproject-rtos/zephyr#40135
- zephyrproject-rtos/zephyr#39664
- zephyrproject-rtos/zephyr#39010
- zephyrproject-rtos/zephyr#38296
Does not include the Proxy split PR (zephyrproject-rtos/zephyr#36871), and its followup PRs.
Also does not include zephyrproject-rtos/zephyr#40109, as it's a pure feature addition that's not in Zephyr v2.7, and is not a requested feature in the nRF Connect SDK.

Bluetooth: Mesh: nRF Connect SDK v1.8 feature freeze patches

---

tests/bluetooth/tester/src/l2cap.c

Adds preprocessor ifdefs to reconfigure() in L2CAP tester application
depending on the KConfig option CONFIG_BT_L2CAP_ECRED
Fixes issue #40456
Signed-off-by: Johan Lundin <johan.lundin@nordicsemi.no>
(cherry picked from commit 403fbfcc12068d890d771bcc7bfa9352fe593baf)
Signed-off-by: Johan Lundin <johan.lundin@nordicsemi.no>

[nrf fromtree] Bluetooth: Adds preprocessor to L2CAP tester app

---

subsys/logging/log_core.c

A variable is tracking number of buffered messages. This is used
to trigger processing thread in certain cases. Counter was not
handled correctly when message was dropped. In certain cases that
can lead to hanging of log processing.
Added counter decrementation in the callback called whenever
message is dropped.
Ref. NCSIDB-630.
Cherry-picked from cbd05448fd2599e96bcafd6b4e52d7daffaca490.

[nrf fromtree] logging: Fix tracking of active messages

---

dts/arm/nordic/nrf5340_cpuappns.dtsi
dts/arm/nordic/nrf9160ns.dtsi

squash! [nrf noup] dts: choose cryptocell for entropy when available
Move these nodes outside of /soc to avoid a simple_bus_reg warning
from dtc. No functional changes expected.
NCSDK-12745
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

[nrf noup] dts: silence warning for cryptocell_sw

---

subsys/ipc/rpmsg_service/rpmsg_backend.h

Will be squashed.
Use partition manager defines instead of kconfig deduced from
devicetree for RPMSG shared memory.
Ref: NCSDK-11234

fixup! [nrf noup] tree-wide: support NCS Partition

---

subsys/fs/littlefs_fs.c

This adds a conditional that selects FLASH_AREA_ID if
partition manager is enabled so that littlefs uses the littlefs_storage
partition or the storage parition.
The littlefs_storage partition takes precedence over the storage partition.
Ref. NCSDK-11402

[nrf noup] fs: littlefs: Fix automount for partition manager

---

.github/workflows/bsim.yaml
.github/workflows/clang.yaml

Fixes isses with downstream forks, where repos names are not zephyr
Will have to be reworked after the upmerge

[nrf noup] action: clang: set the name of checkout repo to zephyr

---

.github/workflows/compliance.yml

A similar fix to #686. West update cannot import submanifests
because the repo is checked out as "sdk-zephyr". This patch set
the checkout dir to "zephyr"

squash! [nrf noup] action: clang: set the name of checkout repo to zephyr

---

boards/arm/nucleo_f767zi/doc/index.rst
doc/contribute/coding_guidelines/index.rst
doc/contribute/external.rst
doc/development_process/project_roles.rst
doc/getting_started/installation_win.rst
doc/guides/west/why.rst
samples/bluetooth/ipsp/README.rst

Use extlink for GitHub issue links in documentation.
Signed-off-by: Henrik Brix Andersen <hebad@vestas.com>
(cherry picked from commit 2c0e0a74af0c16a3ec3080645fa09e4f340283d6)

[nfr fromtree] doc: use extlink for github issue links

---

include/arch/posix/linker.ld

The function `zephyr_linker_sources()` states:
> When placing into NOINIT, RWDATA, RODATA, ROM_START, the contents of
> the files will be placed inside an output section, so assume the
> section definition is already present.
However, in the posix linker.ld template the NOINIT, RWDATA, RODATA, and
ROM_START was not placed inside a pre-defined output section, which
means that linker scripts created for native_posix when
`zephyr_linker_sources()` is used are invalid
This result in the following failure:
> /usr/bin/ld:zephyr/linker_zephyr_prebuilt.cmd:81: syntax error
> collect2: error: ld returned 1 exit status
This PR fixes this issue be predefining output sections according to
the documented behavior.

linker: update posix linker template, linker.ld

---

drivers/ieee802154/ieee802154_nrf5.c

This commit updates the ieee802154 driver to match the current feature
set of the nRF 802.15.4 radio driver for nRF53 SoCs.
(cherry picked from commit 81ea5299600e742d830426a130a49a751109cd9f)

[nrf fromtree] drivers: ieee802154: extend support for nRF53

---

tests/subsys/storage/stream/stream_flash/src/main.c

This test uses SoC's flash from offset of 64 KB which might
overlap with executable for a target
(for instance nrf52840dk_nrf52840).
This patch moves this region to 128 KB which solves the issue.
mirror of https://github.com/zephyrproject-rtos/zephyr/pull/42192
fixes NCSDK-13488

[nrf fromtree] test/subsys/storage/steram_flash: fix build size issue

---

include/net/socket_ncs.h

AT and DFU sockets have been removed from libmodem and NCS.
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>
Signed-off-by: Andreas Moltumyr <andreas.moltumyr@nordicsemi.no>

[nrf noup] net: socket_ncs: remove AT and DFU socket defines

---

.github/workflows/clang.yaml

Bring back parallel execution to the clang action. In the upstream
they went to use a single dedicated powerfull agent to run this. We
need to keep this as we have to base on agents available in github's
cloud.

[nrf noup] action: clang: parallel execution

---

modules/hal_nordic/nrf_802154/sl_opensource/platform/nrf_802154_irq_zephyr.c
west.yml

Parameter `prio` of `nrf_802154_irq_init` is now allowed to have
negative value what means use of ZLI priority or highest possible
priority if ZLIs are disabled.
Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/42355
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>

[nrf fromlist] modules: hal_nordic: nrf_802154_irq ZLI support

---

modules/mbedtls/Kconfig.tls-generic
modules/mbedtls/configs/config-tls-generic.h

-Has unsupported TLS configurations (TLS 1.0, 1.1)
-Collides with PSA configurations
-Converted Zephyr configuration MBEDTLS_TLS_VERSION_1_2
to standardized configuration MBEDTLS_SSL_PROTO_TLS1_2
-Disabled Kconfig.tls-generic specific configurations in zephyr
-Disabled usage of MBEDTLS_BUILTIN
ref: NCSDK-13503

[nrf_noup]: Disable loading of Kconfig.tls-generic

---

drivers/ieee802154/ieee802154_nrf5.c

Due to serialization restrictions radio api calls cannot be nested, any
violation of this rule leads to a deadlock. This commit fixes the bug
by transferring the nested radio api call to ot_radio_workq.
Upstream PR: zephyrproject-rtos/zephyr#42484
Signed-off-by: Lukasz Maciejonczyk <lukasz.maciejonczyk@nordicsemi.no>

[nrf fromlist] drivers: ieee802154_nrf5: fix CSL for multicore devices

---

cmake/linker/ld/target.cmake

With CMake 3.20 relative path inside DEPFILEs are treated relative to
CMAKE_CURRENT_BINARY_DIR and are transformed by CMake in its internal
dep file.
Therefore Zephyr build system must no longer add `base_name` to the
`-MT` argument for the preprocessor.

[nrf fromtree] cmake: remove base_name for dep file

---

subsys/bluetooth/host/adv.c

Previously the data was set incorrectly when the data was set in
multiple operations. It did not take the previous state into account.
Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/42639
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>

[nrf fromlist] Bluetooth: Host: Fix setting long advertising data

---

subsys/bluetooth/host/direction.c
subsys/bluetooth/host/gatt.c

Cherry-pick commits:
- revert of commit https://github.com/nrfconnect/sdk-zephyr/commit/0a1f553dc23ca9c2b42092dbba44ab0b3204990b.
- fix for wrong length of antenna identifiers for CTE RX

Bluetooth: Host: GATT and direction finding bug fixes

---

scripts/pylib/twister/twisterlib.py

This changes was introduced to this open Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/41930
First part of "short build paths" was introduced to sdk-zephyr repo in
this commit:
https://github.com/nrfconnect/sdk-zephyr/commit/ee43917f19aadae60845528d541d08561f051dc0
This fix allow to avoid situation when Twister create original "long path" build directory, before "short build path" try to create such directory and this cause an error. 
Relevant PR on `sdk-nrf` repository with changes in `west.yml` manifest in `sdk-zephyr` version:
https://github.com/nrfconnect/sdk-nrf/pull/6873
Signed-off-by: Piotr Golyzniak <piotr.golyzniak@nordicsemi.no>

[nrf fromlist] twister: short build paths - fix

---

subsys/bluetooth/host/l2cap.c

This fix a typo where incorrect member of bt_keys was used for
checking if LTK is present. This was resulting in bogus results
depending on connection role and current identity used.
This was affecting L2CAP/LE/CFC/BV-25-C qualification test case.
Fixes: #42862
Signed-off-by: ilat <ilhan.ates@nordicsemi.no>
(cherry-pick of 4fce6fb9377f000e7b3a17f50b633bafb8ecd42f)

[nrf fromtree] Bluetooth: L2CAP: Fix checking if LTK is present

---

subsys/bluetooth/host/l2cap.c

This fix a typo where incorrect member of bt_keys was used for
checking if LTK is present. This was resulting in bogus results
depending on connection role and current identity used.
This was affecting L2CAP/LE/CFC/BV-25-C qualification test case.
Fixes: #42862
Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>
Signed-off-by: ilat <ilhan.ates@nordicsemi.no>
(cherry-pick of 4fce6fb9377f000e7b3a17f50b633bafb8ecd42f)

[v2.7.99-ncs1] Bluetooth: L2CAP: Fix checking if LTK is present

---

doc/releases/release-notes-3.0.rst
subsys/bluetooth/host/att.c
subsys/bluetooth/host/iso.c

Bugs:
1) BUS FAULT can happen when a central disconnects an ISO
2) bt_conn_index asserts when disconnecting while doing service
discovery

[nrf fromtree] Bugfixes related to Bluetooth ISO and ATT

---

doc/application/index.rst

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/42876
We use a specific experimental Kconfig option when describing the
behavior of CONFIG_WARN_EXPERIMENTAL.
However, this option may not be experimental forever. This therefore
may go stale. Rather than try to keep generic documentation about
experimental options up to date with whatever the bluetooth subsystem
happens to consider experimental or not, use a placeholder CONFIG_FOO
instead of a real option.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

[nrf fromlist] doc: application: tweak experimental features text

---

.github/workflows/manifest.yml

With this setting enabled, Git credentials are not kept after checkout.
Credentials are not necessary after the checkout step, since we do not
do any further manual push/pull operations.
(cherry picked from commit 52e06334fbeabd5d764935c1fc47d7225216fff4)

ci: manifest: do not persist git credentials

---

.github/test-spec.yml
CODEOWNERS

Signed-off-by: Sebastian Wezel <sebastian.wezel@nordicsemi.no>
This PR is meant to be a starting point to create the .github/test-spec.yml
Which will work similar to the [sdk-nrf/.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)
You can add changes to the test-spec branch. I'll combine them to a single commit on Friday (18.03)

adding new .github/test-spec.yml

---

modules/hal_nordic/nrfx/nrfx_glue.h
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/nrfx_glue/bt_ctlr_used_resources.h
subsys/bluetooth/controller/ll_sw/nrf.cmake

Instead of including from nrfx_glue.h a specific Zephyr Bluetooth
controller header file that defines PPI and GPIOTE resources to be
reserved for exclusive use by the controller, include a file with
only a fixed name and expect the chosen Bluetooth controller to
provide the location of this file in include paths. This way, when
a different Bluetooth controller implementation is used downstream,
a different file can be easily pointed to.

[nrf fromtree] modules: hal_nordic: Improve reservation of resources for BT_CTLR

---

drivers/serial/uart_nrfx_uarte.c

Fixes a case for the asynchronous UART API where
only single buffer was attached to the UART, after
filling this buffer release event was trigger first
time and after disabling UART the release event was
triggered again for the same buffer.
Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>
(cherry picked from commit ba6d9139bbbda3211e0c1f65f4ccca0719f17fa5)

[nrf fromtree] drivers: uart_nrfx_uarte: Fix double Rx buffer releasing

---

doc/reference/networking/mqtt.rst
include/net/mqtt.h
subsys/net/lib/mqtt/mqtt_transport_socket_tls.c

This commit adds an extra parameter in the configuration
structure to configure native TLS support at runtime.
I found it's not necessary to cascade the change to every single library and sample since the MQTT context is always defined static, hence the `set_native_tls` parameter is `false` by default. If support for native TLS is needed, other commits can be added to address that.

[nrf noup] net: mqtt: add native TLS support

---

drivers/clock_control/nrf_clock_calibration.c

Workaround for errata 192 is unnecessary as it is applied within
nrfx_clock_calibration_start().
Fixes #43930
Cherry picked from 2a4144d06.
Ref. NCSIDB-734.
Signed-off-by: Xudong Zheng <7pkvm5aw@slicealias.com>

[nrf fromtree] drivers: clock_control: nrf_calibration: drop workaround

---

dts/arm/nordic/nrf5340_cpuapp.dtsi
dts/arm/nordic/nrf5340_cpuapp_ipc.dtsi
dts/arm/nordic/nrf5340_cpuapp_peripherals.dtsi
dts/arm/nordic/nrf5340_cpuappns.dtsi
dts/arm/nordic/nrf5340_cpunet.dtsi
samples/subsys/ipc/ipc_service/icmsg/boards/nrf5340dk_nrf5340_cpuapp.overlay
samples/subsys/ipc/ipc_service/icmsg/remote/boards/nrf5340dk_nrf5340_cpunet.overlay
samples/subsys/ipc/ipc_service/static_vrings/boards/nrf5340dk_nrf5340_cpuapp.overlay
samples/subsys/ipc/ipc_service/static_vrings/remote/boards/nrf5340dk_nrf5340_cpunet.overlay

Cleaned up the IPC configuration for nRF5340 SoC in Device Tree. This
change fixes the (simple_bus_reg) warning about the missing or empty
reg/ranges property.
This is a follow-up to commit cf6a58d.
Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>
(cherry picked from commit d550320af6adf16807105ef631d48fa45031d04d)

[nrf fromtree] dts: arm: nordic: nrf5340: clean up ipc in dts

---

subsys/bluetooth/mesh/Kconfig

squash! [nrf noup] Bluetooth: update experimental for qualification
Mesh is no longer Experimental, as it has been ready
for production since v1.7.1. Experimantal status should
not be shown while building with mesh.
Signed-off-by: Ingar Kulbrandstad <ingar.kulbrandstad@nordicsemi.no>

[nrf noup] Bluetooth: Mesh: Remove Experimental tag

---

include/zephyr/arch/arm/aarch32/cortex_m/scripts/linker.ld

If CONFIG_SECURE_BOOT is not enabled then these symbols will
not be defined.
Ref: NCSDK-6211

[nrf noup] linker: only add Sx labels if SECURE_BOOT is enabled

---

kernel/work.c

The work queue has a semi/non-standard reschedule point implemented
using k_yield(), with a check to see if the current thread is
preemptible.  Just call z_reschedule_unlocked(), it has this check
internally and is the intended API for this.
Really, this is only a half fix.  Ideally the schedule point and the
lock release should be atomic[1] via the more idiomatic
z_reschedule().  But that would take some surgery, so let's go with
the simpler cleanup first.
This also avoids having to duplicate logic that gets added to
reschedule points by an upcoming patch.
[1] So that they represent a condition variable and don't race at the
end. In this case the race is present but benign, since the only thing
we really want to know is that the queue thread gets a chance to run.
The only cost is an …

[nrf fromtree] kernel/workq: Cleanup bespoke reschedule point

---

dts/bindings/pinctrl/nordic,nrf-pinctrl.yaml
scripts/utils/migrate_includes.py
soc/arm/nordic_nrf/common/pinctrl_soc.h
tests/drivers/pinctrl/nrf/app.overlay

All includes are now prefixed with <zephyr/...>, even though the old
include paths can still be used when CONFIG_LEGACY_INCLUDE_PATH=y, an
option still enabled by default. Migrating large projects can be tedious
and time consuming. This patch provides a script that can be used to
migrate any Zephyr-based project to the new include path. It is used
like this:
python $ZEPHYR_BASE/scripts/utils/migrate_includes.py \
-p path/to/zephyr-based-project
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
(cherry picked from commit 0d18e911fc19f5bdd8da2b778735cedcb1339ac5)
The drive-mode property is nRF specific, so prefix it with nordic,,
same as the nordic,invert property.
Signed-off-by: Gerard Marull-Paretas [gerard.marull@nordicsemi.no](mailto:gerard.marull@nordicsemi.no)
(cherry …

[nrf fromtree] scripts: utils: add include migration script + pinctrl: nrf: prefix custom drive-mode property

---

include/zephyr/sys/cbprintf_internal.h

Use single fixed size on stack array instead of compile time fitting.
When compiler is optimizing it can pick smallest array but with no
optimization there is an increased stack usage.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/45575
Ref. NCSDK-15105

[nrf fromlist] lib: os: cbprintf: Reduce stack usage when no optimization

---

subsys/bluetooth/host/att.c

The L2CAP channel section is sorted lexicographically. Make sure that ATT fixed channel will be placed as the last one to ensure that SMP channel is properly initialized before bt_att_connected tries to send security request.

bluetooth: att: Fix L2CAP channel section order

---

doc/releases/release-notes-3.1.rst

... transition
The commit adds release notes on MCUMGR transition from TinyCBOR
to zcbor, and deprecation of several Kconfig options that are
no longer needed.
(cherry picked from commit 1efc400474a5237bac6e64232d33ed00cca7fbb1)

[nrf fromlist] doc/releases/3.1: Add notes on MCUMGR to zcbor

---

subsys/fs/nvs/Kconfig

The default cache size is 128, what results in plenty of conflicts
in positions calculated by the CRC8 algorithm. It is solved by
increasing cache size, as it changes used algorithm to CRC16
and reduces number of conflicts.
Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>
Commit is [nrf noup], as it modifies the code that was not yet merged to the upstream Zephyr and open PR cannot be modified due to owner vacation: https://github.com/zephyrproject-rtos/zephyr/pull/45769

subsys: nvs: Increased default NVS cache size to 512 B.

---

modules/trusted-firmware-m/CMakeLists.txt
modules/trusted-firmware-m/Kconfig.tfm

Zephyr adds a custom handler that overrides the weak function
sys_arch_reset when TF-M platform partition is enabled.
This takes away the option for the application to override the weak
definition for their platform or use-case.
Add an option that control whether this default reset handling is added
to the build.
Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/46133
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

tfm: Add option for implementation custom reset handler with TF-M

---

drivers/ieee802154/ieee802154_nrf5.c
west.yml

This PR introduces a fix for DRX window being triggered to early during
CSL. Fixes were also introduced in the nrf 802154 radio
driver, so removed the unneeded DRX_ADJUST constant.
Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/46198
Signed-off-by: Artur Hadasz <artur.hadasz@nordicsemi.no>

[nrf fromlist] drivers: ieee802154: nrf5: Fix DRX_ADJUST workaround

---

drivers/ieee802154/ieee802154_nrf5.c

This commit increases verbosity of serialization error handler for
nRF5340 application core. The handler prints the error code now.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/46254

[nrf fromlist] drivers: ieee802154: print serialization error on nRF5340

---

samples/subsys/mgmt/mcumgr/smp_svr/child_image/hci_rpmsg.conf

Added a configuration file for the HCI RPMsg child image that is necessary
for multi-core targets.
Signed-off-by: Kamil Piszczek <Kamil.Piszczek@nordicsemi.no>

[nrf noup] samples: mgmt: mcumgr: add hci_rpmsg child image config

---

samples/subsys/mgmt/mcumgr/smp_svr/src/main.c

... registration
This fixes an issue with the filesystem mcumgr being registered twice
in the sample application which resolves an issue with an endless loop
if a mcumgr handler is used which is not registered.
Signed-off-by: Jamie McCrae <jamie.mccrae@lairdconnect.com>
(cherry picked from commit ad4e9934de8614ef6115c2129a81a6ce839003b9)

[nrf fromtree] samples: subsys: mgmt: smp_svr: Fix dupicate fs mgmt

---

subsys/mgmt/mcumgr/lib/cmd/os_mgmt/src/os_mgmt.c

... value
The commit fixes incorrect value being passed as used stack
information and also prevents compilation error when
CONFIG_INIT_STACKS is n.
Upstream Commit: https://github.com/nrfconnect/sdk-zephyr/commit/550f1b096d0168ec3718b45ad2965eb607006f25

[nrf fromtree] mgmt/mcumgr/lib: Fix OS taskstat passing incorrect

---

boards/arm/nrf51dk_nrf51422/nrf51dk_nrf51422.dts
boards/arm/nrf51dongle_nrf51422/nrf51dongle_nrf51422.dts
boards/arm/nrf52833dk_nrf52820/nrf52833dk_nrf52820.dts
drivers/i2c/i2c_nrfx_twi.c
drivers/i2c/i2c_nrfx_twim.c
drivers/pinctrl/pinctrl_nrf.c
dts/bindings/pinctrl/nordic,nrf-pinctrl.yaml

*[nrf fromtree] boards: nrf: Fix sw_pwm channel definitions*
This is a follow-up to commit f301dc2382dca20c879fe2d73676fc61524e90b6.
Add missing GPIO_ACTIVE_LOW flag to sw_pwm channel definitions for
nRF51 DK and nRF51 Dongle so that the initial state of their PWM
outputs is properly set up.
Add missing sw_pwm channel definition in the nrf52833dk_nrf52820 target
that was modified in 793362ae5a9e02c94d03fbf8736cf19b473965e3 instead
of in f301dc2382dca20c879fe2d73676fc61524e90b6. Add also the pwm-led0
alias for its PWM LED so that it can be used with standard samples.
*[nrf fromtree] drivers: pinctrl_nrf: Use S0D1 drive by default for TWI/TWIM pins*
The default S0S1 drive setting is not suitable for TWI/TWIM pins.
Override it with S0D1 as for some SoCs (e.g. nRF52833) without
this the …

[backport-v2.0][nrf fromtree] Several bug fixes related to pinctrl and updated PWM API

---

drivers/sensor/adxl362/adxl362.h
drivers/sensor/adxl362/adxl362_trigger.c
include/zephyr/drivers/sensor.h
samples/sensor/adxl362/src/main.c

This patch modifies the ADXL362 driver to use the new
SENSOR_TRIG_MOTION trigger for activity detection
and SENSOR_TRIG_STATIONARY for inactivity detection.
Upstream commit: [#1c1c72](https://github.com/zephyrproject-rtos/zephyr/commit/1c1c72ea08812c1e19671c1dbf47fd88aaf35ef9)

[nrf fromtree] ADXL362: Add separate activity/inactivity triggers

---

drivers/sensor/adxl362/adxl362.c

This patch extends the adxl362 driver by adding an option
to change the inactivity detection timeout at runtime.
(cherry picked from commit 3d2b04c9a8a76b7e30dbb4e536821a89760f199a)

[nrf fromtree] ADXL362: add dynamic inact time setting

---

doc/build/dts/api/api.rst
drivers/net/Kconfig
drivers/net/ppp.c

Move from using Kconfig NET_PPP_UART_NAME to a devicetree chosen
property ("zephyr,ppp-uart").  This is similar to a number of other
functions like "zephyr,shell-uart" or "zephyr,bt-uart".
As part of this we rework the init code a little to use
DEVICE_DT_GET for the modem gsm-ppp case.
(cherry picked from commit 82c65315d332f3bd2f05ca20fc8126d26123f1a4)

[nrf fromtree] drivers: ppp: Move to DTS for uart device

---

boards/arm/nrf51dk_nrf51422/nrf51dk_nrf51422.dts
boards/arm/nrf51dongle_nrf51422/nrf51dongle_nrf51422.dts
boards/arm/nrf52833dk_nrf52820/nrf52833dk_nrf52820.dts
drivers/i2c/i2c_nrfx_twi.c
drivers/i2c/i2c_nrfx_twim.c
drivers/pinctrl/pinctrl_nrf.c
dts/bindings/pinctrl/nordic,nrf-pinctrl.yaml

*[nrf fromtree] boards: nrf: Fix sw_pwm channel definitions*
This is a follow-up to commit f301dc2382dca20c879fe2d73676fc61524e90b6.
Add missing GPIO_ACTIVE_LOW flag to sw_pwm channel definitions for
nRF51 DK and nRF51 Dongle so that the initial state of their PWM
outputs is properly set up.
Add missing sw_pwm channel definition in the nrf52833dk_nrf52820 target
that was modified in 793362ae5a9e02c94d03fbf8736cf19b473965e3 instead
of in f301dc2382dca20c879fe2d73676fc61524e90b6. Add also the pwm-led0
alias for its PWM LED so that it can be used with standard samples.
*[nrf fromtree] drivers: pinctrl_nrf: Use S0D1 drive by default for TWI/TWIM pins*
The default S0S1 drive setting is not suitable for TWI/TWIM pins.
Override it with S0D1 as for some SoCs (e.g. nRF52833) without
this the …

[nrf fromtree] Several bug fixes related to pinctrl and updated PWM API

---

drivers/sensor/adxl372/Kconfig

This patch adds names to the KConfig choices of the ADXL372 driver.
(cherry-picked from commit d8e0dd1804f162c44810d43077ec2374ebe8f40f)

[nrf fromtree] ADXL372: add names for KConfig choices

---

scripts/set_assignees.py

Deal with exceptions that happen when a user does not exist on GH.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
(cherry picked from commit 60271524087bb4382c8b4db0f2e17a87e4120065)

[nrf fromtree] scripts: set_assignee: handle exceptions

---

include/zephyr/net/socket_ncs.h

This commit aligns some RAI related socket options with modemlib's.

[nrf noup] include: net: align RAI socket options

---

subsys/mgmt/mcumgr/CMakeLists.txt
subsys/mgmt/mcumgr/Kconfig
subsys/mgmt/mcumgr/bootutil_hooks/nrf53_hooks.c

One commit: adds [nrf noup] patch to mcumgr that provides bootutil hooks, which simulate the non-accessible slot-1/primary slot.

Fixes needed for removal of flash NOP device from sdk-nrf

---

subsys/bluetooth/host/Kconfig.gatt
subsys/bluetooth/host/gatt.c

This introduces a new option that allows the user to disable the
subscription checking when notifying or indicating.
Some users might have use-cases where they would like to send notifications
or indications without the peer having to go through the subscription
process, as that is allowed by the Bluetooth specification.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
(cherry picked from commit fae5dd36431106c328e000d676f1a3d8d987275f)

[nrf fromtree] Bluetooth: gatt: allow disabling subscription enforcement

---

subsys/bluetooth/audio/unicast_client.c

The unicast_client_pacs_avail_ctx_notify_cb had a direction
check that was a leftover copy from the location notification.
However the context notification is always for both sink and
source, and thus does not need any direction checks (in fact
the dir variable was unused).
Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

[nrf fromtree] Bluetooth: Audio: Fix unicast_client avail ctx dir check

---

subsys/bluetooth/mesh/health_cli.c

Swaps response scheme for Fault_test command so that it aligns with description of the documentation.
Swaps response scheme for Fault_get & Fault_clear command so that it aligns with description of the documentation.

[nrf fromtree] Bluetooth: Mesh: Health cli fixes

---

subsys/logging/CMakeLists.txt
subsys/shell/Kconfig

Due to missing dependencies log_output module was not enabled when used with shell.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/49448
Ref. NCSDK-16574

logging: shell: Fix missing timestamp in log messages on shell backend

---

subsys/net/lib/lwm2m/lwm2m_engine.c
subsys/net/lib/lwm2m/lwm2m_rd_client.c

Fixed unstable thread state read for detetect engine thread
state.
Fixed engine missing socket conrext add.
lwm2m resume now do update also from network error state
Signed-off-by: Juha Heiskanen <juha.heiskanen@nordicsemi.no>
Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/49675

[nrf fromlist] net: lwm2m: Fix LwM2M pause and resume

---

scripts/ci/check_compliance.py

Merged:  https://github.com/zephyrproject-rtos/zephyr/pull/49418
nrfxlib and lwm2m teams are blocked without compliance script upgrades now. :/
- [nrf fromtree] scripts/ci/check_compliance.py: Allow to run w/ZEPHYR_BASE
- [nrf fromtree] scripts: compliance: Remove unused variable
- [nrf fromtree] scripts: compliance: Complete transition to junitparser v2
- [nrf fromtree] scripts: compliance: Clean up logging
- [nrf fromtree] scripts: compliance: Tiny cleanup for -c
- [nrf fromtree] scripts: compliance: Remove unused command-line args
- [nrf fromtree] scripts: compliance: Add commit range info output

[nrf fromtree] Improvements to scripts/ci/check_compliance.py

---

boards/arm/qemu_cortex_m0/nrf_timer_timer.c
drivers/counter/counter_nrfx_timer.c
drivers/display/display_nrf_led_matrix.c
soc/arm/nordic_nrf/common/soc_secure.c
soc/arm/nordic_nrf/common/soc_secure.h
soc/arm/nordic_nrf/nrf53/soc.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/debug.h
tests/drivers/timer/nrf_rtc_timer/src/main.c

With the release of nrfx2.9 some API become deprecated
(see https://github.com/NordicSemiconductor/nrfx/blob/v2.9.0/CHANGELOG.md).
This PR replaces deprecated API with suggested in CHANGELOG
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/49581

[nrf fromlist] Replace nrfx deprecated API for new one 

---

subsys/net/ip/Kconfig.stats

Until we merge with Zephyr's Wi-Fi management, use nRF Wi-Fi
management for Wi-Fi stats.

[nrf noup] wifi_stats: Use nRF Wi-Fi management

---

drivers/flash/soc_flash_nrf_ticker.c
subsys/bluetooth/controller/ll_sw/ull_adv_sync.c

When periodic advertising with chaining is re-enabled after
changing interval or just re-enabled then the chain PDUs
where not duplicated causing the LLL to assert detecting the
presence of aux pointer but no linked chain PDUs.
Fix usage fault due to spurious ticker timeout expiry post
enqueuing of ticker stop operation.
Use ticker operation callback to handle completion of ticker
stop operation and then give the semaphore to thread to
notifying the completion of flash operation.
Ticker stop callback are executing in ULL_HIGH priority,
correct the value to 1U instead of 0U which is for LLL
execution context of the Bluetooth Controller.
Signed-off-by: Vinayak Kariappa Chettimada <vich@nordicsemi.no>

[nrf fromlist] Bluetooth: Controller: Periodic Advertising Restart assertion and Flash driver assertion fix

---

subsys/bluetooth/host/Kconfig.l2cap

BT_L2CAP_ECRED is not marked as experimental upstream and we qualify it
downstream.
To be squashed with 1e8c632358761d97cf2d659eb9fdc316b4558547 in the next
upmerge.
Signed-off-by: Herman Berget <herman.berget@nordicsemi.no>

[nrf noup] Bluetooth: BT_L2CAP_ECRED is no longer experimental

---

boards/arm/thingy53_nrf5340/thingy53_nrf5340_common.dts

Added aliases for the button and LED gpio pin which might be used by the MCUboot.
Aliases are required for MCUboot as we don't have labels anymore for GPIOs.
GPIO is used for instance for entering to the serial recovery mode.
upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/50163

[nrf fromlist] boards/arm/thingy53_nrf5340: Add mcuboot's gpio aliases

---

Kconfig.zephyr
lib/os/spsc_pbuf.c
subsys/testsuite/Kconfig.defconfig
subsys/testsuite/ztest/src/ztress.c
tests/lib/spsc_pbuf/src/main.c

Fixing race which was found when running `icmsg` ipc service sample (merged upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/49345).
https://github.com/zephyrproject-rtos/zephyr/pull/49345/commits/e632fdfdc3b15f0ab5d30154882a133f8b05f3dc
https://github.com/zephyrproject-rtos/zephyr/pull/49345/commits/014c7f9a4d2b3041dc29f34d2f0d513ba1a6aa68
https://github.com/zephyrproject-rtos/zephyr/pull/49345/commits/6a6a74101d3b4f4f067d9ab0ce949ee5f9bcfe6a
https://github.com/zephyrproject-rtos/zephyr/pull/49345/commits/f12b5a07f62cc8ce094e61bc1b598f16ca41fd39
Fixing failure of `zephyr/tests/lib/spsc_pbuf` seen on non-secure targets (e.g., nrf91_ns). Failure was cause by use of random number generator which cannot be called from an interrupt context (upstream PR: …

lib: os: spsc_pbuf: Fixing race and test failure on non-secure targets

---

doc/conf.py
include/zephyr/drivers/spi.h
scripts/requirements-doc.txt

https://github.com/zephyrproject-rtos/zephyr/pull/48947
Update to Sphinx 5.x, also update breathe since version 4.34 is the
first to officially support Sphinx 5.x.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>

[nrf fromtree] Python tool version change: Breathe & Spinx

---

.github/workflows/bluetooth-tests.yaml
.github/workflows/clang.yaml
.github/workflows/codecov.yaml
.github/workflows/errno.yml
.github/workflows/footprint-tracking.yml
.github/workflows/footprint.yml
.github/workflows/twister.yaml

Because the clang workflow is run on `pull_request_target`, it needs to be updated in the tree so that clang checks can be run successfully for https://github.com/nrfconnect/sdk-zephyr/pull/916 (and use `zephyr-sdk-0.15.0`). Hence the three commits included in this PR need to be cherry-picked before the upmerge.

[nrf fromtree] Update clang workflow

---

subsys/net/ip/net_private.h

When using nRF Wi-Fi management it uses the net management events with information, but the size of the events is not enough to hold the Wi-Fi events as the proper size is defined only for Zephyr's Wi-Fi management.
Use the proper size for both nRF and Zephyr's Wi-Fi management.
Note: If CONFIG_NET_DHCPV4 is enabled, then this works, as size is now large enough for Wi-Fi management events.

[nrf noup] net: ip: Fix nRF Wi-Fi management events

---

subsys/net/ip/Kconfig.stats
subsys/net/ip/net_private.h
subsys/net/l2/wifi/wifi_mgmt.c

If WPA supplicant is enabled at build time, then use the WPA supplicant APIs, else use offload driver APIs.

net: wifi: Add support for WPA supplicant

---

subsys/net/ip/net_mgmt.c
subsys/net/ip/net_private.h

When DHCPv4 is enabled it is the highest size, so, use that as a first choice. Also, Update the stale comment.

[nrf fromtree] net: mgmt: Fix the maximum event size calculation

---

boards/arm/bl5340_dvk/Kconfig
boards/arm/nrf5340dk_nrf5340/Kconfig
boards/arm/thingy53_nrf5340/Kconfig
modules/trusted-firmware-m/CMakeLists.txt
modules/trusted-firmware-m/Kconfig.tfm
modules/trusted-firmware-m/Kconfig.tfm.partitions
soc/arm/nordic_nrf/Kconfig
soc/arm/nordic_nrf/common/CMakeLists.txt
soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf53/soc.c

Add option to enable the SFN model when building TF-M.
The SFN model will eventually replace the Library model.
Change the default model to be IPC, which follows the default
configuration of TF-M.
Allow building for nRF non-secure and TF-M enabled without having the
platform partition enabled.

[nrf fromlist] TF-M: Add option to enable SFN model 

---

.github/workflows/clang.yaml

squash! [nrf noup] ci: clang: parallel execution
zephyr_runner is upstream's proprietary agent inaccessible outside of upstream's CI. Use ubuntu-latest instead.

[nrf noup] ci: clang: Use ubuntu-latest instead of zephyr_runner

---

.github/workflows/clang.yaml

squash! [nrf noup] ci: clang: parallel execution
The fix for zephyr path is no longer needed after
37160d6e3bd733e42b403aeb8016def5806b6458 was reverted and is causing failures.

[nrf noup] ci: clang: Remove incorrect zephyr path

---

subsys/net/lib/lwm2m/Kconfig
subsys/net/lib/lwm2m/lwm2m_engine.c
subsys/net/lib/lwm2m/lwm2m_message_handling.c

Use Zephyr internal zsock_ calls to remove dependency to NET_SOCKETS_POSIX_NAMES.

[nrf fromtree] net: lwm2m: use zsock_ functions

---

subsys/net/ip/net_private.h
subsys/net/ip/utils.c

Instead of doing a 1-complement addition for every 16-bit word, process 32-bit words and handle the 1-complement addition at the end.
This work is a colaboration with Diego Pino García. The algorithm is inspired by:
https://blogs.igalia.com/dpino/2018/06/14/fast-checksum-computation/
Signed-off-by: Sjors Hettinga <s.a.hettinga@gmail.com>

[nrf fromtree] net: ip: Speed up the IP/UDP/TCP checksum calculation

---

subsys/bluetooth/common/Kconfig

Make discaradable buffer size fit extended adv reports that has only received legacy adv pdus.
This is needed since this PR is https://github.com/nrfconnect/sdk-nrf/pull/9072 will mark extneded adv reports with legacy data in them discardable.
Fixes #51650
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>

[nrf noup] bluetooth: increase discaradable buffer size

---

scripts/pylib/twister/twisterlib/testplan.py
scripts/tests/twister/test_testplan_class.py

During the recent overhaul, some code was left retrieving cases the old way.
Fixes #48897
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
(cherry picked from commit f28a8d224098e3fcbccd9ef5e6597502d81a1526)

[backport-v2.1][nrf fromtree] twister: fix bug retrieving subtests

---

subsys/net/l2/wifi/wifi_shell.c

When security type is not given but instead MFP is given, MFP setting will be considered as security type, this is because both are optional and no way to distinguish them easily.
Make security type mandatory for MFP selection, this way we either assume defaults for both security type and MFP or explicitly ask user for both. Reword the help text to reflect this.

[nrf fromtree] net: wifi: Fix MFP when security type is not given

---

Kconfig.zephyr

squash! [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
Ref: NCSDK-11993

[nrf noup] kconfig: remove downstream patch for offset

---

subsys/bluetooth/host/adv.c
subsys/bluetooth/host/hci_core.h
subsys/bluetooth/host/id.c
subsys/bluetooth/host/id.h

Fix RPA timeout expiration when BT_EXT_ADV has been enabled.
Always invalidate the device RPA on RPA timeout.
This RPA is used by the scan roles, and the advertiser that was started
using the bt_le_adv_start API.
Call the RPA expire callback only on advertising sets that are enabled
and not being limited by a timeout and not using the identity address.
On RPA timeout always invalidate the RPA of advertising sets that are
disabled.
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51208
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51228
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51247
manifest pr: https://github.com/nrfconnect/sdk-nrf/pull/9404

[backport] Bluetooth: host: Fix RPA timeout expiration

---

include/zephyr/net/wifi.h
include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_mgmt.c
subsys/net/l2/wifi/wifi_shell.c

Add support for configuring power-save in Wi-Fi chipsets, supports Legacy, WMM and TWT.
(cherry picked from commit e7bd2e4af8916bffe05e64a8c1f16f748997f4ba)

[nrf fromlist] net: wifi_mgmt: Add support for power save configuration

---

drivers/ipm/ipm_nrfx_ipc.c
drivers/mbox/mbox_nrfx_ipc.c
modules/hal_nordic/nrfx/nrfx_config.h

Pulls alignment to nrfx 2.10 API in IPM and MBOX drivers shims

[nrf fromtree] nrfx: align implementation to nrfx 2.10 API

---

include/zephyr/mgmt/mcumgr/smp.h
subsys/mgmt/mcumgr/lib/cmd/img_mgmt/include/img_mgmt/img_mgmt.h
subsys/mgmt/mcumgr/smp.c
subsys/mgmt/mcumgr/transport/Kconfig
subsys/mgmt/mcumgr/transport/smp_bt.c
subsys/mgmt/mcumgr/transport/smp_dummy.c
subsys/mgmt/mcumgr/transport/smp_shell.c
subsys/mgmt/mcumgr/transport/smp_uart.c
subsys/mgmt/mcumgr/transport/smp_udp.c

Fixes issues with the Bluetooth mcumgr transport which have resulted in issues in matter samples and deadlocks. Have pulled in all previous mcumgr changes to prevent merge issues.

Update mcumgr with latest zephyr additions and Bluetooth transport issues

---

boards/arm/thingy52_nrf52832/thingy52_nrf52832.dts

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/52504
The regulator defines non-zero `startup-delay-us`, so `regulator-fixed-sync` cannot be used.

[nrf fromlist] boards: thingy52_nrf52832: Remove regulator sync from vdd-pwr-ctrl

---

boards/arm/thingy53_nrf5340/pm_static_thingy53_nrf5340_cpuapp.yml
boards/arm/thingy53_nrf5340/pm_static_thingy53_nrf5340_cpuapp_ns.yml

Change introduces common static Partition Manager configuration.
Jira: NCSDK-18033

[nrf noup] boards: thingy53_nrf5340: Add common partition map

---

modules/mbedtls/Kconfig.psa

-Improves prompt-less configurations used to ensure specific features are turned off or on
in PSA builds. 
-Fixes typo on asymmetric encryption/signing
ref: NCSDK-17840

mbedtls: Fix typos and improve prompt-less configuration 

---

subsys/bluetooth/audio/mcc.c

When MCC disconnected, it would memset the entire instance. This causes issues, because the subscription parameters would also be memset, causing the `notify` callback to be set to NULL. If this was done as part of a disconnect, the GATT layer would attempt to call the notify callback as part of cleaning up the ACL, but if the callback was set to NULL (from the memset) this caused a fatal error.
Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>
(cherry picked from commit e80c70fd051da70afc4bec8203e82c0265d1ca99)

[nrf fromtree] Bluetooth: Audio: Fix MCC disconnect issue

---

subsys/logging/Kconfig.mode

This changes the minimal logging Kconfig to select printk rather than imply it, this is because if someone turns printk off, minimal footprint logging does not work, therefore it needs to be a requirement.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/52745
Fixes NCSDK-18426

[nrf fromlist] logging: minimal: Change imply to select for printk

---

.github/workflows/coding_guidelines.yml
.github/workflows/compliance.yml
.github/workflows/doc-build.yml
.github/workflows/doc-publish-pr.yml
.github/workflows/doc-publish.yml

commit aea5f90d7dcad14695218aae49d37827b416a9cd
[nrf fromtree] ci: compliance: Use Ubuntu 20.04 runner image
This commit updates the compliance check workflow to use a specific
runner image version, ubuntu-20.04, instead of the latest version in
order to prevent any potential breakages due to the 'latest' version
change by GitHub.
commit 7d8541f05e92c4de8e497ccc220794e2d2493e60
[nrf fromtree] ci: doc: Use Ubuntu 20.04 runner image
This commit updates the documentation build and publish workflows to
use a specific runner image version, ubuntu-20.04, instead of the
latest version in order to prevent any potential breakages due to the
'latest' version change by GitHub.
commit 65b0b52715d67967681023651001ace6ac46272c
[nrf fromtree] ci: coding_guidelines: Use Ubuntu 20.04 runner image
This …

Backport: lock the github action runner version to 20.04

---

subsys/bluetooth/host/adv.c
subsys/bluetooth/host/hci_core.h
subsys/bluetooth/host/id.c
subsys/bluetooth/host/id.h

Fix RPA timeout expiration when BT_EXT_ADV has been enabled.
Always invalidate the device RPA on RPA timeout.
This RPA is used by the scan roles, and the advertiser that was started
using the bt_le_adv_start API.
Call the RPA expire callback only on advertising sets that are enabled
and not being limited by a timeout and not using the identity address.
On RPA timeout always invalidate the RPA of advertising sets that are
disabled.
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51208
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51228
Fixes: https://github.com/zephyrproject-rtos/zephyr/issues/51247
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/9405

[backport 3.1.99-ncs1] Bluetooth: host: Fix RPA timeout expiration

---

samples/tfm_integration/psa_crypto/README.rst

The sample is requesting an initial attestation token, which requires running the provisioning sample before, so the device has the needed key material programmed.
This updates the documentation to make users aware of this and as the provisioning sample is in sdk-nrf, a noup is used.
Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

[nrf noup] Update doc of tfm/psa_crypto sample

---

boards/arm/thingy53_nrf5340/Kconfig.defconfig
boards/arm/thingy53_nrf5340/thingy53_nrf5340_common.dts

Change enables MCUboot bootloader by default to allow programming samples and applications without external programmer (using MCUboot serial recovery).
Jira: NCSDK-18263

[nrf noup] boards: thingy53_nrf5340: Enable MCUboot by default

---

boards/arm/actinius_icarus/Kconfig.defconfig
boards/arm/actinius_icarus_bee/Kconfig.defconfig
boards/arm/actinius_icarus_som/Kconfig.defconfig

Enable TF-M by default for Actinius nrf9160-based NS boards.
This is based on https://github.com/nrfconnect/sdk-zephyr/commit/2ede29c77a7a240aca62a06831504961136c27d3 which is missing the nrf9160-based boards from Actinius. Needed for building the nrf samples from SDK v2.1.x onwards
Signed-off-by: Alex Tsamakos <alex@actinius.com>

[nrf noup] boards: Enable TF-M by default for Actinius NS boards

---

drivers/serial/uart_nrfx_uarte.c

Fix the driver so that after a call to uart_rx_disable() it does not allow re-enabling RX until the UART_RX_DISABLED is generated (what means that the disabling procedure is complete). Otherwise, it is possible that the RXTO event from the previous RX is handled right after a new RX is started, and the RX buffer pointer gets corrupted in the `rx_flush()` function.
(cherry picked from commit c984a343afdb06abb7cf8cca03c00eacdf88675e)
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>

[nrf fromtree] drivers: uart_nrfx_uarte: Prevent re-enabling RX until UART_RX_DISABLED

---

.github/workflows/compliance.yml

When merging a single commit we should be using "--commit" option of gitlint as per [1] from 0.9.0 "--commits" doesn't work for single commit causing gitlint to lint all commits in the repo.
FYI, [2] fixes this issue, but it is not merged yet.
[1] - https://github.com/jorisroovers/gitlint/blob/main/CHANGELOG.md#v090-2017-12-03 [2] - https://github.com/jorisroovers/gitlint/pull/412

fixup: [nrf noup] ci: NCS-specific CI tweaks

---

subsys/net/l2/ppp/lcp.c
subsys/net/l2/ppp/ppp_internal.h
subsys/net/l2/ppp/ppp_l2.c

A follow up to commit 1d7a077e11 - apparently the PPP interface should not be brought entirely down internally, as this can break further communication with the host. Because of that, reintroduce functionality that used to be covered by net_if_carrier_down() (which basically skips the L2 enable(false) call), but limited to PPP scope only.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/53828

[nrf fromlist] net: ppp: Fix PPP connection with host

---

include/zephyr/net/openthread.h
subsys/net/l2/openthread/openthread.c

Add a new callback list structure for state change information.
These APIs are meant to eventually replace the single callback API
provided by openthread_set_state_changed_cb().
This will allow multiple users to gain information about
OpenThread stage changes.
Note CONFIG_OPENTHREAD_MAX_STATECHANGE_HANDLERS
with OpenThread's otSetStateChangedCallback() API can also be
used to enable registration of multiple callbacks of this type but this
cannot be modified if a certified OpenThread binary is used in the
build.
Signed-off-by: Nick Ward <nick.ward@ftpsolutions.com.au>
(cherry picked from commit 4b555306437394574e3a88a38541e36895317561)

[nrf fromtree] net: openthread: Add state change callback list

---

include/zephyr/bluetooth/mesh/msg.h
subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/access.c
subsys/bluetooth/mesh/adv.c
subsys/bluetooth/mesh/adv.h
subsys/bluetooth/mesh/adv_ext.c
subsys/bluetooth/mesh/app_keys.c
subsys/bluetooth/mesh/cdb.c
subsys/bluetooth/mesh/cfg_cli.c
subsys/bluetooth/mesh/friend.c
subsys/bluetooth/mesh/health_cli.c
subsys/bluetooth/mesh/main.c
subsys/bluetooth/mesh/net.h
subsys/bluetooth/mesh/shell/health.c
subsys/bluetooth/mesh/shell/shell.c
subsys/bluetooth/mesh/subnet.c

Mesh fixes
- Stop scanner before resetting mesh
- Invalidate pending entries before calling settings API
Friendship fixes and improvement
- Separate adv tag/set for friend
- Config opt for friend adv latency
- Add extra flag to control seg msg in frnd queue
- Remove illegal use of NET_BUF_FRAG in friend.c"

Upstream fixes for mesh and mesh friendship

---

doc/releases/release-notes-3.3.rst
include/zephyr/bluetooth/bluetooth.h
include/zephyr/bluetooth/hci.h
subsys/bluetooth/host/scan.c

allow disabling reports (synchronise but don't generate sync reports) and allows enabling sync reporting with filtering of duplicates. the default option remains to establish sync, with sync reports, but without duplicate filtering.
Signed-off-by: Raphael Treccani-Chinelli <raphael.treccani@nordicsemi.no>
(cherry picked from commit 3e937da264c30350928e440ec9664a1890fdd0aa)
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>

[nrf fromtree] bluetooth: host: Added extra options to PAST subscribe

---

subsys/net/l2/wifi/wifi_mgmt.c

Use z_wpa_supplicant as the name space instead of zephyr_supp.

Rename the namespace

---

subsys/net/ip/net_pkt.c
tests/net/net_pkt/src/main.c

For socket families that are niether INET/INET6 e.g., PACKET, we cannot estimate header length, so, if the payload is zero as well, networking stack drop the packet.
Instead, allow for zero header + payload packets and let L2 take care of handling them, for some L2's this is still a valid frame.
E..g, In case of Wi-Fi this is sent as 802.11 Header + LLC Header (no payload).
Add unittests for both AF_INET + Zero payload and AF_PACKET + Zero payload.

[nrf fromlist] net: pkt: Allow zero payload for non-IPv4/v6 frames

---

samples/bluetooth/hci_rpmsg/src/main.c

This instance might be shared by other users that may have opened it earlier in the boot chain.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
(cherry picked from commit 5222691b7f5562555b74112d4fe1be0f5955ef60)

[nrf fromtree] Samples: Bluetooth: ignore -EALREADY when opening ipc instance

---

subsys/bluetooth/controller/Kconfig

It is possible to do PAST as advertiser without support for periodic sync.
Fixes #54613.
Signed-off-by: Herman Berget <herman.berget@nordicsemi.no>
(cherry picked from commit cc9d2102f2c2e8d3001c846f7a9f7f524490bb5f)
Signed-off-by: Herman Berget <herman.berget@nordicsemi.no>

[nrf fromtree] Bluetooth: Fix enabling PAST as advertiser

---

subsys/net/ip/dhcpv4.c
subsys/net/ip/ipv6_mld.c
subsys/net/lib/config/init.c

Requested for NCS 2.3.0 by @krish2718

[nrf fromtree] net: config: Unify the init behaviour when timeout is enabled and not

---

include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_mgmt.c
subsys/net/l2/wifi/wifi_shell.c

Add support for configuring power save timeout in Wi-Fi chipsets. Changes to configure power save inactivity timer.
Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>

net: wifi_mgmt: Add support for power save timeout configuration

---

subsys/net/l2/wifi/wifi_shell.c

Display power save status correctly.
Signed-off-by: Ajay Parida <ajay.parida@nordicsemi.no>
(cherry picked from commit 057e2fc59c522ceffc7ef915cfac877976df6fc6)

[nrf fromtree] net: wifi_shell: Display correct power save status

---

subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/adv_ext.c
subsys/bluetooth/mesh/lpn.c

Friend's replies on LPN's polls do not assume randomization in advertiser. Zero randomization will help to optimize time when LPN keeps receiving window open and save power.
Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>

[nrf noup] Bluetooth: Mesh: zero randomization for friend's adv

---

boards/arm/thingy53_nrf5340/pm_static_thingy53_nrf5340_cpuapp_ns.yml

The tfm_nonsecure partition must be SPU region aligned, therefore the size of the tfm partition must be reduced by the size of the mcuboot_pad partition when TF-M is used in combination with MCUBoot.
Ref: NCSDK-19515
Signed-off-by: Markus Swarowsky <markus.swarowsky@nordicsemi.no>

[nrf noup] boards: thingy53_nrf5340: Change tfm partition size

---

subsys/settings/src/settings_init.c

Multiple components may use the settings subsystem, so ensure settings_subsys_init() is thread safe.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/54943

[nrf fromlist] settings: Make settings_subsys_init() thread safe

---

subsys/net/l2/ethernet/arp.c
subsys/net/l2/ethernet/arp.h
subsys/net/l2/ethernet/ethernet.c

In the case of no ARP entry, the incoming packet is added to the ARP's pending queue, while ARP is being resolved. Here a reference is taken by the ARP layer to the packet to avoid it being freed, but the Ethernet immediately puts down the reference and send the ARP packet to the driver.
If the ARP request fails for some reason, L2 returns failure to net_if which then puts down the reference and the packet will be freed as the reference count is now zero.
But the packet is still in the ARP's pending queue and after timeout ARP will put down the reference causing double free bus fault (double free message is only seen if the CONFIG_NET_PKT_LOG_LEVEL_DBG is enabled, so, a bit hard to debug.
Fix this but not putting down the reference in Ethernet that was taken by ARP and let ARP timeout …

[nrf fromlist] net: l2: ethernet: Fix double free

---

subsys/bluetooth/audio/broadcast_sink.c

Fixes a bug where we cleanup the broadcast sink without properly terminating the BIG sync first.
(cherry picked from commit 17b7854961b46140d1f2c686585e824102d1e9dd)

[nrf fromtree] Bluetooth: Audio: Fix for PA sync in broadcast sink

---

subsys/bluetooth/host/scan.c

[nrf fromtree] Cherry-pick requested by buildsquad. Hopefully it fixes an unstable test result. This PR contains only one of the commits in the downstream PR.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/54074
This changes the periodic scanner to drop periodic adv reports with incomplete data. This avoids incorrect data being sent to application in the case where the periodic adv data is not successfully received by the scanner.
Fixes zephyrproject-rtos#54072
Signed-off-by: Pierce Lowe <pierce.lowe@nordicsemi.no>
(cherry picked from commit a7c1c27e38dd8bb964730cf440d8c6f9091cf899)

[nrf fromtree] bluetooth: host: drop incomplete data in periodic scanner

---

modules/openthread/platform/diag.c

Remove `#include "utils/code_utils.h"` and macros connected with it. File was incorrectly included in `diag.c` as it is OpenThread's header used for examples only.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/55095

[nrf fromlist] modules: openthread: remove `code_utils.h` include

---

drivers/timer/nrf_rtc_timer.c
tests/drivers/timer/nrf_rtc_timer/src/main.c

Cherry-pick a set of upstream commits that fix a problem in the system timer driver (nrf_rtc_timer) that in specific conditions the COMPARE event for a scheduled timeout was not handled properly and in consequence the timeout expired with an additional delay of 512 seconds, i.e. after the RTC overflowed.

[nrf fromtree] nrf_rtc_timer fixes related to missed timeout expirations

---

arch/arm/Kconfig
arch/arm/core/aarch32/cpu_idle.S
drivers/entropy/entropy_nrf5.c
include/zephyr/arch/arm/aarch32/misc.h
soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf53/soc.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/cpu.h
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ecb.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c

Cherry-pick a set of upstream commits to get the workaround for nRF53 anomaly 160 in NCS.

[nrf fromtree] soc: nrf53: Add workaround for anomaly 160

---

Jenkinsfile
arch/arm/Kconfig
arch/arm/core/aarch32/cpu_idle.S
drivers/entropy/entropy_nrf5.c
include/arch/arm/aarch32/misc.h
soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf53/soc.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/cpu.h
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ecb.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c

Cherry-pick a set of upstream commits to get the workaround for nRF53 anomaly 160 in NCS 1.9.

[backport-v1.9][nrf fromtree] soc: nrf53: Add workaround for anomaly 160

---

.github/workflows/doc-build.yml

New LaTeX Docker image (Debian based) uses Python 3.11. On Debian
systems, this version does not allow to install packages to the system
environment using pip.  Use a virtual environment instead.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/55137

ci: doc-build: fix PDF build

---

subsys/bluetooth/mesh/adv_ext.c

Fixes issue where randomness can be removed for advertising sets that have to handle other adv types than the BT_MESH_FRIEND_ADV tag type.

[nrf noup] Bluetooth: Mesh: Fix adv randomness bug

---

arch/arm/Kconfig
arch/arm/core/aarch32/cpu_idle.S
drivers/entropy/entropy_nrf5.c
include/zephyr/arch/arm/aarch32/misc.h
soc/arm/nordic_nrf/nrf53/CMakeLists.txt
soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf53/soc.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/cpu.h
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/ecb.c
subsys/bluetooth/controller/ll_sw/nordic/hal/nrf5/radio/radio.c

Cherry-pick a set of upstream commits to get the workaround for nRF53 anomaly 160 in NCS 2.1.

[backport-v2.1][nrf fromtree] soc: nrf53: Add workaround for anomaly 160

---

.github/workflows/assigner.yml
.github/workflows/manifest.yml

This series updates the pull request assigner and manifest workflows to use the Ubuntu 22.04 virtual environment.
Hotfix for the following pyopenssl error due to the outdated distro-provided Python packages:
```
Traceback (most recent call last):
File "/home/runner/work/_actions/zephyrproject-rtos/action-manifest/a6d0c6e52bbbb7d6df23ceb42842edcb4582b8dc/action.py", line 17, in <module>
import requests
File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
from urllib3.contrib import pyopenssl
File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
import OpenSSL.SSL
File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import crypto, SSL
File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", …
```

[nrf fromtree] ci: assigner, manifest: Use ubuntu-22.04 virtual environment

---

west.yml

Update Zephyr fork of MCUboot to revision:
1558e7ab0aadb4eac11f03befb5ccd3fa3f0aafe
Brings following Zephyr relevant fixes:
- 1558e7ab boot: zephyr: remove stm32 watchdog defines
- 4420bb66 boot: zephyr: setup watchdog
- 393af79e boot_serial: Update zcbor files from zcbor 0.7.0
- a95a41b3 boot: bootutil: loader: Let image version comparison use build number
- f7d8660e boot_serial: Fix include paths for zephyr builds
- c7835371 bootutil: Add FIH for ED25519 sig verification
- 186ac885 bootutil: Fix FIH return type for EC256
- 5397c13d zephyr: serial_recovery: Fix broken CDC device selection
- 918da26a bootutil: Provide boot_set_next function
(cherry picked from commit af2576a127c27e3a715605be53339c3cadca5243)

[nrf fromtree] west.yaml: MCUboot synchronization from upstream

---

MAINTAINERS.yml
subsys/net/ip/Kconfig.mgmt
subsys/net/ip/net_mgmt.c

This helps us work with low queue depth of network management queue in case the we have high rate events.
Fixes https://github.com/zephyrproject-rtos/zephyr/issues/56595 .
Upstream-PR: https://github.com/zephyrproject-rtos/zephyr/pull/57354

[nrf fromlist] net: Make net_mgmt queue timeout configurable

---

subsys/mgmt/mcumgr/grp/img_mgmt/Kconfig
subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c
subsys/mgmt/mcumgr/grp/img_mgmt/src/zephyr_img_mgmt.c

Fix check for chosen code partition in direct-xip mode and improve image version comparison.

mcumgr: img_mgmt: Fix using direct-xip mode in the NCS and friends

---

modules/openthread/Kconfig.thread
modules/openthread/platform/openthread-core-zephyr-config.h

Added the possibility to set the default OpenThread CSL timeout using Kconfig.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/57716

[nrf fromlist] net: openthread: configure OPENTHREAD_CSL_TIMEOUT

---

Kconfig.mcuboot
Kconfig.zephyr
subsys/mgmt/mcumgr/grp/img_mgmt/Kconfig
subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c
subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt_state.c

Five commits:
1) Separating MCUboot options to Kconfig.mcuboot
2) introducing Kconfig options that allow to inform application regarding MCUboot mode the application will be boot with;
3) disabling MCUmgr image management when MCUboot has been configured for single application mode;
4) disabling setting of image state, to confirm or test, when MCUboot has been configured for DirectXIP
5) commit form additional PR (https://github.com/zephyrproject-rtos/zephyr/pull/57794) that corrects image list for DirectXIP

Share MCUboot mode to app and use it in MCUmgr for basic DirectXIP support

---

lib/posix/getopt/getopt_long.c
tests/posix/getopt/testcase.yaml

Cherry picked from upstream Zephyr to resolve build warnings when using getopt.

Cherry pick getopt fix

---

subsys/bluetooth/host/scan.c

The phy was converted both when reading from the event and when reading from the sync, leading to incorrect value in the synced callback.
Upstream PR #57829

[nrf fromtree] Bluetooth: Host: Fix double conversion of phy

---

include/zephyr/net/wifi_mgmt.h
subsys/net/ip/net_private.h
subsys/net/l2/Kconfig
subsys/net/l2/wifi/Kconfig
subsys/net/l2/wifi/wifi_mgmt.c
subsys/net/l2/wifi/wifi_shell.c

Support to provide raw beacon and probe response data to registered application.

net: wifi_mgmt: Support to provide raw scan data

---

subsys/net/conn_mgr/Kconfig

Connection manager L2 Wi-Fi calls internally invoke WPA supplicant calls which requires higher stack size. Update the default stack size for such cases.
Marking this "nrf noup" since supplicant is not upstream yet.

[nrf noup] net: Increase connection manager stack size

---

subsys/net/ip/ipv4.h
subsys/net/ip/ipv6.h
subsys/net/ip/net_context.c

If a socket has DSCP set then the packets from the socket should also be marked with appropriate priority in case traffic classes are used in networking stack.
(cherry picked from commit 0df54dd47faf7ce0eec2d8e508d6dc31f643ff18)

[nrf fromlist] net: context: Set priority based on DSCP

---

include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_mgmt.c

Wrong macro was copied, this causes the event to fail.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/57943

[nrf fromlist] net: wifi: Fix typo in event

---

modules/openthread/Kconfig.thread
modules/openthread/platform/openthread-core-zephyr-config.h
west.yml

openthread upmerge to `d9abe30`
Signed-off-by: Piotr Jasiński <piotr.jasinski@nordicsemi.no>
(cherry picked from commit 9efd52fb90e21b8c6f3a0d671c003801c22ead76)

[nrf fromtree] manifest: openthread upmerge to `d9abe30`

---

include/zephyr/net/wifi.h

Fixed comparison between signed(int16_t) and unsigned(size_t) variables.
Signed-off-by: Wojciech Slenska <wsl@trackunit.com>
(cherry picked from commit 330a2f84c7425a3b6b9356b8d148ff44df171d99)

[nrf fromtree] net: wifi: Fix cpp compatibility

---

west.yml

[[nrf fromlist] manifest: Update nRF HW models to latest](https://github.com/nrfconnect/sdk-zephyr/commit/e48fc94fc7d1bbf81e89d18968a44ffbb7397a2e)
The nRF HW models have been updated to include the following
fixes and improvements.
* PPI: add support for nrf_ppi_group_enable
* BLECrypt: Widen search for crypto library
* Makefile: Switch to gnu11 from c11 due to HAL
* NVMC: Minor fixes in command line options descriptions
Which enable more 15.4 functionality with the nrf driver
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/58745
-----------
[[nrf fromtree] manifest: nrf hw models: Use latest w flash](https://github.com/nrfconnect/sdk-zephyr/commit/3f6607c0a75b9a040814e47e5e9b2dfce7d5baf8)
Update to the latest NRF HW models which include
models of the NVMC and UICR …

Update bsim nRF HW models

---

modules/openthread/Kconfig.features

Thic commit fixes `OPENTHREAD_FTD` dependency to `OPENTHREAD_UPTIME`.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
(cherry picked from commit 499bf552fb14050946fee94836fdc815b30f7621)

[nrf fromtree] net: openthread: Fix `OPENTHREAD_FTD` dependency.

---

boards/arm/bl5340_dvk/bl5340_dvk_cpunet_reset.c
boards/arm/nrf5340_audio_dk_nrf5340/nrf5340_audio_dk_cpunet_reset.c
boards/arm/nrf5340dk_nrf5340/nrf5340_cpunet_reset.c
boards/arm/thingy53_nrf5340/board.c

The function nrf_reset_network_force_off contains workaround for errata 161 for nRF5340 SoC. This function should be used instead of manual writing to NRF_RESET->NETWORK.FORCEOFF register.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/58045

[nrf fromtree] boards: nrf5340: use nrf_reset_network_force_off

---

subsys/net/l2/ethernet/ethernet_mgmt.c

Function net_if_ipv6_addr_rm is only defined for NATIVE_IPV6.
Upstream-Pr: https://github.com/zephyrproject-rtos/zephyr/pull/59108

[nrf fromtree] net: l2: ethernet: Fix IPv6 Kconfig

---

drivers/ieee802154/Kconfig.nrf5
drivers/ieee802154/ieee802154_nrf5.c
drivers/ieee802154/ieee802154_nrf5.h
samples/boards/nrf/ieee802154/802154_rpmsg/src/main.c

Workaround for nRF5340 network core crashes. 
Added Kconfig IEEE802154_NRF5_CALLOUT_TIMEOUT_MS.
Waiting for callbacks ending tx and cca operations are limited by Kconfig-urable `CONFIG_IIEEE802154_NRF5_CALLOUT_TIMEOUT_MS`
Waiting for end of delayed transmission (nrf5_tx_at) is limited to `time_ahead + CONFIG_IEEE802154_NRF5_CALLBACK_TIMEOUT_MS` 
Waiting for end of energy detection is limited to `duration + CONFIG_IEEE802154_NRF5_CALLBACK_TIMEOUT_MS` 
When frames cease to be received, the radio driver is polled with period `IEEE802154_NRF5_RX_THREAD_HEARTBEAT_PERIOD_MS` (60s by default for serialized driver) to check if network core crashed.
Also:
Cherry-picked commit: https://github.com/zephyrproject-rtos/zephyr/commit/174b7f47757845e531c33583dde372671cc5b27c which ensures that …

ieee802154 nrf5 callout timeouts

---

scripts/west_commands/build.py

Adjust WEST_PYTHON to posix path to be consistent with other Python scripts which passes paths to the Zephyr CMake build system.
(cherry picked from commit c03e1900ae7faf2d64b9275735f59c585a028937)

[nrf fromtree] scripts: adjust WEST_PYTHON to posix path

---

drivers/timer/nrf_rtc_timer.c
include/zephyr/drivers/timer/nrf_rtc_timer.h

The function `z_nrf_rtc_timer_exact_set` is added to allow setting compare channel without possible creeping of cc val.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/59297

drivers: timer: add z_nrf_rtc_timer_exact_set

---

boards/arm/thingy53_nrf5340/thingy53_nrf5340_cpunet.dts

CPUNET uses a diffetent DTS file and the edge connector entry was missed, this causes build issue for CPUNET.
Fixes 017ff78466("boards: thingy53: Update DTS files to support expansion boards").
Upstream-Pr: https://github.com/zephyrproject-rtos/zephyr/pull/59439

[nrf fromlist] boards: thingy53: Fix missing entry for CPUNET

---

include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_shell.c

This should be an unsigned integer. Also, add a comment to explain this feature.
Upstream-Pr: https://github.com/zephyrproject-rtos/zephyr/pull/59638

net: wifi: Fix power save timeout data type

---

modules/mbedtls/Kconfig
modules/mbedtls/Kconfig.psa

This PR addresses a mix of issues.
Using the same naming as the official PSA documentation for PSA algorithms.
Fixes missing missing dependency auto-enabling of PSA key types.
Fix missing dependency for cipher module with PSA stream cipher.
Various other small fixes, see commit messages.

[nrf noup] modules: mbedtls: Update PSA naming and fix dependencies

---

drivers/entropy/Kconfig.psa_crypto
modules/mbedtls/Kconfig
modules/mbedtls/Kconfig.psa

Set PSA configurations as default disabled, and let the application or users of PSA enable these as needed.

modules: mbedtls: Default PSA configurations disabled

---

subsys/net/lib/coap/coap_client.c

Use Zephyr internal zsock_ calls to remove dependency to NET_SOCKETS_POSIX_NAMES.

[nrf fromtree] net: lib: coap: Use zsock_ functions

---

CMakeLists.txt
cmake/compiler/clang/compiler_flags.cmake
cmake/compiler/compiler_flags_template.cmake
cmake/compiler/gcc/compiler_flags.cmake
lib/libc/picolibc/CMakeLists.txt

Now that the gcc compiler driver uses the -T flag instead of -Wl,-T, we can remove the hack here that kept the picolibc specs file from inserting the picolibc linker script.
Signed-off-by: Keith Packard <keithp@keithp.com>
(cherry picked from commit 4e7930b099771ecc5ad5c05b95a158cc0ceee0d2)

[nrf fromtree] libc/picolibc: Remove -T /dev/null linker arguments

---

include/zephyr/bluetooth/conn.h
subsys/bluetooth/host/Kconfig
subsys/bluetooth/host/smp.c

The current API for changing the bondable mode uses the global flag.
With Zephyr support for multiple Bluetooth identities, the API for
changing the bondable mode should be more fine-grained.
The bondable requirements of one identity should not have an impact on
another identity which can have a different set of requirements.
This change introduces function to overlay bondable flag per
connection.
Signed-off-by: Mateusz Kapala <mateusz.kapala@nordicsemi.no>
(cherry picked from commit 5b44ebe1595a8d4a46f5721271557d4159498673)

[nrf fromtree] bluetooth: host: smp: Add bondable flag overlay per connection

---

subsys/net/l2/wifi/wifi_shell.c

Use the macro to print to handle for cases where shell context is NULL, this is possible because in this net management event handler shell context is not passed.
Upstream-Pr: https://github.com/zephyrproject-rtos/zephyr/pull/60408

[nrf fromlist] net: l2: wifi: Fix printing of TWT parameters

---

tests/bsim/bluetooth/host/l2cap/split/tester/src/main.c

Don't assume the connection handle will always be 0. This is currently the case with the Zephyr link layer, but recently changed in the Softdevice Controller.
Another problem is that apparently the spec allows the controller to just blackhole data instead of returning `BT_HCI_ERR_UNKNOWN_CONN_ID` if the host uses a wrong handle.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
(cherry picked from commit 8a65b3f337f4a13ce46f74ddae61de5cbf6e179b)

[nrf fromtree] tests: Bluetooth: don't assume handle is 0

---

modules/hal_nordic/nrf_802154/CMakeLists.txt

Makes the files listed in the cmake file relative as they do not need to be absolute paths.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/59867

[nrf fromlist] modules: hal_nordic: nrf_802154: Make paths relative

---

modules/mbedtls/Kconfig.psa

Make the PSA key type configurations be user configurations instead
of implictly enabled based on other configurations.
While AES is the most likely to be used in this case the user can
choose different block ciphers for block cipher modes, and others
stream ciphers also exists.
This also allows applications to enable key generation without any
algorithms for ECC and RSA keys.
Also add the full key types configurations, even though not all may be
supported.
Add help text for for unsafe PSA algorithms. These should not be used
for security.
Use same text naming as PSA spec for RIPEMD-160 and SHA-1.

modules: mbedtls: Make PSA key types user configurations

---

subsys/net/ip/Kconfig.ipv4
subsys/net/ip/dhcpv4.c
subsys/net/ip/dhcpv4.h
subsys/net/ip/ipv4.c

Some DHCPv4 servers do not respect BROADCAST flag set on DHCP Discover, replying with unicast packet, making it impossible to obtain DHCP address by Zephyr in such cases.
RFC1542 chapter 3.1.1 makes the following statement about the BROADCAST flag:
This addition to the protocol is a workaround for old host
implementations.  Such implementations SHOULD be modified so
that they may receive unicast BOOTREPLY messages, thus making
use of this workaround unnecessary.  In general, the use of
this mechanism is discouraged.
Making it clear that being able to process unicast replies from the DHCP server is not only an optional behavior, but a recommended solution.
Therefore, introduce a support for unicast DHCPv4 in Zephyr. To achieve this, add additional filtering rule at the IPv4 level - in case …

[nrf fromtree] net: dhcpv4: Accept unicast replies

---

boards/posix/native_posix/irq_handler.c
boards/posix/nrf52_bsim/irq_handler.c

commit 7b438000ff3ad249b50eeb86e2755334527e579e 
[nrf fromtree] native_posix: IRQ handling: dont swap if kernel is uninitialized
After an interrupt, do not attempt to swap
if the kernel is not yet initialized.
Otherwise, if an interrupt is raised with interrupts
unlocked while the kernel is not yet fully initialized,
a swap would lead to a crash.
(This could happen if a PREKERNEK1/2 driver enables interrupts
and an interrupt fires before the kernel has swapped to
main)
(cherry picked from commit dcd6ee518867de3d2ff02f5b9dea084feef17821)
commit 930c35e461abf285fe92846477df09b22997c699
[nrf fromtree] nrf52_bsim: IRQ handling: dont swap if kernel is uninitialized
After an interrupt, do not attempt to swap
if the kernel is not yet initialized.
Otherwise, if an interrupt is raised with …

[nrf fromtree] native boards: IRQ handling: dont swap if kernel is uninitialized

---

subsys/bluetooth/host/conn.c

Fixes a race condition that could occur if the TX queue was read out before iso_has_ts was set. In that case, the provided buffer is of wrong length.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
(cherry picked from commit 5e44f2761b1f7f60e83186607de90b2850e5b253)

[nrf fromtree] Bluetooth: ISO: Fix HCI SDU length sent to controller

---

doc/build/index.rst
doc/build/version/index.rst
doc/develop/application/index.rst

Adds details on how to use Zephyr's VERSION file for setting the version of an application.

[nrf fromtree] doc: build: Add details on application version system

---

include/zephyr/net/socket_ncs.h

Add socket option level IPPROTO_ALL to socket_ncs.h.
PR that depends on this: https://github.com/nrfconnect/sdk-nrf/pull/11715

[nrf noup] include: net: add socket option level IPPROTO_ALL

---

subsys/net/lib/lwm2m/lwm2m_rd_client.c
tests/net/lib/lwm2m/lwm2m_rd_client/src/main.c
tests/net/lib/lwm2m/lwm2m_rd_client/src/stubs.c

Two more fixes for bootstrap timing issues.
Related sdk-nrf PR: https://github.com/nrfconnect/sdk-nrf/pull/12037
Original Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/61370

net: lwm2m: Two more bootstrap related fixes

---

tests/bsim/bluetooth/mesh/src/main.c

PR fixes using of the parameter with omitted names.
Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>
(cherry picked from commit b8f7c81dd3930ae1dde60dcf1daba32d03176816)

[nrf fromtree] tests: Bluetooth: Mesh: fix omitted names

---

.github/test-spec.yml

There is no need to run those for all PRs.
For example: When there are only changes to Bluetooth, we don't want this CI to run.
Adding these filters may speedup the time to merge for PRs to sdk-nrf

[nrf noup]: ci: Only run lwm2m tests when needed

---

.github/test-spec.yml

Extended the github CI filter for crypto and TF-M tests to reduce the CI load and possibly speed up PRs.

[nrf noup] ci: Only run crypto and tf-m tests when needed

---

modules/mbedtls/Kconfig.psa

Add Kconfig options:
PSA_WANT_ALG_CCM_STAR_NO_TAG
PSA_WANT_ALG_PURE_EDDSA
PSA_WANT_ALG_HKDF_EXTRACT
PSA_WANT_ALG_HKDF_EXPAND
since they exist in the Oberon PSA core.
Rename:
PSA_WANT_ALG_SRP -> PSA_WANT_ALG_SRP_6
To align with the Oberon PSA core.

modules: mbedtls: Align Kconfig options with Oberon PSA core

---

.github/test-spec.yml

Add BLE CI test dependency and update the include path of mesh.

[nrf noup] ci: Update ble and mesh test-spec entry

---

include/zephyr/net/zperf.h
subsys/net/ip/Kconfig
subsys/net/ip/icmpv4.c
subsys/net/ip/icmpv4.h
subsys/net/ip/icmpv6.c
subsys/net/ip/icmpv6.h
subsys/net/ip/net_shell.c
subsys/net/lib/zperf/zperf_common.c
subsys/net/lib/zperf/zperf_internal.h
subsys/net/lib/zperf/zperf_shell.c
subsys/net/lib/zperf/zperf_tcp_uploader.c
subsys/net/lib/zperf/zperf_udp_uploader.c

This is handy in testing of setting priority directly rather than deriving from DSCP. Please note ICMP doesn't use net context.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/62313

[nrf fromlist] net: shell: Add priority to ping

---

subsys/net/lib/sockets/socketpair.c
tests/net/socket/socketpair/testcase.yaml

net: socketpair: Fix use after free
In low memory conditions, its possible for socketpair memory allocation
to fail and then the socketpair is freed but after that the remote
semaphore is released causing a crash.
Fix this by freeing the socketpair after releasing the semaphore. Add a
test case to induce low memory conditions (low HEAP and high socketpair
buffer size), with the fix issue is not seen.

[nrf fromlist] net: socketpair: Fix use after free

---

modules/mbedtls/Kconfig.psa

fixup! [nrf noup] modules: mbedtls: add PSA configurations
Add missing PSA key types configurations.
These configurations are needed to satisfy the PSA_HAS_KEY_TYPE_SUPPORT hidden configuration.
NCSDK-22424

[nrf noup] modules: mbedtls: Add missing PSA key types configurations

---

modules/openthread/platform/crypto_psa.c

The psa_generate_random function requires the psa_crypto_init call before the usage. This can be ensured by calling the psa_crypto_init in otPlatCryptoRandomInitfunction.

[nrf fromtree] net: openthread: Initialize PSA crypto when random is initializing

---

modules/mbedtls/CMakeLists.txt
modules/trusted-firmware-m/CMakeLists.txt
modules/trusted-firmware-m/interface/interface.c
west.yml

Update trusted-firmware-m to 1.8.0, mbedtls to 3.4.0, and tf-m-tests to 1.8.0.  Includes minor cmake changes due to file renames and such, as well as adjusting the return type of a callback function that has changed since the previous version of trusted-firmware-m.
(cherry picked from commit 3b3e28aedaf8f30b03eb1e1753d9ab34d34c5d99)

[nrf fromtree] manifest: Upgrade to trusted-firmware-m 1.8.0

---

modules/mbedtls/Kconfig
modules/mbedtls/Kconfig.psa
subsys/net/conn_mgr/Kconfig

Kconfig compliance is run with Zephyr Kconfig as the root Kconfig file.
Because of this a number of of Kconfig symbols applied in noup commits are not defined and compliance complains.
Fix this issue by forward declaring these Kconfig symbols.

[nrf noup] Fix use of undefined Kconfig symbols

---

include/zephyr/logging/log_msg.h

Resolve unused arg compiler error
(cherry picked from commit b1b4932373c6a9b2665432b68df520223243886f)

[nrf fromtree] logging: Unused arg in log_msg_get_tid

---

subsys/net/l2/wifi/wifi_shell.c

The mode command operation has to be set to WIFI_MGMT_GET when the option -g is provided. It was mistakenly set to true. Correcting the same
This PR fixes #63424 and sets the proper value for the get command
Signed-off-by: Vivekananda Uppunda <vivekananda.uppunda@nordicsemi.no>
(cherry picked from commit b0c96580298ac47715fdb1d1ba5ede766676d643)

net: l2: wifi: Fix Wi-Fi mode get command bug

---

lib/libc/common/source/stdlib/malloc.c
lib/os/Kconfig.heap

fixup! [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
The configurations SRAM_SIZE and SRAM_BASE_ADDRESS use devicetree definitions. These are not matching the partition manager configuration. Use partition manager values in malloc heap size calculations. Don't trust the value of SRAM_SIZE to determine if only small heaps needs to be supported.

[nrf noup] tree-wide: Fix malloc heap-size with partition manager enabled

---

subsys/net/ip/tcp.c

In case RST packet is received or malformed packet is received, the TCP should not proceed with the state machine execution (which may process the invalid packet) but rather jump directly to exit, where the connection will be closed.
(cherry picked from commit 370096e4f5b3dc9c9565b0d9322e94c58803a9d3)

[nrf fromtree] net: tcp: Fix goto condition in case of RST/packet error

---

subsys/bluetooth/Kconfig.iso
subsys/bluetooth/controller/ll_sw/ull.c
subsys/bluetooth/host/conn.c

PR contains four commits:
1st commit fixes Zephyr LL controller to pass bsim tests after the following changes in Host
2nd commit fixes calculations of HCI ISO Data packet length
3rd commit fixes timestamp value for SDUs fragmented to several HCI ISO Data packets
4th commit fixes KConfig descriptions of BT_ISO_TX_MTU and BT_ISO_RX_MTU

[nrf fromtree] Hci iso data packets fragmentation fix

---

subsys/fs/nvs/Kconfig
subsys/fs/nvs/nvs.c

Introduce `NVS_LOOKUP_CACHE_FOR_SETTINGS` Kconfig option that enables a dedicated hash function for the NVS lookup cache that takes advantage of the NVS ID allocation scheme used by the NVS settings backend. As such, this option should only be used if an application uses NVS via the settings layer.
The commit is a `noup` patch because the original change seems not generic enough to be accepted by the Zephyr community: https://github.com/zephyrproject-rtos/zephyr/pull/61619.

[nrf noup] settings: nvs: use dedicated lookup cache hash function

---

drivers/flash/soc_flash_nrf.c

Fix UICR read access.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/62873
(cherry picked from commit b9ffe72133e90453d275cc80b88f95b29002ec60)

[nrf fromlist] drivers/flash/nrf: Workaround for nrf91 errata 7

---

soc/arm/nordic_nrf/nrf53/soc.c

For RTC0 events the RTC1 pretick event was not cleared what caused the WDT to be not stopped. This resulted in increased power usage.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/63597

[nrf fromlist] nrf53: fix RTC pretick power usage for events on RTC0

---

modules/openthread/platform/crypto_psa.c

If asserts are disabled, there is a warning in 'otPlatCryptoInit' regarding unused variable `err`. This commit fixes that.
Signed-off-by: Maciej Baczmanski <maciej.baczmanski@nordicsemi.no>
(cherry picked from commit [d2495b14f25a49b7247d1d325bd97ecb5530851c](https://github.com/zephyrproject-rtos/zephyr/commit/d2495b14f25a49b7247d1d325bd97ecb5530851c))

[nrf fromtree] modules: openthread: fix unused variable during `otPlatCryptoInit`

---

drivers/spi/spi_nrfx_spis.c
subsys/bluetooth/common/Kconfig
tests/kernel/timer/timer_behavior/src/jitter_drift.c

- drivers: spi_nrfx_spis: Handle empty spi_buf_set structures properly
- tests: kernel: timer: jitter_drift: Restore initial alignment to tick
- bluetooth: common: Kconfig: Add missing dependency for BT_MONITOR

[nrf fromtree] A few upstream fixes for NCS 2.5

---

west.yml

New hal_nordic revision contains updated nrfx with an improvement to nRF91 anomaly 7 workaround.
Upstream PR: zephyrproject-rtos/zephyr#63841

[nrf fromlist] manifest: update hal_nordic rev to fix nRF91 anomaly 7

---

dts/arm/nordic/nrf52820.dtsi

The nRF52820 radio peripheral supports IEEE 802.15.4, add the required property and node to reflect this.
See
https://infocenter.nordicsemi.com/topic/ps_nrf52820/radio.html?cp=5_3_0_5_11
(cherry picked from commit f39944933d8a3aa8761711e788cabfc07117377d)

dts: arm: nordic: Add support for ieee802154 in the nRF52820 radio

---

west.yml

New hal_nordic revision contains updated nrfx
with a fix to GPIOTE driver array out-of-bounds
access on nRF52820.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/64014

[nrf fromlist] manifest: update hal_nordic to fix nRF52820 nrfx_gpiote

---

subsys/bluetooth/host/testing.c
subsys/bluetooth/mesh/access.c
subsys/bluetooth/mesh/blob_srv.c
subsys/bluetooth/mesh/dfu_cli.c
tests/bluetooth/tester/src/btp_mesh.c

PR includes:
- MBT bugfixes: https://github.com/zephyrproject-rtos/zephyr/pull/63904
- DFU bugfixes: https://github.com/zephyrproject-rtos/zephyr/pull/64034
- Models extensions bugfixes: https://github.com/zephyrproject-rtos/zephyr/pull/64065

[nrf fromlist] Mesh 1.1 bugfixes from PRs

---

tests/bluetooth/tester/src/btp_gatt.c

Pass only speficied number of handler to read_params for GATT read multiple. This is to avoid sending invalid (zeros) handles in ATT_READ_MULTIPLE_REQ.
This was affecting GATT/CL/GAR/BI-18-C and GATT/CL/GAR/BI-19-C qualification test cases.
Signed-off-by: Szymon Janc <szymon.janc@codecoup.pl>
(cherry picked from commit 4f57614cbddc66dbe264691352fe07223e3974e0)

[nrf fromtree] tests: bluetooth: tester: Fix GATT read multiple

---

scripts/ci/check_compliance.py

If in a server multiple users are running compliance then it throws errors as the filename "Kconfig.modules" and "Kconfig.dts" is owned by someone else.
Fix this by creating a randomized Kconfig file and delete after use.

scripts: ci: Fix for compliance with multi-user machine

---

.github/test-spec.yml

HomeKit Accessory Development Kit has been deprecated and removed from NCS.

testspec: remove HomeKit from NCS

---

include/zephyr/zbus/zbus.h
subsys/bluetooth/audio/bap_broadcast_sink.c
subsys/zbus/Kconfig
subsys/zbus/zbus.c

Needed changes for fixing a looping issue when removing a PA sync and adding message subscribers to zbus

Cherry pick zbus and host fixes

---

include/zephyr/bluetooth/hci.h
subsys/bluetooth/host/hci_core.c

This new API returns the version string corresponding to a given HCI version.
The API can be used by applications to print out human-readable information about the controller being used.
Adding this API removes possible code duplication.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
(cherry picked from commit 8b2dd61ebab8af6a1c17abee4b565f1d1c8222b6)

[nrf fromtree] Bluetooth: HCI: Add bt_hci_get_ver_str()

---

.github/test-spec.yml

CI-run-zephyr-twister is used to determine if twister tests from sdk-zephyr should be run on PR to sdk-nrf repository.

[nrf noup] ci: Add CI-run-zephyr-twister test spec

---

doc/develop/test/pytest.rst
doc/develop/test/twister.rst
samples/subsys/testsuite/pytest/shell/pytest/test_shell.py
scripts/pylib/pytest-twister-harness/src/twister_harness/__init__.py
scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py
scripts/pylib/pytest-twister-harness/src/twister_harness/fixtures.py
scripts/pylib/pytest-twister-harness/src/twister_harness/fixtures/__init__.py
scripts/pylib/pytest-twister-harness/src/twister_harness/helpers/mcumgr.py
scripts/pylib/pytest-twister-harness/src/twister_harness/plugin.py
scripts/pylib/pytest-twister-harness/tests/fixtures/mcumgr_fixture_test.py
scripts/pylib/twister/twisterlib/harness.py
scripts/pylib/twister/twisterlib/reports.py
scripts/pylib/twister/twisterlib/runner.py
scripts/schemas/twister/testsuite-schema.yaml
scripts/tests/twister/pytest_integration/test_harness_pytest.py

Cherry-pick changes from twister to improve reporting of failed pytest scenarios and added parametrized scope of DUT fixture.

[nrf fromtree] twister: pytest: Improve reporting and fixtures

---

drivers/serial/uart_nrfx_uarte.c

Upstream commit: https://github.com/zephyrproject-rtos/zephyr/commit/52c55177ba71af328c6069ea56c007e6eb5cdf1d
Upstream Issue: https://github.com/zephyrproject-rtos/zephyr/issues/62828
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/64094

[nrf fromtree] drivers: uart: nrf: rx_timeout_slab incorrectly set

---

arch/arm/core/aarch32/Kconfig
modules/trusted-firmware-m/CMakeLists.txt
modules/trusted-firmware-m/Kconfig.tfm

Exception info dump is a very basic feature so it should IMHO be enabled by default.
For instance, a simple null-pointer exception in the non-secure app will not be logged unless this option is enabled.
(cherry picked from commit a4e9aed68de223968e43f4ea4fa1abdda5b49c26)

[nrf fromtree] tfm: Enable TFM_EXCEPTION_INFO_DUMP by default

---

modules/openthread/platform/uart.c

Uart driver for openthread have been waiting for host to start communicating with coprocessor, during booting of the Zephyr and by that blocking start os OS. There is no longer a need for that since the stack will be soft rebooted after host connects to coprocessor, removing the need to wait on host communication.
Signed-off-by: Przemyslaw Bida <przemyslaw.bida@nordicsemi.no>
(cherry picked from commit cc85223ed4d5907bd457cb8145672c2167821cbf)

net: openthread: Remove waiting for DTR in openthread UART.

---

west.yml

Due to the fact that hal_nordic hosted on zephyrproject-rtos github space already has nrfx 3.2.0 integrated into it there is a need to switch to sdk-hal_nordic for NCS 2.5.1 release. New hal_nordic revision has nrfx 3.1.0 with MDK 8.58.0 plus few minor fixes requested by upcomming NCS release.

manifest: Update hal_nordic to point to sdk-hal_nordic

---

include/zephyr/bluetooth/conn.h
include/zephyr/bluetooth/hci_types.h
subsys/bluetooth/Kconfig
subsys/bluetooth/controller/Kconfig
subsys/bluetooth/host/conn.c
subsys/bluetooth/host/conn_internal.h
subsys/bluetooth/host/hci_core.c
subsys/bluetooth/shell/bt.c
tests/bluetooth/shell/testcase.yaml

These commits add the LE API's for the LE Power Control Request Feature in Zephyr.
The support of feature is provided with the controller-based feature selection with BT_CTLR_LE_POWER_CONTROL_SUPPORT and is selectable via BT_TRANSMIT_POWER_CONTROL.
With the new APIs, the applications will:
get improved reading of local and remote tx power
be aware of changes in remote or local tx power
Defined HCI commands in Core Spec v5.4:
7.8.117 LE Enhanced Read Transmit Power Level command: improvement to existing local tx power reading.
7.8.118 LE Read Remote Transmit Power Level command: Remote tx power is read through an event (LE Transmit Power Reporting) 7.8.121 LE Set Transmit Power Reporting Enable command: Enables local or remote tx power reporting to monitor changes in tx power 7.7.65.33 LE …

Add le power control request feature le apis

---

subsys/net/l2/wifi/wifi_mgmt.c

When WPA-PSK was introduced the passphrase length check was missed.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/65933

[nrf fromlist] wifi: Check WPA-PSK passphrase length

---

subsys/net/l2/wifi/wifi_shell.c

While printing SSID in wifi status command, If the length is maximum(32 character). It leads to buffer overflow. It required one character for null
terminator ‘\0’. Changing the Format Specifiers to print proper SSID.
Signed-off-by: Kapil Bhatt <kapil.bhatt@nordicsemi.no>
(cherry picked from commit cb7b650b923f160540943f0724b79b79fd8e51f4)

[nrf fromtree] net: l2: wifi: Fix Print of SSID in WIFI status

---

doc/develop/test/pytest.rst
scripts/pylib/twister/twisterlib/environment.py
scripts/pylib/twister/twisterlib/harness.py
scripts/tests/twister/pytest_integration/test_harness_pytest.py

Cherry-pick changes from twister to pass parameters to pytest subprocess. It allows to select a specific testcase from a test suite.

[nrf fromtree] twister: pytest: Add --pytest-args to Twister command line

---

soc/arm/Kconfig
soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf91/Kconfig.series

CPU_HAS_NRF_IDAU is depending on SOC_SERIES_NRF91X and SOC_NRF5340_CPUAPP.
This makes it more difficult to have an out-of-tree nrf SOC.
It is also an unnecessary dependency. There is no prompt for CPU_HAS_NRF_IDAU, so it will not show up in menuconfig and it won't be possible to enable it from a users Kconfig fragment.
The only way to enable it is to select it, and those that select this option can themselves make sure that they only do so when appropriate.
Also, move NRF_SPU options out to SOC Kconfig files to also make out-of-tree SoCs possible. With the added benefit of not polluting the common soc/arm/Kconfig.
(cherry picked from commit 6348a973c38eeed5e18e6821dcb38a1c2f78ac76)

[nrf fromtree] soc: arm: Remove CPU_HAS_NRF_IDAU's dependencies

---

drivers/flash/nrf_qspi_nor.c

- [nrf fromtree] drivers: nrf_qspi_nor: Activate QSPI peripheral when enabling XIP
- [nrf fromtree] drivers: nrf_qspi_nor: Prevent reading status before sending RDPD
- [nrf fromtree] drivers: nrf_qspi_nor: Clean up handling of return values
- [nrf fromtree] drivers: nrf_qspi_nor: Refactor deactivation and locking access to QSPI
- [nrf fromtree] drivers: nrf_qspi_nor: Fix and refactor driver initialization
Ref. NCSDK-24746

[nrf fromtree] Fixes an improvements in the nrf_qspi_nor driver

---

.github/workflows/compliance.yml
scripts/gitlint/zephyr_commit_rules.py

squash! [nrf noup] ci: NCS-specific CI tweaks
Necessary changes for NCS CI.
- Add a Jenkinsfile
- Add a commit-tags workflow: This enables sauce tag checking in sdk-zephyr
- compliance.yml: Disable check for merge commits, since we have upmerges downstream. Also, since in the code we refer to Kconfig symbols that are defined in the sdk-nrf repository, the Kconfig checks (Kconfig, KconfigBasic and KconfigBasicNoModules) will not pass so exclude them. Also, disable any maintainers-related checks
- scripts/gitlint: Extend the max commit line lengths for Gitlint to account for sauce tags
(cherry picked from commit d34b035bcc569431b7008c72edc55db1b29bccf3) (cherry picked from commit 4a6d5fc57fe7589b2585ee5e44341f50821cc653) (cherry picked from commit a01c3a4caccb6964a29078172ba7f590bcdbe790) …

[nrf noup] ci: NCS-specific CI tweaks

---

drivers/ieee802154/ieee802154_nrf5.c

Skip configuring ACK header IE if `EnableCsl()`
has been called with arguments:
- `aCslPeriod` == 0
- `aShortAddr` == IEEE802154_NO_SHORT_ADDRESS_ASSIGNED
- `aExtAddr` == NULL
This happens during RCP startup in `Radio::Init()` implementation.
It will be fixed on OT and Zephyr level, but this commit is needed
to prevent coprocessor samples from asserting on boot.

[nrf noup] drivers: ieee802154: temporary fix for ACK header IE config

---

dts/arm/nordic/nrf5340_cpunet.dtsi

The required property `easydma-maxcnt-bits` was missing for nrf5340_cpunet.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/67600

[nrf fromtree] dts: nrf5340: add missing `easydma-maxcnt-bits` for nrf5340_cpunet

---

subsys/net/lib/sockets/sockets.c

According to the POSIX specification, null pointer is a valid value for the `address` argument
of the `accept` function.
This commit adds a check to prevent a null pointer dereference inside `z_impl_zsock_accept`.
(cherry picked from commit f3b2c04661370ac595faf32d2cafb43506704671)

[nrf fromtree] net: sockets: prevent null pointer dereference

---

drivers/regulator/regulator_common.c

Reference counting was broken when adding the enable delay. Now reverted to previous pattern.
Signed-off-by: Andy Sinclair <andy.sinclair@nordicsemi.no>
(cherry picked from commit c3a54ae1c34e939db83431bea354c0f4d0add0b3)

[nrf fromtree] drivers: regulator: Fixed reference counting during enable

---

drivers/ieee802154/ieee802154_nrf5.c
drivers/ieee802154/ieee802154_nrf5.h

The current implementation implicitly assumes that if the device is configured to have the capability of acting as a CSL endpoint then in case a delayed reception with matching ID finishes with a timeout no action is needed. This assumption is correct when RxOnWhenIdle mode is disabled because the transition to sleep is done automatically by the driver below. However, it's wrong when RxOnWhenIdle is enabled. This commit fixes that case by adding a call to event handler that notifies the higher layer about the event and allows it to transition to RxOff if needed.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/67774

[nrf fromlist] drivers: ieee802154: fix nRF5 Rx error handling

---

boards/posix/nrf_bsim/nrf5340bsim_nrf5340_cpuapp.dts
west.yml

3 patches directly from Zephyr upstream from a couple of days after the upmerge target.
Needed to have the nrf5340bsim targets be more usable with the SDC and 802154 drivers.
-------
[nrf fromtree] boards nrf5340bsim_cpuapp: Select approprite 802154 radio in DT
Set the chosen 802154 radio in DT for the
nrf5340bsim_nrf5340_cpuapp so we can build with the
radio driver built into the net core.
Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
(cherry picked from commit 47b7eaece9419214fb2065cba4b9c520dc807ca6)
-------
[nrf fromtree] manifest: Update nrf hw models to latest
* Update the HW models module to
9b985ea6bc237b6ae06f48eb228f2ac7f6e3b96b
Including the following:
* 9b985ea nrf_ccm: Add RATEOVERRIDE subscribe support
* 8592230 nrf_hack: Add comments
* …

[nrf fromtree] Patches to enable the nrf5340bsim

---

include/zephyr/net/wifi.h
include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_shell.c

Update user/app status of TWT teardown sessions.
Upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/67469

[nrf fromtree] net: mgmt: Update app of TWT teardown status

---

include/zephyr/bluetooth/audio/audio.h
subsys/bluetooth/audio/ascs.c
subsys/bluetooth/audio/bap_broadcast_sink.c
subsys/bluetooth/audio/bap_broadcast_source.c
subsys/bluetooth/audio/bap_iso.c
subsys/bluetooth/audio/bap_iso.h
subsys/bluetooth/audio/bap_stream.c
subsys/bluetooth/audio/bap_stream.h
subsys/bluetooth/audio/bap_unicast_client.c

Two patches from Zephyr upstream for bring transparent coding format and fixing issue for invalid ISO datapath issue.

[nrf fromtree] Patches for ISO datapath issue

---

drivers/ieee802154/ieee802154_nrf5.c
include/zephyr/net/ieee802154_radio.h
modules/openthread/platform/radio.c
west.yml

Revert hotfix from PR: https://github.com/nrfconnect/sdk-zephyr/pull/1441
Fix bugs in current implementation of ieee802154 driver:
- after refactoring `set_vendor_ie_header_lm`, case when `link_metrics_data_len == 0` has been ignored. Fixed by refactoring the code again.
- Resetting RCP stack by openthread has been handled incorrectly (`-ENOTSUP` returned). Fixed by implementing `otPlatRadioResetCsl` in upstream OpenThread and adding `clear_ie` flag.
- refactoring of enh ACK header IE resulted with returning `-ENOTSUP` when `ack_ie.header_ie == NULL` (set when csl period set to 0 in `otPlatRadioEnableCsl`), because
`ieee802154_header_ie_get_element_id` accessed `NULL` pointer.
- `struct ieee802154_config config` is a struct containing an union. Members of `config` were accessed …

Cherrypick fixes for ACK header IE related bugs

---

subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/access.c
subsys/bluetooth/mesh/delayable_msg.c
tests/bsim/bluetooth/mesh/src/test_access.c
tests/bsim/bluetooth/mesh/src/test_persistence.c
tests/bsim/bluetooth/mesh/src/test_provision.c
tests/bsim/bluetooth/mesh/tests_scripts/access/access_transmit_delayable.sh
tests/bsim/bluetooth/mesh/tests_scripts/priv_beacon/proxy_adv_multi_subnet_coex.sh

Enable by default the access layer responses random delays. Commit also adapts all mesh models, samples and
babblesim tests to use random delay functionality correctly.
(cherry picked from commit 4e7d64b1b45247de1e1d71a4402f5637b0fd0afe)

[nrf fromtree] Bluetooth: Mesh: enable access responses randomization

---

subsys/net/l2/wifi/wifi_shell.c

For a Wi-Fi station the connect API supports both band and channel configuration, but for a shell command either channel or band makes sense, so, overload the channel field to support band.
Rejig the band and channel validation to support all modes.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/68174

[nrf fromlist] wifi: shell: Add band support for STA

---

subsys/bluetooth/audio/ascs.c
subsys/bluetooth/audio/bap_unicast_client.c

Since we always set up the ISO data path for endpoints in both directions (due to limitations in the ISO API), we can actually receive valid (empty) SDUs on a CIS in a direction that has not been configured.
This is not the ideal solution, but prevents unncessary LOG_ERR. The ideal solution is to modify the ISO API to provide the flexibility that BAP needs w.r.t. ISO data paths, but that is a larger change for later.
(cherry picked from commit 13a357b0198defde8f5c34920bec25b9ea2a0855)

[nrf fromtree] Bluetooth: BAP: Update log for unicast iso recv without endpoint

---

modules/mbedtls/Kconfig.psa

Thread and Matter use PSA JPAKE and SPAKE2+ APIs underneath. Don't select `EXPERIMENTAL` flags in these cases.

[nrf noup] modules: mbedtls: change `EXPERIMENTAL` flags on PSA features that are used by Matter and Thread

---

include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_shell.c

Provision of configurable parameter for generating unblock event ahead of TWT slot. Host application depending upon latencies can configure this to wakeup rpu ahead of the TWT slot.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull//67317

[nrf fromlist] net: shell: Early wake up for TWT power save

---

drivers/flash/Kconfig.nordic_qspi_nor
drivers/flash/nrf_qspi_nor.c

Added Kconfig assignment of qspi timeout.
Per nrfx v3.2 addition of qspi timeout in config
struct.
Previous: https://github.com/nrfconnect/sdk-zephyr/pull/1428

[nrf fromtree] drivers: qspi: added operation timeout

---

drivers/ieee802154/ieee802154_nrf5.c
drivers/ieee802154/ieee802154_nrf5.h

This reverts commit 780b12854c11f10f6b3e4b21ae02eaa1b2965736. "drivers: ieee802154: nrf: cache radio channel"
Implementation affected RCP devices in openthread as MAC layer does not call `Receive()` functions after transmit is done.
Additionally, after sending a frame to a new channel (for example while discovery operation), radio switches to RX state immediately after TX, but continues to listen on old channel for about 5ms, until MAC layer calls `Receive` operation, forcing to change the channel.
Signed-off-by: Maciej Baczmanski <maciej.baczmanski@nordicsemi.no>
(cherry picked from commit [dbe74b3299f1e247db8c33491ad932e1681c0efa](https://github.com/zephyrproject-rtos/zephyr/commit/dbe74b3299f1e247db8c33491ad932e1681c0efa))

[nrf fromtree] Revert "drivers: ieee802154: nrf: cache radio channel"

---

west.yml

* Update the HW models module to 52d0b4b7b7431d8da6222cc3b17a8afdcb099baf
Including the following:
* 52d0b4b UART: FIFO backend: Do not error out if other side disconnects Rx
* 3582b68 UART: FIFO backend: Avoid possible race
* 414f160 AAR: Fix UBSAN warnings
* 24f5d3d PPI: Fix UBSAN warning
* d17c9d7 UART: Bugfix: Support STARTRX while Rx is stopping
* d982e76 UART: Minor bugfix: Fix 2 warning messages
* eda7af9 UART: Bugfix: Handle task STOPTX while stopping
* b8ea63b UART: BugFix: Support STARTTx even if Tx is not Off
* c0d28cc nrf_common: Add replacement for nrf_dma_accessible_check()
* feb91bb nrfx_common replacement: nrfx_get_irq_number() Add missing peri
* c95d9af Makefile: By default lets build both 52833 and 5340 targets
* cf41110 UART: FIFO backend: Check for failure of fcntl
* …

[nrf fromtree] manifest: Update nrf hw models to latest including UBSAN fixes

---

subsys/bluetooth/host/adv.c
subsys/bluetooth/host/hci_core.c
subsys/bluetooth/host/hci_core.h
subsys/bluetooth/host/iso.c
subsys/bluetooth/host/l2cap.c
subsys/bluetooth/host/l2cap_br.c
subsys/bluetooth/host/scan.c

Several warnings were reported by UBSAN when testing different Bluetooth LE features.
This PR fixes 3 different warnings.

[nrf fromtree] Bluetooth: UBSAN warnings fixes

---

subsys/net/lib/lwm2m/Kconfig
subsys/net/lib/lwm2m/lwm2m_engine.c
subsys/net/lib/lwm2m/lwm2m_message_handling.c
subsys/net/lib/lwm2m/lwm2m_rd_client.c
tests/net/lib/lwm2m/lwm2m_engine/src/main.c

* 992936300bf - net: lwm2m: Use CID_SUPPORTED instead of CID_ENABLED (2 weeks ago) <Seppo Takalo>
* bf872870eab - net: lwm2m: Fix segfault on failed bootstrap (3 weeks ago) <Seppo Takalo>
* 9eee8d2be59 - net: lwm2m: Allow send operations when sleeping (3 weeks ago) <Juha Ylinen>
One critical fix (segfault) needed for the 2.6.0 release, so I'll pull in few other changes to keep in synch.
ZCBOR changes are in separate PR https://github.com/nrfconnect/sdk-zephyr/pull/1471 so I'll skip those.

Lwm2m: upstream updates

---

west.yml

Updated hal_nordic fixes APPROTECT handling on nRF91 target, as well as fixes missing alignment of nrfx samples to modified API of the GPIOTE driver.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/68800

[nrf fromtree] manifest: Update hal_nordic revision to fix APPROTECT on nRF91 and to fix nrfx samples build error

---

subsys/bluetooth/host/hci_core.c
subsys/bluetooth/shell/bt.c

Allow the channel map to be set when periodic advertising or acting as
an ISO source.

Downstream channel classification fix

---

subsys/net/lib/dhcpv4/Kconfig
subsys/net/lib/dhcpv4/dhcpv4_server.c

Jira: NCSDK-25558
Jira: NCSDK-25559

net: DHCPv4 server improvements

---

scripts/ci/test_plan.py

In twister, applying quarantine is a part of apply_filters() function. However, this function is not called when --load-test is used. Therefore, if one wants to use quarantines in combination with dynamic scope from the test_plan.py script, one has to pass such info through the script.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/66659

[nrf fromlist] scripts: Allow using quarantine mechanism with test_plan.py script

---

modules/hal_nordic/nrfx/CMakeLists.txt

Add required dppic interconnect files for nRF54L15.

[nrf fromlist] modules: hal_nordic: nrfx: Fix DPPIC support for nRF54L15

---

subsys/ipc/ipc_service/backends/ipc_rpmsg_static_vrings.c

…point
The work item will attempt to dereference pointers that have been nulled by the backend.
To avoid that, wait until all items currently on the queue have been processed.
The symptom is a busfault on ARM, and is "fixed" by adding a `k_msleep(1)` right before `ipc_service_deregister_endpoint()`. This will in effect do the same thing as this patch, and allow the scheduler to run the work item on the ipc workqueue.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
(cherry picked from commit f24a01e6d1e6804af9ae3fd81850e798076027ff)

[nrf fromtree] ipc: Drain pending work items before deregistering endpoint

---

subsys/bluetooth/host/att.c

Taken from https://github.com/zephyrproject-rtos/zephyr/pull/68882

Bluetooth: Correct `bt_att_create_rsp_pdu` reservation when EATT is enabled

---

drivers/i2s/i2s_nrfx.c

The driver uses pinctrl to configure pins instead of nrfx I2S API. Check whether MCK pin was actually connected by pinctrl instead of comparing nrfx_cfg.mck_pin that is always NRF_I2S_PIN_NOT_CONNECTED.
This makes it possible for nRF I2S to provide master clock even when operating in I2S Slave mode.
Signed-off-by: Tomasz Moń <tomasz.mon@nordicsemi.no>
(cherry picked from commit 76e12a33d94bf72d1351171cec1875c64ec93f0c)

[nrf fromtree] drivers: i2s_nrfx: Generate master clock if pin is connected

---

drivers/serial/uart_async_to_irq.c
drivers/serial/uart_nrfx_uarte.c
drivers/spi/Kconfig.nrfx
drivers/spi/spi_nrfx_spi.c
drivers/spi/spi_nrfx_spim.c
soc/arm/nordic_nrf/nrf53/Kconfig.soc
soc/arm/nordic_nrf/nrf53/soc_cpu_idle.h

A set of fixes from upstream that should be included in NCS 2.6.0

[nrf fromtree] Upstream fixes for NCS 2.6.0

---

.github/test-spec.yml

Descope samples and tests from many CIs, since the majority are not affecting the functionality of protocols and applications.
Samples that may affect the overall performance and functionality, should be enabled specifically.

test-spec: descope samples and tests from many CIs

---

drivers/sensor/adxl367/adxl367_trigger.c

The adxl367_trigger.c file was missing a DT_COMPAT definition, which resulted in the driver config structs being misaligned between the driver source files. This is fixed here.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/69339
(cherry picked from commit b7a83778dff35a6c94b20509453d31ef0caaabb7)

[nrf fromlist] drivers: sensor: adxl367: fix trigger support

---

drivers/mfd/mfd_npm6001.c

Sets SWREADY in MFD initialization, so that hysteresis mode can be used.

[nrf fromtree] drivers: mfd: npm6001: set SWREADY

---

modules/mbedtls/Kconfig.psa

Adds new Kconfigs used by the Oberon PSA core v1.2.1.1
Noup since the Oberon PSA core is Nordic only code.
Ref: NCSDK-26057

[nrf noup] modules: mbedtls: Add new PAKE Kconfigs

---

subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/access.c

CDP1 is mandatory to qualify a mesh device for mesh protocol v1.1. The dependency on BT_MESH_MODEL_EXTENSIONS is removed because if a node contains only base models (for example Generic OnOff Server), this API will consume extra RAM bytes which won't be used.
(cherry-picked from commit e30b7a84bc421dc16e87c47deab1921186604830)

[nrf fromtree] Bluetooth: Mesh: Enable CDP1 by default

---

modules/hal_nordic/nrf_802154/sl_opensource/platform/nrf_802154_clock_zephyr.c

The __WEAK-tagged function `nrf_802154_clock_hfclk_ready` is removed. The implementation is provided by the nRF 802.15.4 Radio Driver. Existence of __WEAK-tagged version causes incorrect behavior when Link Time Optimization is used.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/69581

modules: hal_nordic: remove weak nrf_802154_clock_hfclk_ready

---

boards/arm/nrf9151dk_nrf9151/doc/index.rst

This patch fixes a broken link in the docs for the nrf9151dk.
It points to the SiP's product page for now.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/69516
(cherry picked from commit be17e6e7133a99156191e64ca3ca6233dc0fad0e)

[nrf fromlist] boards: arm: nrf9151dk: fix broken link

---

CMakeLists.txt
lib/libc/newlib/CMakeLists.txt
lib/libc/picolibc/CMakeLists.txt

Pulled PR from upstream that enables LTO on entire application and also fixes compilation issues with nanolib.

[nrf fromlist] buildsystem: Enable LTO also for the application

---

subsys/shell/Kconfig

Shell stack size is too low for OpenThread without joiner functionality, causing overflow. This commit increases it.
upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/69783
Signed-off-by: Maciej Baczmanski <maciej.baczmanski@nordicsemi.no>
(cherry picked from commit 4fb493e49fef245e62df21620382e027a7200907)

[nrf fromlist] kconfig: shell: increase shell stack size for OpenThread

---

west.yml

Some entries had the .git suffix in the repo-path property. While it does not affect e.g. clones, it makes the project URL (built using base url and repo-path) unusable to build other URLs (e.g. to point to a commit, release tag, etc.).
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>
(cherry picked from commit 16a60630830d19c0be6c3118c9dd3f33d03d0ac7)

[nrf fromtree] manifest: remove .git suffixes from repo-paths

---

subsys/bluetooth/host/scan.c

During manual testing with UBSAN enabled, it was found that bt_le_per_adv_sync_cb synced() callback in application sometimes gets unexpected different values in
`sync_info.recv_enabled` field.
The UBSAN output contained the following warnings message: runtime error:
load of value 65, which is not a valid value for type '_Bool'
It tunrned out that struct bt_le_per_adv_sync_synced_info sync_info inside bt_hci_le_past_received_common() contains uninitialized recv_enabled member.
Set it to true by default to avoid possible issues.
(cherry picked from commit 76050859d41d031b78b737ef41640e1fb77f686a)

[nrf fromtree] Bluetooth: add missing initilization of sync_info member

---

boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp.dts
drivers/ieee802154/ieee802154_nrf5.c
modules/hal_nordic/nrfx/nrfx_glue.h

Cherry-pick of upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/68610

Update hal_nordic with nrf 802154

---

modules/mbedtls/Kconfig.psa

!fixup [nrf noup] modules: mbedtls: add PSA configurations
Adding PSA_WANT_ALG_SP800_108_COUNTER_HMAC/CMAC that is part of PSA crypto spec 1.2

[nrf noup] modules: mbedtls: Add PSA_WANT_ALG_SP800_108_COUNTER_XXX

---

dts/arm/nordic/nrf54l_common.dtsi

nrf54l15 write block size

---

scripts/pylib/twister/twisterlib/coverage.py

In case of problem with parsing hex data from coverage dump, do not create empty gcda file.
Such empty file will break gcovr parsing.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/70297

[nrf fromlist] scripts: pylib: twister: twisterlib: prevent empty gcda

---

include/zephyr/bluetooth/bluetooth.h
include/zephyr/bluetooth/gap.h
samples/bluetooth/periodic_adv_rsp/src/main.c
tests/bsim/bluetooth/host/att/pipeline/dut/src/main.c
tests/bsim/bluetooth/ll/cis/src/main.c

Be respectful of PAwR subevents while scheduling scan activities. The radio will be swtiched from scan to PAwR when it is closed to the next subevent interval.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/70678

[nrf fromtree] Samples: Bluetooth: Fix PAwR sample failed to set subevent data

---

subsys/dfu/boot/mcuboot.c

Active partition ID need to be extracted basing on PARTITION_MANAGER products.
ref.:NCSDK-26693
This is alternative patch to https://github.com/nrfconnect/sdk-nrf/pull/14633
similar solution spotted there: https://github.com/nrfconnect/sdk-nrf/blob/main/applications/nrf_desktop/src/modules/dfu.c#L81

[nrf noup] dfu/boot/mcuboot fix img. confirmation in case of PARTITION_MANAGER

---

include/zephyr/net/wifi.h
subsys/net/l2/wifi/wifi_mgmt.c

Once Wi-Fi is associated few parameters like listen interval and power-save mode cannot be changed. The state for association is "ASSOCIATED" and not completed. Even after state transitions to COMPLETE, it can still go back to other states, e.g., PTK/GTK renewal.
Fix the state check.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/70760

[nrf fromlist] net: wifi: Fix the Wi-Fi state check

---

modules/mbedtls/Kconfig

Using a comment to explain Kconfig options make them invisible to Kconfig search. Use help instead.

Use help for DISABLE_MBEDTLS_BUILTIN info

---

scripts/snippets.py

Fixes an issue with paths being output in windows-style with back slashes, this causes issues for certain escape sequences when cmake interprets them. Replace these paths with posix paths so that they are not treated as possible escape sequences.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/69963

[nrf fromlist] scripts: snippets: Fix path output on windows

---

boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20_cpuapp.dts
boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20_cpurad.dts
drivers/entropy/CMakeLists.txt
drivers/entropy/Kconfig
drivers/entropy/Kconfig.nrf_prng
drivers/entropy/fake_entropy_nrf_prng.c
dts/bindings/rng/nordic,nrf-prng.yaml

This adds temporary entropy driver simulation for
nRF54h20 device since final entropy source is not
available yet. This driver is needed to unblock further development on nRF54H20.

[nrf noup] entropy: Add fake entropy nRF PRNG driver needed to run Radio Test and BLE on nRF54h20

---

boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20_cpuapp.dts
boards/arm/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20_cpurad.dts
boards/riscv/nrf54h20dk_nrf54h20/nrf54h20dk_nrf54h20_cpuppr.dts

For both UARTs connected to debugger chip.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71324

[nrf fromlist] boards: nordic: nrf54h20dk: enable HWFC

---

.github/test-spec.yml

All changes in nrf54 boards will trigger low-level testing.

[nrf noup] test-spec: include nrf54 boards in low-level test trigger

---

subsys/net/lib/dns/dns_sd.c

The "struct sockaddr" should only be used in casts and never as a standalone variable because it might not have enough space allocated for all the protocol specific fields. So refactor the port_in_use() function to reflect that.

[nrf fromtree] net: dns-sd: Do not use sockaddr struct directly
