Jenkinsfile

Build on Jenkins
Signed-off-by: Ulrich Myhre <ulmy@nordicsemi.no>

[nrf noup] ci: Add Jenkins-based CI for zephyr

---

include/net/socket.h

Add SOL_SOCKET and sockopt options SO_ERROR, SO_RCVTIMEO and
SO_BINDTODEVICE.
Signed-off-by: Stig Bjørlykke <stig.bjorlykke@nordicsemi.no>

[nrf noup]: Add sockopt options.

---

Jenkinsfile

I don't know what I'm doing....

[DNM] CI fix for PR check

---

CMakeLists.txt
Jenkinsfile
Kconfig.zephyr

This reverts commit 86599ab896febfcdf9a58f6026f49e4a45c3c103.

Revert "[nrf temphack] cmake: Add nRF specific hook"

---

Jenkinsfile

[nrf noup] jenkinsfile: Multiple fixes

---

ext/hal/nordic/nrfx/README
ext/hal/nordic/nrfx/drivers/include/nrfx_nvmc.h
ext/hal/nordic/nrfx/drivers/src/nrfx_nvmc.c

Updates nrfx to the recently released version. See
https://github.com/NordicSemiconductor/nrfx/blob/v1.7.1/CHANGELOG.md
for a list of changes that this version introduces.
Origin: nrfx
License: BSD 3-Clause
URL: https://github.com/NordicSemiconductor/nrfx/tree/v1.7.1
commit: 9d68726e41c321f1772c187bd12d82f5b13104f1
Purpose: Provide peripheral drivers for Nordic SoCs
Maintained-by: External

[nrf fromlist] ext: hal: nordic: Update nrfx to version 1.7.1

---

subsys/settings/src/settings_fcb.c
subsys/settings/src/settings_init.c
tests/subsys/settings/fcb/src/settings_test_fcb.c

Add partition manager support to the settings subsystem.

[nrf temphack] pm: Add partition manager support to 'settings'

---

cmake/target_toolchain.cmake

The opposite of the wanted behavior was achieved.

cmake: bugfix incorrect negation

---

cmake/zephyr_module.cmake
scripts/zephyr_module.py

Reverts and re-implements c5650d5  with default fallback for `--west-path`

Fixup for setting default west-path

---

CMakeLists.txt
arch/arm/core/cortex_m/tz/CMakeLists.txt

This should not be merged until the fromlist commits can be rebased away.
Also: IMAGEify extra_post_build_byproducts

IMAGEify extra_post_build_byproducts

---

Jenkinsfile

Required now that we have windows agents.
also fix stray tabs->spaces

[nrf noup] ci: add linux label to jenkins agent

---

Jenkinsfile

When testing a PR, we only need to build nRF platforms.
Branches and Tags test all platforms (nRF & non-nRF) 
Based on changes from Kamil Gawor's  [PR-154](https://github.com/NordicPlayground/fw-nrfconnect-zephyr/pull/154)
Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>

Jenkinsfile: Build only nRF Platforms for PR's

---

Jenkinsfile

run NRF and upstream sanitycheck in parallel for branch/tag builds

[nrf noup] ci: build NRF sanitycheck on all builds

---

Jenkinsfile

Signed-off-by: Łukasz Hejnak <lukasz.hejnak@nordicsemi.no>

NCSDK-NONE Run all sanitychecks on every PR using zephyr compiler.

---

Jenkinsfile

NCSDK-3166: re-run on QEMU bug in sanitycheck
NCSDK-3160: ci-tools from west manifest
NCSDK-3134: report PENDING to github with callback link

[nrf noup] ci: use ci-tools in west manifest

---

include/arch/arm/cortex_m/scripts/linker.ld

Rename configs used in linker script
Needed by https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1291

[DNM] [nrf noup] cortex_m: linker.ld: Rename FW_METADATA to FW_INFO

---

Jenkinsfile

CI_LIB supplies default if null

[nrf noup] ci: add default values for params

---

CMakeLists.txt
include/arch/arm/cortex_m/scripts/linker.ld

This PR makes the attached code compatible with both ncs master and with the upcoming re-write of multi-image.
This is done to reduce the size of the re-write PR.
Details of the changes are in the commit messages.

Fix s1 variant

---

Jenkinsfile

delete workspaces on all parallel builds immediately after copying results to keep servers cleaner

[nrf noup] ci: cleaning sanity-out immediatly

---

.github/workflows/backport.yml
CODEOWNERS

Using NordicBuilder user and free-tier actions

[nrf noup] ci: Add Github-Actions:Backport-Bot

---

Jenkinsfile

- new cron features
- separate logs for sub-jobs
- more options for downstream jobs.

[nrf noup] ci: adding common cron configuration

---

CMakeLists.txt

This to minimize patches and simplify development
nrf pr https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1778

[nrf noup] cmake: move s1 patches to nrf repo

---

drivers/usb/device/usb_dc_nrfx.c
subsys/usb/class/mass_storage.c

Gets rid of some USB issues for connectivity_bridge application

Cherrypick upstream USB fixes

---

cmake/reports/CMakeLists.txt

This commit was dropped in the last upmerge https://github.com/NordicPlayground/fw-nrfconnect-zephyr/commit/30f47eace36c9593c8f6efacebc75c0f66aa7b17
Discovered by @hakonfam

post upmerge w17 2020

---

subsys/net/l2/openthread/Kconfig
west.yml

Needed for finishing building thread from libraries and c310 support before I go on PTO

Openthread cherrypick build sources and custom mbedtls

---

doc/reference/networking/lwm2m.rst
doc/releases/release-notes-2.5.rst
include/net/lwm2m.h
samples/net/lwm2m_client/src/lwm2m-client.c
subsys/net/lib/lwm2m/lwm2m_engine.c
subsys/net/lib/lwm2m/lwm2m_engine.h
subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c
subsys/net/lib/lwm2m/lwm2m_object.h
subsys/net/lib/lwm2m/lwm2m_rd_client.c
subsys/net/lib/lwm2m/lwm2m_rw_json.c
subsys/net/lib/lwm2m/lwm2m_rw_oma_tlv.c
subsys/net/lib/lwm2m/lwm2m_rw_plain_text.c

Cherrypick LwM2M fixes/improvements for 1.4 release

[nrf fromtree] net: lwm2m: Bootstrap improvements

---

west.yml

This patch fixes bugs in the ieee802154 radio driver

[nrf fromtree] west.yml: Update hal_nordic revision

---

samples/subsys/usb/mass/prj.conf
scripts/zephyr_module.py
subsys/bluetooth/host/gatt.c
subsys/net/l2/openthread/openthread.c
west.yml

This is combining:
#373
#374
#376
#377
`+` hal_nordic update
for a single CI run.
-----
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/3169

373 374 376 377 combined

---

drivers/usb/device/usb_dc_nrfx.c
soc/arm/common/cortex_m/arm_mpu_regions.c
west.yml

This is combining:
#379 
#383
for a single CI run.
Manifest PR: nrfconnect/sdk-nrf#3231

379 383 combined

---

samples/bluetooth/hci_rpmsg/sample.yaml
subsys/settings/src/settings_line.c
west.yml

Upstream PRs:
- https://github.com/zephyrproject-rtos/zephyr/pull/30412
- https://github.com/zephyrproject-rtos/zephyr/pull/30422
and https://github.com/zephyrproject-rtos/zephyr/pull/30421

Single PR for changes needed for the dev-tag

---

scripts/west_commands/runners/nrfjprog.py

See issue for details.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>

[nrf temphack] runners: nrfjprog: hackaround NCSDK-7327

---

boards/arm/nrf21540dk_nrf52840/nrf21540dk_nrf52840.dts
dts/bindings/arm/nordic,nrf21540-fem.yaml

Update nrf21540 DTS to support FEM configuration and update other pins
according to te board datasheet
Signed-off-by: Jakub Pegza <Jakub.Pegza@nordicsemi.no>

[nrf fromtree] boards: arm: nordic: Update DTS for nrf21540

---

boards/arm/nrf5340dk_nrf5340/CMakeLists.txt
boards/arm/nrf5340dk_nrf5340/Kconfig.defconfig
boards/arm/nrf9160dk_nrf9160/CMakeLists.txt

Mix of toup and noup (and temphack).

TFM: configurable memory layout

---

.github/workflows/compliance.yml

- Cherry picks the latest changes to the compliance workflow
- Adds a new `noup` commit with a couple of tweaks

Compliance downstream patches

---

modules/Kconfig.tfm

TFM: Add Kconfig to set MCUBOOT_IMAGE_NUMBER

---

samples/tfm_integration/psa_level_1/sample.yaml
samples/tfm_integration/tfm_ipc/sample.yaml

Mirror of https://github.com/zephyrproject-rtos/zephyr/pull/31931 (Merged)

Tfm sample.yaml fixes

---

scripts/requirements-doc.txt

Fixes backported from `master` branch.

doc: fix documentation build problems

---

samples/tfm_integration/psa_protected_storage/CMakeLists.txt
samples/tfm_integration/psa_protected_storage/README.rst
samples/tfm_integration/psa_protected_storage/prj.conf
samples/tfm_integration/psa_protected_storage/sample.yaml
samples/tfm_integration/psa_protected_storage/src/main.c

Add sample showing PSA Protected Storage API usage
Upstream Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/35226
Signed-off-by: Andreas Vibeto <andreas.vibeto@nordicsemi.no>
sdk-nrf manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/4684

[nrf fromlist] samples: tfm: Add PSA Protected Storage sample

---

include/bluetooth/conn.h
include/bluetooth/hci.h
subsys/bluetooth/controller/ll_sw/nordic/lll/lll.c
subsys/bluetooth/host/adv.c
subsys/bluetooth/host/conn.c
subsys/bluetooth/host/conn_internal.h
subsys/bluetooth/host/gatt.c
subsys/bluetooth/host/hci_core.c
subsys/bluetooth/host/hci_core.h
subsys/bluetooth/host/id.c
subsys/bluetooth/host/l2cap.c
subsys/bluetooth/host/l2cap_internal.h
subsys/bluetooth/host/scan.c
subsys/bluetooth/host/smp.c
subsys/bluetooth/mesh/net.c
subsys/bluetooth/mesh/pb_adv.c
subsys/bluetooth/mesh/rpl.c
subsys/bluetooth/mesh/settings.c

Collection of upstream commits that need to be merged for nRF Connect SDK v1.6.0

Bluetooth: Post-upmerge changes for NCS v1.6

---

drivers/ieee802154/ieee802154_nrf5.c

It fixes: https://projecttools.nordicsemi.no/jira/browse/KRKNWK-10453

openthread: fix frame couters and retransmission for Thread v1.2

---

drivers/timer/nrf_rtc_timer.c
kernel/timeout.c
modules/trusted-firmware-m/CMakeLists.txt
samples/drivers/watchdog/src/main.c
subsys/task_wdt/task_wdt.c

Combined update of:
#548 
#558
#560

548 558 560 combined

---

.github/workflows/footprint-tracking.yml
.github/workflows/footprint.yml

Revert the previous workaround and put in the real fix, which was merged quickly upstream.

Zephyr workflow fix

---

include/dfu/mcuboot.h
include/mgmt/mcumgr/zephyr_groups.h
subsys/dfu/boot/mcuboot.c

Combines #586 and #602 for combined testing in https://github.com/nrfconnect/sdk-nrf/pull/5515.

Merge 586 & 602

---

subsys/bluetooth/mesh/access.c
subsys/bluetooth/mesh/access.h
subsys/bluetooth/mesh/adv.c
subsys/bluetooth/mesh/adv.h
subsys/bluetooth/mesh/cfg_srv.c
subsys/bluetooth/mesh/friend.c
subsys/bluetooth/mesh/prov.c
subsys/bluetooth/mesh/prov.h
subsys/bluetooth/mesh/prov_device.c
subsys/bluetooth/mesh/provisioner.c

Downstreams Bluetooth Mesh bugfixes from upstream PRs:
- zephyrproject-rtos/zephyr#38205
- zephyrproject-rtos/zephyr#38270
- zephyrproject-rtos/zephyr#38312
- zephyrproject-rtos/zephyr#38360

Bluetooth: Mesh: Final set of bugfixes for 1.7

---

drivers/ieee802154/ieee802154_nrf5.c

Introduce fixes for making the CSL Receiver to properly schedule
the reception window.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>
KRKNWK-11203

[nrf fromlist] drivers: nrf5: fixes for the CSL Receiver

---

drivers/timer/nrf_rtc_timer.c
include/drivers/timer/nrf_rtc_timer.h
modules/hal_nordic/nrf_802154/sl_opensource/platform/nrf_802154_lp_timer_zephyr.c
tests/drivers/timer/nrf_rtc_timer/src/main.c

This PR mirrors the upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/39099.

Extend nrf_rtc_timer and nrf_802154_lp_timer

---

drivers/net/Kconfig
drivers/net/ppp.c
subsys/net/l2/ppp/fsm.c
subsys/net/l2/ppp/lcp.c

Cherry-picking ppp updates from merged zephyr PR: [net: ppp: custom MTU/MRU and option to disable autostart in a driver](https://github.com/zephyrproject-rtos/zephyr/pull/40388)

net: ppp: custom MTU/MRU and option to disable autostart in a driver

---

west.yml

Regular upmerge of openthread to fix throughput issue .

[nrf fromtree] openthread: upmerge up to commit c02d1110

---

drivers/flash/soc_flash_nrf.c

This adds the functionality to read memory which are residing in the
secure part of flash from a non-secure application when building with
TF-M.
Currently we check if the address space is not inside the non-secure
applapplication address space. If the address space is outside we do a
request to TF-M so that the secure application can either return success
or fail if the address space is not allowed to be read.

[nrf noup] Add tfm read service to nRF SoC Flash driver

---

drivers/ieee802154/ieee802154_nrf5.c
lib/libc/minimal/include/strings.h
subsys/net/l2/openthread/Kconfig.thread
subsys/net/lib/openthread/platform/logging.c
subsys/net/lib/openthread/platform/openthread-core-zephyr-config.h
subsys/net/lib/openthread/platform/shell.c
west.yml

Cherry-pick latest OpenThread changes.

[nrf fromtree] openthread update

---

subsys/net/l2/openthread/Kconfig.features
subsys/net/lib/openthread/platform/crypto_psa.c

Align with upstream OpenThread changes.

[nrf fromlist] openthread: align changes

---

subsys/bluetooth/Kconfig.adv
subsys/bluetooth/common/Kconfig

- Fixing event buffer length
- Removing the experimental label from Periodic Adv and Sync

Bluetooth: Pull in some changes that are in PRs

---

include/net/lwm2m.h
subsys/net/lib/lwm2m/Kconfig
subsys/net/lib/lwm2m/lwm2m_engine.h
subsys/net/lib/lwm2m/lwm2m_obj_firmware.c
subsys/net/lib/lwm2m/lwm2m_obj_firmware_pull.c

As https://github.com/zephyrproject-rtos/zephyr/pull/41402 didn't make it to the upmerge, this PR brings the commits to sdk-zephyr. 
Also https://github.com/zephyrproject-rtos/zephyr/pull/41598 is brought in this PR.

[nrf fromtree] Lwm2m multi-instanced firmware update object

---

subsys/net/l2/openthread/openthread.c
subsys/net/lib/openthread/platform/radio.c
tests/subsys/openthread/radio_test.c

Add a couple of radio fixes from upstream Zephyr.

[v2.7.99-ncs1] net: openthread: add radio fixes

---

boards/arm/thingy53_nrf5340/thingy53_nrf5340_common.dts

This PR cherry-picks two commits from upstream needed for Thingy53.

[v2.7.99-ncs1] Thingy53 fixes

---

.github/test-spec.yml

Signed-off-by: Elisabeth Solheim Klakken <elisabeth.solheim@nordicsemi.no>

test-spec: Reduce for libmodem and iot samples

---

.github/test-spec.yml

adding CI-mesh-test entries
Signed-off-by: Alperen Sener <alperen.sener@nordicsemi.no>

ci: mesh: add entry

---

drivers/ieee802154/Kconfig
drivers/ieee802154/Kconfig.nrf5
drivers/ieee802154/ieee802154_nrf5.c
modules/mbedtls/Kconfig.tls-generic
subsys/net/l2/openthread/Kconfig.features
subsys/net/lib/openthread/platform/alarm.c
subsys/net/lib/openthread/platform/platform.c
subsys/net/lib/openthread/platform/settings.c
west.yml

Selected OpenThread commits from upstream.

OpenThread upmerge 20220407

---

.github/test-spec.yml

Specialize entries for mosh and positioning tests.

[nrf noup] ci: Update mosh and positioning entiresin test-spec.yml

---

subsys/net/lib/lwm2m/lwm2m_rw_senml_cbor.c

Pulls in two bugfixes from the upstream. Please see the PR zephyrproject-rtos/zephyr#45616 for further details.

Lwm2m SenML CBOR range

---

include/zephyr/arch/arm/aarch32/cortex_m/scripts/linker.ld

linker: remove incorrect check

---

include/zephyr/bluetooth/bluetooth.h
subsys/bluetooth/host/Kconfig
subsys/bluetooth/host/conn.c
subsys/bluetooth/host/hci_core.c
subsys/bluetooth/host/hci_core.h
subsys/bluetooth/host/id.c
subsys/bluetooth/host/id.h

Migrating the upstream changes from the following PR:
https://github.com/zephyrproject-rtos/zephyr/pull/47260

Bluetooth: Host-based Privacy: RPA rotation changes 

---

include/zephyr/bluetooth/conn.h
subsys/bluetooth/host/Kconfig
subsys/bluetooth/host/conn.c
subsys/bluetooth/host/hci_core.c

These fixes are needed for Bluetooth Host qualification.

[nrf fromtree] Cherry-pick fixes needed for GAP/CONN/DCEP/BV-01-C

---

include/zephyr/bluetooth/gatt.h
subsys/bluetooth/host/Kconfig
subsys/bluetooth/host/hci_core.c
subsys/bluetooth/host/l2cap.c
subsys/bluetooth/host/scan.c
subsys/bluetooth/host/settings.c
subsys/bluetooth/host/smp.c

This patch picks some bug fixes and documentation improvements that were not included in the upmerge.

[nrf fromtree] Various Bluetooth Host bug fixes

---

scripts/quarantine.yaml

Add scripts/quarantine.yaml file, which will be used in CI.
Signed-off-by: Piotr Golyzniak <piotr.golyzniak@nordicsemi.no>

[nrf noup] scripts: add quarantine file

---

modules/hal_nordic/nrf_802154/serialization/platform/nrf_802154_spinel_response_notifier.c

Upstream PR:
https://github.com/zephyrproject-rtos/zephyr/pull/50225
Signed-off-by: Artur Hadasz <artur.hadasz@nordicsemi.no>

[nrf fromtree] modules: hal_nordic: nrf_802154 serialization race condition fix

---

scripts/quarantine.yaml

squash! [nrf noup] scripts: add quarantine file
Signed-off-by: Piotr Golyzniak <piotr.golyzniak@nordicsemi.no>

[nrf noup] scripts: update quarantine

---

subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/adv.c
subsys/bluetooth/mesh/adv_ext.c
subsys/bluetooth/mesh/friend.c
subsys/bluetooth/mesh/net.c
subsys/bluetooth/mesh/net.h
subsys/bluetooth/mesh/proxy_srv.c
subsys/bluetooth/mesh/rpl.c
subsys/bluetooth/mesh/transport.c

Added improvements and fixes for extended advertiser to preform better for mesh. All fixes are taken from main branch.
Signed-off-by: Ingar Kulbrandstad [ingar.kulbrandstad@nordicsemi.no](mailto:ingar.kulbrandstad@nordicsemi.no)

[nrf fromtree] Bluetooth: Mesh: Added support for extended advertiser

---

boards/arm/stm32g071b_disco/stm32g071b_disco.dts
drivers/sensor/ina23x/ina230.c
drivers/sensor/ina23x/ina230.h
drivers/sensor/ina23x/ina230_trigger.c
drivers/sensor/ina23x/ina237.c
drivers/sensor/ina23x/ina237.h
drivers/sensor/ina23x/ina23x_common.c
drivers/sensor/ina23x/ina23x_common.h
drivers/sensor/ina23x/ina23x_trigger.c
drivers/sensor/ina23x/ina23x_trigger.h
dts/bindings/sensor/ti,ina230.yaml
dts/bindings/sensor/ti,ina237.yaml
dts/bindings/sensor/ti,ina23x-common.yaml
tests/drivers/build_all/sensor/i2c.dtsi

Required for https://github.com/nrfconnect/sdk-nrf/pull/9197

[nrf fromtree] drivers: ina23x: pull upstream changes

---

doc/develop/getting_started/index.rst

Add reference labels in getting_started/index.rst
Signed-off-by: Uma Praseeda <uma.praseeda@nordicsemi.no>
(cherry picked from commit 90577ee5d8b5ac6eea891134e16aad7b69e239dc)

[nrf fromtree] doc: Add reference labels in getting started doc

---

doc/_extensions/zephyr/link-roles.py
doc/conf.py

Created a custom role for linking to files within modules.

Custom role link module

---

include/zephyr/bluetooth/audio/mcc.h
subsys/bluetooth/audio/mcc.c
subsys/bluetooth/audio/pacs.c
subsys/bluetooth/audio/pacs_internal.h
subsys/bluetooth/audio/unicast_client.c
subsys/bluetooth/shell/mcc.c
tests/bluetooth/bsim_bt/bsim_test_audio/src/mcc_test.c

Updates Zephyr to include MCC fixes

[nrf fromtree] Bluetooth: Audio: Fix issue with NULL instance for MCC

---

.github/test-spec.yml

Signed-off-by: Michał Szablowski <michal.szablowski@nordicsemi.no>

test-spec: matter: update files in CI-matter-test

---

lib/os/spsc_pbuf.c

Get the the spsc hotfix from upstream.

[nrf fromtree] spsc_pbuf: Fix cache wb in spsc_pbuf_free

---

include/zephyr/net/ethernet.h
subsys/net/ip/net_shell.c
subsys/net/l2/ethernet/ethernet.c

Need to test setting custom MAC address by user for testing.

Add shell support for Ethernet MAC address configuration

---

subsys/bluetooth/audio/ascs.c
subsys/bluetooth/audio/endpoint.h
subsys/bluetooth/audio/stream.c

Bugfixes from Zephyr upstream for fixing the connection handle properly.

Fix ascs conn handle issues

---

drivers/net/ppp.c
subsys/net/ip/net_context.c
subsys/net/l2/ethernet/ethernet.c

Pull PR: https://github.com/zephyrproject-rtos/zephyr/pull/53440 into the NCS.

[nrf fromtree] net: ip: net_context: AF_PACKET/SOCK_RAW/IPPROTO_RAW: set pkt family

---

include/zephyr/net/net_stats.h
subsys/net/ip/net_shell.c
subsys/net/l2/ethernet/eth_stats.h
subsys/net/l2/ethernet/ethernet.c
subsys/net/l2/wifi/wifi_shell.c

Though these are minor, but crucial for debugging issues.

Packet error stats

---

subsys/bluetooth/host/Kconfig
subsys/bluetooth/host/gatt.c

Cherry-pick of GATT Caching related fixes to sdk-zephyr.

Bluetooth: host: GATT Caching fixes

---

subsys/net/l2/wifi/wifi_shell.c

[nrf fromlist] Show TWT response parameters details.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/57116

[SHEL-1390] net: shell: Display TWT response details

---

modules/openthread/CMakeLists.txt
modules/openthread/Kconfig.features
modules/openthread/platform/crypto_psa.c
west.yml

Adding implementation of crypto api and removing unneeded options.

Cherry pick openthread zephyr commits

---

.github/test-spec.yml

fixup! [nrf noup] ci: add .github/test-spec.yml

[nrf noup] ci: Add Wi-Fi CI to the Wi-Fi modules

---

include/zephyr/net/socket_ncs.h

Add secure socket options:
* Add CID socket options to NCS specific options.
* Add TLS/DTLS tls ciphersuite chosen socket option to NCS specific options.
* Add TLS/DTLS connection save/load socket options to NCS specific options.
* Add TLS/DTLS handshake status socket option to NCS specific options.

[nrf noup] include: net: add secure socket options

---

include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_mgmt.c

Pulled a dependent commit from #1140  will rebase once its merged.

Add ACK for disconnect

---

subsys/net/l2/wifi/wifi_shell.c

Display MFP info in scan results.
Signed-off-by: Ravi Dondaputi <ravi.dondaputi@nordicsemi.no>
(cherry picked from commit 0889ceaa4e63feed4ed4a223f986c34be26f3830)

[nrf fromtree] net: wifi: Display MFP info in scan results

---

subsys/bluetooth/host/smp.c

If disconnection has been triggered in between the security update and the call to `smp_pairing_complete` we need to abort the pairing.
The disconnection may have been triggered by `bt_unpair`, in that case the keys will have been erased and it will lead to an assertion to continue as if nothing happened.
To resolve this issue, at the beginning of `smp_pairing_complete` the `status` is set to `BT_SMP_ERR_UNSPECIFIED` if there is no connection.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/59807

Find My: fixes for minor release

---

west.yml

This PR cherry-pick 3 commits from upstream tree
commit e0e88394f57f9e48c82bf72fc5668cd1a8be61b4
Author: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Date:   Mon Jul 3 11:38:02 2023 +0200
commit b69cd3cbc101cae3558a4730fa320e25a43b1543
Author: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Date:   Thu Jul 20 15:58:26 2023 +0200
commit b89ff1b3d6816606d24403738844a8257c2db173
Author: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>
Date:   Thu Jul 27 10:32:10 2023 +0200

manifest: Update nrf hw models to latest revision

---

drivers/pwm/pwm_nrfx.c
drivers/spi/spi_nrfx_spi.c
drivers/spi/spi_nrfx_spim.c
modules/hal_nordic/nrfx/nrfx_config_nrf51.h
modules/hal_nordic/nrfx/nrfx_config_nrf52805.h
modules/hal_nordic/nrfx/nrfx_config_nrf52810.h
modules/hal_nordic/nrfx/nrfx_config_nrf52811.h
modules/hal_nordic/nrfx/nrfx_config_nrf52820.h
modules/hal_nordic/nrfx/nrfx_config_nrf52832.h
modules/hal_nordic/nrfx/nrfx_config_nrf52833.h
modules/hal_nordic/nrfx/nrfx_config_nrf52840.h
modules/hal_nordic/nrfx/nrfx_config_nrf91.h
west.yml

This is a cherry-pick of already merged PR https://github.com/zephyrproject-rtos/zephyr/pull/59838
Needed by: KRKNWK-17141, KRKNWK-16393

Cherry pick nrfx 3.1.0 integration

---

doc/connectivity/networking/api/net_tech.rst
doc/connectivity/networking/api/wifi.rst
include/zephyr/net/wifi.h
include/zephyr/net/wifi_mgmt.h
include/zephyr/net/wifi_utils.h
samples/subsys/mgmt/updatehub/src/main.c
scripts/coccinelle/symbols.txt
subsys/net/ip/net_private.h
subsys/net/l2/Kconfig
subsys/net/l2/wifi/CMakeLists.txt
subsys/net/l2/wifi/Kconfig
subsys/net/l2/wifi/wifi_mgmt.c
subsys/net/l2/wifi/wifi_shell.c
subsys/net/l2/wifi/wifi_utils.c

wifi: Scan extensions

---

.github/test-spec.yml

Update Thread test-spec entry.

[nrf noup] ci: Update Thread test-spec entry

---

scripts/quarantine.yaml

fixup! [nrf noup] ci: scripts: add quarantine file

[nrf noup] ci: scripts: add quarantine file

---

.github/workflows/compliance.yml

fixup! [nrf noup] ci: NCS-specific CI tweaks
Disable the enw KconfigNoModules check.

[nrf noup] ci: NCS-specific CI tweaks

---

doc/releases/release-notes-3.5.rst
modules/Kconfig.mcuboot
samples/subsys/mgmt/mcumgr/smp_svr/sample.yaml
subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt_state.c

MCUmgr additions for DirectXIP with revert.

---

doc/releases/release-notes-3.5.rst
doc/services/device_mgmt/smp_groups/smp_group_0.rst
include/zephyr/mgmt/mcumgr/grp/os_mgmt/os_mgmt.h
modules/Kconfig.mcuboot
subsys/mgmt/mcumgr/grp/os_mgmt/CMakeLists.txt
subsys/mgmt/mcumgr/grp/os_mgmt/Kconfig
subsys/mgmt/mcumgr/grp/os_mgmt/src/os_mgmt.c

~~Depends on https://github.com/nrfconnect/sdk-nrf/pull/12460~~

MCUboot info PRs. Fromtree.

---

include/zephyr/net/zperf.h
subsys/net/lib/zperf/zperf_common.c
subsys/net/lib/zperf/zperf_internal.h
subsys/net/lib/zperf/zperf_shell.c
subsys/net/lib/zperf/zperf_tcp_receiver.c
subsys/net/lib/zperf/zperf_udp_receiver.c

Zperf multicast improvements

---

scripts/ci/test_plan.py
scripts/ci/twister_ignore.txt
scripts/pylib/twister/twisterlib/environment.py
scripts/pylib/twister/twisterlib/reports.py
scripts/pylib/twister/twisterlib/testinstance.py
scripts/pylib/twister/twisterlib/testplan.py
scripts/pylib/twister/twisterlib/testsuite.py
scripts/tests/twister/test_harness.py
scripts/tests/twister/test_testsuite.py

Bring in needed changes for dynamic test scope selection for twister

Plan test upmerge

---

lib/libc/newlib/Kconfig

fixup![nrf fromlist] wifi: Add the enums to the status
This was only for local testing and by mistake got merged.

[nrf noup] newlib: Revert unintended change

---

boards/arm/bl5340_dvk/bl5340_dvk_cpuapp_ns.dts
boards/arm/bt610/bt610.dts
boards/arm/mg100/mg100.dts
boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp.yaml
boards/arm/nrf5340dk_nrf5340/nrf5340dk_nrf5340_cpuapp_ns.yaml
boards/arm/pinnacle_100_dvk/pinnacle_100_dvk.dts
boards/arm/ubx_bmd340eval_nrf52840/ubx_bmd340eval_nrf52840.dts
boards/arm/ubx_bmd345eval_nrf52840/ubx_bmd345eval_nrf52840.dts
boards/arm/ubx_bmd380eval_nrf52840/ubx_bmd380eval_nrf52840.dts
samples/drivers/spi_flash/README.rst
samples/drivers/spi_flash/sample.yaml

Before that change the sample was filtered out by the Twister

Modify filter for spi_flash sample

---

include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_shell.c

Updated to provide regulatory channel information along with country code.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/67294

[nrf fromlist] net: mgmt: Provide Regulatory channel info

---

doc/releases/release-notes-3.6.rst
drivers/ieee802154/Kconfig
drivers/ieee802154/ieee802154_nrf5.c
drivers/ieee802154/ieee802154_nrf5.h
include/zephyr/net/ieee802154_pkt.h
modules/openthread/platform/radio.c
west.yml

Cherry-pick commits introduced upstream in https://github.com/zephyrproject-rtos/zephyr/pull/67137

Update nRF IEEE 802.15.4

---

boards/arm/nrf9151dk_nrf9151/Kconfig.board
boards/arm/nrf9151dk_nrf9151/Kconfig.defconfig
boards/arm/nrf9151dk_nrf9151/board.cmake
boards/arm/nrf9151dk_nrf9151/doc/index.rst
boards/arm/nrf9151dk_nrf9151/dts/bindings/nordic,nrf9151dk-nrf5340-reset.yaml
boards/arm/nrf9151dk_nrf9151/dts/nrf9151dk_buttons_on_io_expander.dtsi
boards/arm/nrf9151dk_nrf9151/dts/nrf9151dk_leds_on_io_expander.dtsi
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151.dts
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151.yaml
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_common-pinctrl.dtsi
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_common.dtsi
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_defconfig
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_ns.dts
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_ns.yaml
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_ns_defconfig
boards/arm/nrf9151dk_nrf9151/nrf9151dk_nrf9151_partition_conf.dtsi
boards/arm/nrf9151dk_nrf9151/pre_dt_board.cmake
drivers/sensor/adxl367/adxl367.c
dts/arm/nordic/nrf9151_laca.dtsi
dts/arm/nordic/nrf9151ns_laca.dtsi
soc/arm/nordic_nrf/nrf91/Kconfig.defconfig.nrf9151_LACA
soc/arm/nordic_nrf/nrf91/Kconfig.soc

Cherrypick upstream Zephyr changes needed for the thingy91x board

Cherrypick for thingy91x board

---

dts/arm/nordic/nrf54l_common.dtsi

Initial CRACEN support

---

west.yml

update tinycrypt revision to fix
warnings reported by ubsan
Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>
(cherry picked from commit 8f458bb51f1f3b47fbde4f8730687275dcee8a21)
Signed-off-by: Ivan Iushkov <ivan.iushkov@nordicsemi.no>

[nrf fromtree] modules: crypto: update tinycrypt revision

---

modules/mbedtls/Kconfig.psa
modules/trusted-firmware-m/Kconfig.tfm.crypto_modules

TF-M  PAKE support

---

west.yml

Fix address checking function for nrf54h20.
(cherry picked from commit 9504e6bb16bd5dab124786eef74522eb4387b91a)

[nrf fromlist] manifest: Update hal_nordic with DMA address check fix

---

subsys/net/lib/http/http_client.c

Correct various small edge-case behaviors that have been accidentally introduced in the http_client.
- http_client_req no longer incorrectly returns -ETIMEDOUT on NULL HTTP resonse. -ETIMEDOUT is now only returned when the underlying TLS socket times out.
- http_client_req now returns -ECONRESET upon incomplete (but non-NULL) HTTP response. The request callback is no longer called in this case (as with any other error state).
- http_wait_data has been refactored slightly to increase clarity.
Signed-off-by: Georges Oates_Larsen <georges.larsen@nordicsemi.no>
(cherry picked from commit https://github.com/zephyrproject-rtos/zephyr/pull/70911/commits/30c7d0920c9b03dd15f9ac1913738c290c003275)

[nrf fromtree] net: lib: http: Correct http_client edge-case behavior

---

boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp-pinctrl.dtsi
boards/arm/nrf54l15pdk_nrf54l15/nrf54l15pdk_nrf54l15_cpuapp.dts

Define RTS and CTS pins.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/71605

[nrf fromlist] boards: nordic: nrf54l15pdk: enable HWFC

---

subsys/net/ip/tcp.c
tests/net/tcp/src/main.c

[v3.5.99-ncs1-branch] net: tcp: FIN with data fixes 

---

subsys/bluetooth/host/hci_core.h
subsys/bluetooth/host/scan.c

Cherry-picks the fix from upstream zephyr

 Bluetooth: Host: Fix auto-connect/sync establishment on Coded PHY

---

drivers/flash/soc_flash_nrf_rram.c

fromlist: https://github.com/zephyrproject-rtos/zephyr/pull/71825
Non-secure images cannot reference NRF_RRAMC_NS because NRF_RRAMC_NS
does not exist.
TF-M will configure RRAMC according to these Kconfig's before booting
the non-secure image so we ifdef out this code.
Also, rewrite the implementation of commit_changes to also work when
the commit task is not available.

[nrf fromlist] drivers: nrf: rram: Support TF-M

---

arch/arm/core/mpu/arm_mpu.c
boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20-memory_map.dtsi
boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts
boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuppr.yaml
drivers/pinctrl/pinctrl_nrf.c
drivers/spi/spi_nrfx_spim.c
tests/drivers/spi/spi_controller_peripheral/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/drivers/spi/spi_controller_peripheral/boards/nrf54h20dk_nrf54h20_cpuapp_fast.overlay
tests/drivers/spi/spi_controller_peripheral/boards/nrf54h20dk_nrf54h20_cpurad.overlay
tests/drivers/spi/spi_controller_peripheral/src/main.c
tests/drivers/spi/spi_controller_peripheral/testcase.yaml
tests/drivers/spi/spi_error_cases/boards/nrf54h20dk_nrf54h20_cpuapp_fast.overlay
tests/drivers/spi/spi_error_cases/boards/nrf54h20dk_nrf54h20_cpuppr.overlay
tests/drivers/spi/spi_error_cases/boards/nrf54h20dk_nrf54h20_cpuppr_launcher.overlay
tests/drivers/spi/spi_error_cases/src/main.c
tests/drivers/spi/spi_error_cases/testcase.yaml
tests/drivers/spi/spi_loopback/boards/nrf54h20dk_nrf54h20_cpuapp_fast.overlay
tests/drivers/spi/spi_loopback/testcase.yaml
west.yml

Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/73545

nrf54h20: add support for fast SPIM12x instances

---

scripts/ci/check_compliance.py
scripts/west_commands/runners/core.py
scripts/west_commands/runners/nrf_common.py

Handle MPI and root manifest for radio core separately from the main build system logic.
Ref: NCSDK-27790, NCSDK-27874

scripts: nrf_common: Handle SUIT artifact

---

subsys/bluetooth/mesh/Kconfig
subsys/bluetooth/mesh/lpn.c
subsys/bluetooth/mesh/pb_gatt_srv.c

Upstream mesh fixes needed for ncs v2.7

Mesh upstream fixes

---

subsys/ipc/ipc_service/backends/ipc_icbmsg.c

This is implementation of ICBMsg endpoint deregistration. The underlying ICMsg instance and blocks are not affected by deregistration, so it is possible to reuse the same address during the re-registration of the same endpoint.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74243

[nrf fromlist] icbmsg: Allow deregistration of the endpoints

---

drivers/gpio/gpio_gecko.c
include/zephyr/sys/crc.h
include/zephyr/sys/util.h
lib/crc/CMakeLists.txt
lib/crc/crc24_sw.c
lib/crc/crc_shell.c
tests/unit/crc/main.c
tests/unit/util/main.c

Combined PRs #1808 and #1809 to get CI checks in one run.

Combined PRs #1808 and #1809

---

drivers/flash/Kconfig.nrf_rram
soc/nordic/nrf54l/soc.h

upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/74589
manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/16109

Flashtimeoutfixes

---

subsys/net/lib/dhcpv4/dhcpv4.c
subsys/net/lib/dhcpv4/dhcpv4_internal.h

net: dhcpv4: Reimplement RENEW/REBIND logic according to RFC2131

---

modules/hal_nordic/nrfs/backends/nrfs_backend_ipc_service.c
modules/hal_nordic/nrfs/dvfs/ld_dvfs.c
modules/hal_nordic/nrfs/dvfs/ld_dvfs_handler.c

nrf-squash! [nrf noup] boards: nordic: By default turn off NRFS for ztest

[nrf noup] boards: nordic: Change NRFS logs to debug level

---

doc/_extensions/zephyr/kconfig/__init__.py
scripts/ci/check_compliance.py
scripts/ci/test_plan.py
scripts/list_boards.py
scripts/west_commands/boards.py

Board/SoC extensions: additional changes

---

tests/drivers/adc/adc_accuracy_test/boards/nrf52840dk_nrf52840.overlay
tests/drivers/adc/adc_accuracy_test/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/drivers/adc/adc_accuracy_test/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay
tests/drivers/adc/adc_accuracy_test/testcase.yaml
tests/drivers/adc/adc_api/boards/nrf54h20dk_nrf54h20_cpuapp.overlay
tests/drivers/adc/adc_api/boards/nrf54l15pdk_nrf54l15_cpuapp.overlay

Extend testing adc with nrf devices

[nrf fromlist] tests: drivers: adc_accuracy

---

modules/openthread/Kconfig.thread
modules/openthread/platform/radio.c
subsys/net/l2/openthread/openthread.c

Implementation of functionality whitch configure CIDR for OT NAT64.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/75012

[nrf fromlist] net: openthread: Set CIDR for NAT64

---

subsys/net/ip/ipv6.c
subsys/net/ip/ipv6_nbr.c
subsys/net/ip/net_core.c
tests/net/socket/misc/src/main.c

This PR cherry-picks changes from upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76150

Cherry-pick IPv6 routing changes

---

include/zephyr/net/net_ip.h
subsys/net/ip/ipv6.c
subsys/net/ip/route.c
subsys/net/ip/route.h

This PR contains two commits related to multicasts that are already a part of the upstream

Cherry-pick mulitcast related changes

---

subsys/net/ip/ipv6.c
subsys/net/ip/route.c

This PR cherry-picks contains commits from upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76417

net: ipv6: cherry pick further routing improvements

---

drivers/watchdog/Kconfig.nrfx
drivers/watchdog/wdt_nrfx.c
modules/hal_nordic/nrfx/nrfx_config.h

sdk-nrf PR to check with CI
https://github.com/nrfconnect/sdk-nrf/pull/16739

Nrfx wdt driver without irq

---

.github/test-spec.yml

Updated label name, added new entries to trigger CI.

[nrf-noup] test-spec: update CI-boot-test

---

subsys/net/ip/route.c

This commit moves reading nexthop's LL address only if it's supported by a given neighbor and can be used for routing between interfaces.
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/76731

net: ipv6: route: get nexthop's LL address only if relevant

---

modules/mbedtls/Kconfig.psa

Remove the deprecated PSA_WANT_KEY_TYPE_ECC_KEY_PAIR Kconfig
ref: NCSDK-27160

[nrf noup] modules: mbedtls: remove deprecated Kconfig

---

subsys/bluetooth/controller/Kconfig
subsys/bluetooth/host/conn.c
tests/bluetooth/shell/testcase.yaml

Cherry pick upstream Path Loss Monitoring fixes.

Cherrypick plm fixes

---

boards/native/nrf_bsim/doc/nrf54l15bsim.rst
boards/native/nrf_bsim/nrf54l15bsim_nrf54l15_cpuapp.dts
west.yml

Downmerge
https://github.com/zephyrproject-rtos/zephyr/pull/77893 
&
https://github.com/zephyrproject-rtos/zephyr/pull/77942

Downmerge nrf54l15bsim upd

---

drivers/mbox/mbox_nrf_vevif_task_rx.c

Allow using direct IRQs (which are obligatory when buiding with `CONFIG_GEN_SW_ISR_TABLE=n`).
Upstream PR: https://github.com/zephyrproject-rtos/zephyr/pull/79657

[nrf fromtree] drivers: mbox: nrf_vevif_task_rx: align to direct IRQs

---

.github/workflows/commit-tags.yml

nrf-squash! [nrf noup] ci: NCS-specific CI tweaks
Adapt to the changes in:
https://github.com/nrfconnect/action-commit-tags/pull/4

[nrf noup] workflows: Update the commit tags action

---

doc/services/ipc/ipc_service/backends/icbmsg_flows.svg
doc/services/ipc/ipc_service/backends/icbmsg_memory.svg
doc/services/ipc/ipc_service/backends/icbmsg_message.svg
doc/services/ipc/ipc_service/backends/ipc_service_icbmsg.rst

The details of how the ICBMsg communication is done, are hidden inside the source code. This specification adds details about the ICBMsg protocol.
Upstream commit: https://github.com/zephyrproject-rtos/zephyr/commit/8d99393530adf8d478027996fd055bfb306ff3c9

[nrf fromtree] doc: ipc: Add detailed protocol specs for ICBMsg backend

---

dts/common/nordic/nrf54l15.dtsi
samples/boards/nordic/nrf_sys_event/CMakeLists.txt
samples/boards/nordic/nrf_sys_event/prj.conf
samples/boards/nordic/nrf_sys_event/sample.yaml
samples/boards/nordic/nrf_sys_event/src/main.c
soc/nordic/common/CMakeLists.txt
soc/nordic/common/Kconfig
soc/nordic/common/nrf_sys_event.c
soc/nordic/common/nrf_sys_event.h

Pull in sys nrf event

---

doc/zephyr.doxyfile.in
include/zephyr/bluetooth/audio/bap.h
include/zephyr/net/socket.h
include/zephyr/net/socket_select.h

Some documentation fixes

---

subsys/dfu/boot/mcuboot_shell.c

fixup! [nrf noup] tree-wide: support NCS Partition Manager (PM) definitions
Adds in checks for partition manager to prevent users from erasing the MCUboot partition or the currently active partition

[nrf noup] dfu: boot: mcuboot_shell: Prevent erasing active areas

---

subsys/dfu/boot/mcuboot_shell.c

Backport 25f14b4f8ecba7423f39ead3c117c0d86a096c5b from #2114.

[Backport v3.7.99-ncs1-branch] [nrf noup] dfu: boot: mcuboot_shell: Prevent erasing active areas

---

drivers/timer/nrf_grtc_timer.c

This commit allows to switch the GRTC clock source to an RC oscillator.
Upstream PR #: 80622

[nrf fromlist] drivers: timer: grtc: Add LFPRC as the source of GRTC

---

drivers/wifi/nrfwifi/Kconfig.nrfwifi
west.yml

Pulling fix for EAP AKM for WPA2-SHA256

wifi: nrf70: Fix EAP AKM

---

modules/Kconfig.mcuboot
samples/subsys/mgmt/mcumgr/smp_svr/prj.conf
subsys/mgmt/mcumgr/grp/img_mgmt/include/mgmt/mcumgr/grp/img_mgmt/img_mgmt_priv.h
subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt.c
subsys/mgmt/mcumgr/grp/img_mgmt/src/img_mgmt_state.c

Fix MCUmgr support for images hashed with sha512

---

drivers/pwm/pwm_nrfx.c

Add pin retenion if GPD is enabled for nRF54H20.
Upstream PR #: 80672

[nrf fromlist] drivers: pwm: nrfx: add pin retention

---

soc/nordic/soc.yml

To properly execute erase, recover and reset.
Upstream PR #: 81420

soc: nordic: add configuration for nrf54h20 flpr core

---

drivers/wifi/nrf_wifi/src/wifi_mgmt_scan.c
west.yml

1. Pull EAP-TLS-SHA256 display type fix
2. Latest interface files

wifi: Pull latest fixes

---

modules/hal_nordic/CMakeLists.txt

Bump nrf regtool v8.1.2 ncs

---

drivers/clock_control/clock_control_nrf.c

When using synthesized low frequency clock, HFXO should be running to ensure correct frequency.
Signed-off-by: Michał Stasiak <michal.stasiak@nordicsemi.no>
(cherry picked from commit 9a476674681d38d68a83d169c8d870f97119e786)

[nrf fromtree] drivers: clock_control: nrf: start HFXO when using LFSYNTH

---

drivers/pwm/pwm_nrfx.c

Fast PWM120 prevents GPIO from driving pin with low/high state when PWM duty is 0% or 100%. In such case, regular PWM signal generation needs to be used.
Upstream PR #: 83652

[nrf fromtree] drivers: pwm: nrfx: 0/100% duty for PWM120

---

drivers/clock_control/clock_control_nrf2_fll16m.c
dts/bindings/clock/nordic,nrf-fll16m.yaml
dts/common/nordic/nrf54h20.dtsi
tests/drivers/clock_control/nrf_clock_control/src/main.c

Cherry pick fll16m remove closed loop

Cherry pick fll16m remove closed loop

---

drivers/clock_control/clock_control_nrf2_fll16m.c
dts/bindings/clock/nordic,nrf-fll16m.yaml
dts/common/nordic/nrf54h20.dtsi
tests/drivers/clock_control/nrf_clock_control/src/main.c

Backport h20 fll16m remove closed loop

Backport h20 fll16m remove closed loop

---

drivers/flash/flash_mspi_nor.c

QE bit is non-volatile, so do not assume chip will be in single mode at init.

drivers: flash: mspi_nor: switch mode explicitly

---

soc/nordic/nrf54h/pm_s2ram.c

For the Suspend to RAM procedures the SCB content
also needs to be retained.
Upstream PR #: 86777

[nrf fromlist] soc: nordic: nrf54h: Add SCB retention for s2ram

---

drivers/audio/dmic_nrfx_pdm.c

Added queue for memory slab addresses to ensure that they are released in correct order. Improved formula for frequency scaling for nRF54H20. Fixed alternative channel mapping.
Signed-off-by: Michał Stasiak <michal.stasiak@nordicsemi.no>
Signed-off-by: Sebastian Głąb <sebastian.glab@nordicsemi.no>
(cherry picked from commit 8260e1ff5cc4f25ef9f54a8717917016015df707)

[nrf fromtree] drivers: audio: dmic_nrfx: improvements to driver

---

subsys/bluetooth/mesh/proxy_srv.c
tests/bluetooth/tester/src/btp/btp_mesh.h
tests/bluetooth/tester/src/btp_mesh.c

Cherry picking the upstream fixes needed for Private Network Beacons for PTS

Mesh pts test bug fix for pnid

---

tests/drivers/uart/uart_async_api/src/test_uart_async.c

When CONFIG_COVERAGE is enabled then performance is degraded. In that case higher baudrates shall be avoided because CPU may not have enough time to handle UART interrupts. Limit baudrate to 115200 when CONFIG_COVERAGE=y.
Upstream PR #: 87386

[nrf fromlist] tests: drivers: uart: async_api: Align test to gcov

---

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts
boards/nordic/nrf9280pdk/nrf9280pdk_nrf9280_cpuapp.dts
drivers/flash/flash_mspi_nor.c
drivers/flash/flash_mspi_nor.h
drivers/flash/flash_mspi_nor_quirks.h
drivers/flash/spi_nor.h

Bring in updated flash_mspi_nor driver.

drivers: flash: mspi_nor: update

---

drivers/pinctrl/pinctrl_nrf.c
include/zephyr/dt-bindings/pinctrl/nrf-pinctrl.h
samples/basic/blinky/boards/nrf54l15dk_nrf54l15_cpuapp_hpf_gpio.overlay

Rename SDP to HPF (High Performance Framework).

Nrfx 7252 rename to hpf

---

modules/nrf_wifi/bus/spi_if.c

Backport 276b91c420806449650fcf452e72045085739322 from #2750.

[Backport v4.0.99-ncs1-branch] [nrf fromtree] modules: nrf_wifi: spi: Implement frequency switching

---

include/zephyr/bluetooth/gatt.h
subsys/bluetooth/host/cs.c
tests/bluetooth/gatt/src/main.c
tests/bsim/bluetooth/host/gatt/ccc_store/src/central.c
tests/bsim/bluetooth/host/gatt/ccc_store/src/peripheral.c

Cherry pick upstream changes

---

west.yml

wifi: Fix low RSSI disconnections

---

west.yml

[nrf fromlist] manifest: Update nrf_wifi for Raw modes boot failure

---

boards/index.rst

zephyr: doc: fix board page

---

west.yml

Cherry-picks the newest bsim models.
The commits include commits needed for testing

Update bsim models

---

samples/bluetooth/bap_broadcast_assistant/src/main.c

Modify the reset function to also reset the connection and PA sync states.
Modify and add missing checks for mutex locks to use ASSERT when using K_FOREVER, as they should never fail/timeout.
Cleanup some text and error checks.
Ensure that the add_src_param is reset for each loop iteration as well.
Modify so that we use K_FOREVER fewer places.
(cherry picked from commit 117dca089ab5a5504b059b397fceb1524f787715)

[nrf fromtree] samples: Bluetooth: BAP: BA: Reset states and modify error checking

---

tests/drivers/clock_control/nrf_clock_control/src/main.c

Add the resolve and get_startup_time call
Upstream PR #: 93141
(cherry picked from commit 632aad17eaab2a0fa50258b47d8732d37d274c08)

[nrf fromlist] tests: drivers: nrf_clock_control: Test extended API

---

samples/drivers/adc/adc_dt/boards/nrf54lm20dk_nrf54lm20a_cpuapp.overlay
samples/drivers/adc/adc_sequence/boards/nrf54lm20dk_nrf54lm20a_cpuapp.overlay
tests/drivers/adc/adc_accuracy_test/boards/nrf54lm20dk_nrf54lm20a_cpuapp.overlay

Pull in fixes from https://github.com/zephyrproject-rtos/zephyr/pull/93633

Nrfx 7936 nrfx 7936 enable samples and tests on nrf54lm20a pt4

---

scripts/pylib/pytest-twister-harness/src/twister_harness/device/hardware_adapter.py
scripts/pylib/twister/twisterlib/handlers.py

[nrf fromtree] scripts: twister: handlers: Append dev-id for nrfutil_next

---

boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpuapp.dts
boards/nordic/nrf54h20dk/nrf54h20dk_nrf54h20_cpurad.dts

Add secondary_app_partition aliases.

[nrf fromtree] boards: Add secondary_app_partition alias
